confluentinc/cp-ansible

roles/confluent.common/defaults/main.yml, roles/confluent.kafka-broker/defaults/main.yml, roles/confluent.kafka-broker/templates/server.properties.j2, roles/confluent.kafka-broker/templates/server_sasl_ssl.properties.j2, roles/confluent.kafka-broker/templates/server_ssl.properties.j2
Kafka Cluster of 1 broker was failing to start with the default metrics reporter replication factor, so added these defaults 
```yaml
confluent:
+  support:
+    customer_id: anonymous
+    metrics_enabled: true
kafka:
broker:
config:
+      confluent.metrics.reporter.topic.replicas: 3
```
Also updated `server.properties` with the relevant settings. 
Ideally, that bottom piece should be broken out to a [separate template and included in the rest](https://stackoverflow.com/a/42760481/2308683)
=> Added variables for Confluent MetricsReporter

all.yml, plaintext/all.yml, roles/confluent.connect-distributed/defaults/main.yml, roles/confluent.control-center/defaults/main.yml, roles/confluent.control-center/templates/includes/base_control-center.properties.j2, roles/confluent.ksql/defaults/main.yml, roles/confluent.schema-registry/defaults/main.yml, sasl_ssl/all.yml, ssl/all.yml
Closes #48 
Needed to pull out listener ports for Schema Registry and KSQL listener ports outside of the top config keys because doing `{{ksql.config.port}}` or `{{ksql.listener_port}}`, for example, was throwing a recursive property error.
=> Integrate KSQL,Schema Registry,Connect and Control Center

roles/confluent.connect-distributed/templates/includes/base_connect-distributed.properties.j2, roles/confluent.connect-distributed/templates/includes/schema_registry_urls.j2
Closes #36 
`connect-distributed.properties` had a hard-coded port number for the Schema Registry. This makes it configurable per Schema Registry host.
=> Use Schema Registry Port variable for Connect AvroConverters

roles/confluent.kerberos/defaults/main.yml, roles/confluent.kerberos/templates/krb5.conf.j2
documented variable to use is realm not realm_name, so the kerberos config automatically gets set to confluent.example.com
tested with kerberos playbook and realm name (!= confluent.example.com), services came up
=> kerberos realm hardcoded to confluent.example.com

group_vars/all/shared_vars.yml, hosts_example.yml, roles/confluent.common/tasks/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/files/kafka.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.variables/defaults/main.yml
Added [JMX Exporter](https://github.com/prometheus/jmx_exporter) support to kafka broker. When enabled, this will make many of the broker's JMX metrics available via HTTP for consumption in Prometheus.
Dependencies: this will download the JMX exporter jar.
Tested with Confluent Platform 5.3.x.
**Test Configuration**: 
* CP 5.3.1
* set jmxexporter_enabled: true in hosts.yml (inventory file)
=> JMX exporter support

hosts_example.yml
Modified the example hosts file, specifically changed the variable ansible_ssh_user to ansible_user due to deprecation as per the Ansible documentation here:
https://ansible-tips-and-tricks.readthedocs.io/en/latest/ansible/inventory/
https://github.com/confluentinc/cp-ansible/issues/95
Ran the playbook with plaintext across all components, as well as with SSL across all components with the variable change.
=> Changed ansible_ssh_user to ansible_user due to deprecation.

hosts_example.yml
Corrected the variable name ssl_provided_keystore_and_truststore.  Was missing the 'ssl_'.
Deployed on RHEL 7 in test environment.
=> Corrected variable name ssl_provided_keystore_and_truststore.

roles/confluent.common/tasks/main.yml, roles/confluent.variables/defaults/main.yml
Services fail to start due to insufficient privileges to jolokia.jar which is enabled by default.
Nov 07 00:33:47 sbx-kafka-jontest-zookeeper-2 systemd[1]: confluent-zookeeper.service failed.
Nov 07 00:33:51 sbx-kafka-jontest-zookeeper-2 systemd[1]: Started Apache Kafka - ZooKeeper.
Nov 07 00:33:51 sbx-kafka-jontest-zookeeper-2 zookeeper-server-start[3110]: Error opening zip file or JAR manifest missing : /opt/jolokia/jolokia.jar
Nov 07 00:33:51 sbx-kafka-jontest-zookeeper-2 zookeeper-server-start[3110]: Error occurred during initialization of VM
Nov 07 00:33:51 sbx-kafka-jontest-zookeeper-2 systemd[1]: confluent-zookeeper.service: main process exited, code=exited, status=1/FAILURE
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and …
=> Allow services to read jolokia.jar

roles/confluent.variables/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml
When providing a custom zookeeper dataDir (ie: /data1), the directory does not have the necessary ownership and permissions for the zookeeper service to start.
When providing a custom zookeeper dataDir (ie: /data1), the directory does not have the necessary ownership and permissions for the zookeeper service to start / create the `version-2` directory.
Verified functionality against test cluster.
3 broker / 3 …
=> Set Zookeeper dataDir ownership

roles/confluent.kafka_broker/templates/server.properties.j2, roles/confluent.variables/defaults/main.yml
Fixes #162
I tested this configuration in my lab. After the change advertisements were fully qualified. 
The following configuration was used for testing.
```yaml
kafka_broker_default_listeners:
external:
hostname: "{{ansible_fqdn}}"
internal:
hostname: "{{ansible_fqdn}}"
```
Expected output:
```properties
listeners=EXTERNAL://primary-broker-001.custenborder.com:9092,INTERNAL://primary-broker-001.custenborder.com:9091
```
=> Added support to specify the hostname for a listener. Fixes #162.

roles/confluent.common/defaults/main.yml, roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml
Adds a variable and check to optional install Netcat within the common role
Fixes # N/A
Simple test against fresh AWS cluster with `install_netcat` set to false within the `hosts.yaml` file.
3x ZK
3x Kafka
1x Control Center
=> Make Netcat Optional with a var

tasks/create_ordered_kafka_groups.yml, upgrade_kafka_broker.yml, upgrade_kafka_broker_log_format.yml
Now the upgrade kafka playbooks take extra care to do restarts on the controller last
Tested locally, with 3 broker cluster, will run it through jenkins as well
=> Upgrade kafka playbooks now make sure controller is last to be touched before any restarts

roles/confluent.control_center/templates/control-center.properties.j2
moving away from deprecated variable and naming the single ksql cluster default, as connect is named
Ran basic install and made sure ksql is in c3 as before
=> Fixing Deprecated ksql property in c3

roles/confluent.common/tasks/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.ksql/defaults/main.yml, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml
Customer discovered bug that permissions on /opt/prometheus/kafka.yml were causing start up to fail. I also introduced additional vars to make each service's jolokia/prometheus exporters togglable
Tested with jmx_exporter_enabled set to true/false
All service start as normal, with health checks passing
=> Fixes to jolokia and prometheus vars + bug fix on file permissions

roles/confluent.kafka_broker/templates/listener.j2
Fixes an issue when the admin account of sasl_scram_users group is used for the PLAIN authentication method instead of that of the sasl_plain_users group in the broker listener configuration.
=> Fix admin user reference for SASL_PLAIN listener

roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.zookeeper/tasks/health_check.yml, roles/confluent.zookeeper/tasks/main.yml, upgrade_zookeeper.yml
Netcat is not allowed on our systems due to the security constraints.
Instead of netcat, make use of bash's file descriptor redirection.
Link:
* https://www.gnu.org/software/bash/manual/html_node/Redirections.html#Redirections
- [?] Bug fix (non-breaking change which fixes an issue)
- [?] Breaking change (fix or feature that would cause existing functionality to not work as expected)
I have tested the installation of zookeeper with this code change.
I have _NOT_ tested the upgrade of zookeeper.
- [partial] I have performed a self-review of my own code
=> Remove netcat

all.yml, hosts_example.yml, roles/confluent.variables_handlers/defaults/main.yml, upgrade_control_center.yml, upgrade_kafka_broker.yml, upgrade_kafka_connect.yml, upgrade_kafka_rest.yml, upgrade_ksql.yml, upgrade_schema_registry.yml, upgrade_zookeeper.yml
Now can set proxy env vars for duration of playbook run. Simply need to set a dictionary in your hosts.yml
Tested that the env vars get set when you set the variable in hosts.yml and if you do not nothing breaks
=> configure proxy env vars

filter_plugins/filters.py, hosts_example.yml, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/templates/server.properties.j2, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.ssl/tasks/create_keystore_and_truststore.yml, roles/confluent.ssl/tasks/main.yml, roles/confluent.ssl/tasks/self_signed_certs.yml, roles/confluent.ssl/templates/openssl-san.cnf.j2, roles/confluent.variables_handlers/defaults/main.yml, tasks/certificate_authority.yml
Can now have a hostname on each listener (which helps in aws land) and those hostnames get set in the autogenerated certs in the extension
Also now ssl role has a task that checks if keystores/truststores are created before running everything
=> adding advertised listeners property, additional hostnames in auto generated certs, check if keystores/truststores exists before regen

roles/confluent.control_center/defaults/main.yml, roles/confluent.control_center/templates/override.conf.j2, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/templates/override.conf.j2, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_connect/templates/override.conf.j2, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.kafka_rest/templates/override.conf.j2, roles/confluent.ksql/defaults/main.yml, roles/confluent.ksql/templates/override.conf.j2, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.schema_registry/templates/override.conf.j2, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/templates/override.conf.j2
Out of the box these components have the below open file limits set in their unit files
confluent-server/kafka: 1000000
kafka-rest: 100000
c3: 100000
This PR removes code that sets limitnofile values in the overwrite file for the above components. 
It also sets the limitnofile value to 100000 for these services (the remaining components): schema registry, ksql, connect, zookeeper
Ran install, confirmed the limitnofile is not in override.conf files. also confirmed the other environment variables from override.conf made it into the java process
=> Improved limitnofile logic

roles/confluent.control_center/defaults/main.yml, roles/confluent.control_center/tasks/main.yml
Fixes/Improves support for custom defined RocksDB paths. This ensures the path is created with the correct user/group and permissions and sets the appropriate configs within Systemd Overrides.conf.
Custom paths are a common occurrence for secure environments that mount `/tmp` with `noexec`. RocksDB requires execute permissions to run.
Tested in Lab Env
=> Control Center RocksDB Customer Path support

hosts_example.yml, roles/confluent.ssl/tasks/custom_certs.yml
Custom keys previously did not have password parameter, which is a security bug
Updated my cert generation script to put password on key, and then tested custom certs playbook w key has input parameter
=> Custom certs option did not take key pass as parameter

roles/confluent.ksql/tasks/main.yml
This PR removes an extraneous directory ownership task from KSQL.  We already set ownership and permissions in another task.
https://github.com/confluentinc/cp-ansible/issues/244
I have tested this change using the following molecule scenarios and validating that the permissions and ownership of the dir are set correctly inside the container:
1. rbac-mtls-provided-ubuntu
2. mtls-customcerts-rhel
=> Removed extraneous directory ownership task.

roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_connect/molecule/connect-hub/molecule.yml, roles/confluent.kafka_connect/molecule/connect-hub/verify.yml, roles/confluent.kafka_connect/tasks/confluent_hub.yml, roles/confluent.kafka_connect/tasks/connectors.yml
After installing connecthub connectors, the jars are all owned by root. This PR switches the ownership to the connect linux user
It leaves the permissions on the jars as read because thats all java needs.
Also removed a variable that only was used once in place of logic
Added unit test
=> Fix Connecthub plugin permissions

filter_plugins/filters.py, roles/confluent.control_center/defaults/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.ksql/defaults/main.yml, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.zookeeper/defaults/main.yml
Equal to filter is no supported in earlier versions of ansible, rolling back small filter change
All molecule tests must pass
=> equal to filter needs rolling back

Jenkinsfile, hosts_example.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/templates/zookeeper.properties.j2
This change makes the current zk node's hostname configurable
This means zk is listening on all interfaces, there were /etc/hosts issues on some debian vms, they should set to 0.0.0.0
Also updating the jenkinsfile to run molecule test
Tested with a 55 molecule scenario, everything came up
=> Making current zookeeper nodes hostname configurable & basic jenkins test

hosts_example.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/templates/kafka_server_jaas.conf.j2, roles/confluent.kafka_broker/templates/server.properties.j2, roles/confluent.test/molecule/zookeeper-kerberos/.gitignore, roles/confluent.test/molecule/zookeeper-kerberos/molecule.yml, roles/confluent.test/molecule/zookeeper-kerberos/verify.yml, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml, roles/confluent.zookeeper/templates/zookeeper.properties.j2
Now you can configure sasl gssapi on zookeeper independent of the kafka listeners
Should pave the way for sasl digest md5
Created a new molecule scenario, that does zookeeper sasl protocol = kerberos and kafka just has scram, this validate the user creation not impacted
=> Improvements on Zk kerberos

hosts_example.yml
Known bug around zk restarts when current hostname set to 0.0.0.0
https://github.com/apache/zookeeper/pull/1254
This pr removes that documentation
Default of zookeeper_current_hostname is inventory_hostname so out of the box cp-ansible installs zk fine.
=> Removed docs that say 0.0.0.0 for zk hostname works

roles/confluent.control_center/templates/kafka_client.j2, roles/confluent.kafka_connect/templates/kafka_client.j2, roles/confluent.kafka_rest/templates/kafka_client.j2, roles/confluent.ksql/templates/kafka_client.j2, roles/confluent.schema_registry/templates/kafka_client.j2
When removing the symlink to the kafka_client.j2 template, some files were mistakenly left in
These are dead files already so no new tests need to be created, but the old ones must pass
=> Symlinked file removal completion

hosts_example.yml, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.variables_handlers/vars/main.yml
Defaulted MTLS on the RBAC Rest listener to false, as CLI does not support MTLS currently.
Ran molecule scenario rbac-mtls-rhel and confirmed that all rbac bindings were created successfully.
molecule --debug converge -s rbac-mtls-rhel|tee test1.txt
=> RBAC MDS Rest URL default configuration

roles/confluent.kafka_broker/templates/server.properties.j2
When installing with ZK TL and fips mode the key/trust stores should be pkcs12 with additional properties configured to reflect that. Not sure if this is a bug as additional broker properties fix that too, but this adds automated install just like it is done for other components in fips mode.
Installed with mTLS and fips mode, everything looks ok
ZK in mTLS mode
zookeeper_ssl_enabled: true …
=> fips related properties for ZK TLS setup

roles/confluent.kafka_broker/templates/server.properties.j2
As per internal discussions with the security team, the following property is deprecated and no longer used by the Confluent RBAC implementation:
confluent.authorizer.group.provider=CONFLUENT
This has been tested using the following molecule scenarios:
rbac-kerberos-debian
rbac-mtls-rhel
=> Removed deprecated property related to RBAC configuration.

roles/confluent.control_center/defaults/main.yml
log4j java arg was getting written twice, this fixes that
All existing molecule scenarios should pass, I confirmed manually with `systemctl status confluent-control-center -l` that the process does not have duplicating log4j java arg now
=> fix duplicating log4j java arg

hosts_example.yml, roles/confluent.ssl/tasks/create_keystore_and_truststore.yml, roles/confluent.ssl/tasks/provided_keystore_and_truststore.yml
Fixes bug where some keystores in pkcs12 format could not be converted a new pkcs12 file on fips enabled hosts... Now there is a try catch where it first attempts cert/key exports on the keystore assuming its in pkcs12 format, and then falls back to doing the jks -p12 conversion
Also, docs bug fix
Tested with both a jks and pkcs12 keystore file, try catch worked as expected.
=> TLS - provided keystore format bugfix

filter_plugins/filters.py, roles/confluent.control_center/defaults/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.ksql/defaults/main.yml, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.variables_handlers/vars/main.yml, roles/confluent.zookeeper/defaults/main.yml
In rhel8, to resolve the "dh too small" error, one solution was to add the cipher suites ssl properties. Instead you can add a java argument that directly handles dh keys by adding this: `-Djdk.tls.ephemeralDHKeySize=2048`
https://stackoverflow.com/questions/24502672/how-to-expand-dh-key-size-to-2048-in-java-8
Ran on the rhel8 molecule scenario, but all scenarios must still pass
=> Removes cipher suites in place of java args

roles/confluent.control_center/tasks/health_check.yml, roles/confluent.kafka_connect/tasks/health_check.yml, roles/confluent.kafka_rest/tasks/health_check.yml, roles/confluent.ksql/tasks/health_check.yml, roles/confluent.schema_registry/tasks/health_check.yml
Missing change in 6.0 branch for healthcheck to use the hostname instead of localhost.
Change is a continuation of: https://github.com/confluentinc/cp-ansible/pull/309
All molecule scenarios must pass
=> updated healthcheck in 6.0 branch

Jenkinsfile, roles/confluent.test/molecule/plaintext-rhel/molecule.yml
Appends the CHANGE_ID and BUILD_NUMBER env var onto to the docker network and container names
On the jenkins server, these resolve to the PR number and the jenkins build number. If the env vars are not set, then the empty string is used
Added jenkinsfile and updated the molecule scenario it tests, which must pass
=> Enable multiple jenkins jobs to run - 53x branches

roles/confluent.common/tasks/main.yml
Many users seem to mess up ansible configs, so this assertion will error out with a nice message if hash merging is not enabled.
Tested with hash merge on/off
=> Hash Merge validator

roles/confluent.kafka_broker/tasks/main.yml, tasks/create_ordered_kafka_groups.yml, tasks/set_kafka_broker_jolokia_ssl_enabled.yml, tasks/upgrade_component.yml, tasks/wait_for_urp.yml, upgrade_control_center.yml, upgrade_kafka_broker.yml, upgrade_kafka_connect.yml, upgrade_kafka_rest.yml, upgrade_schema_registry.yml, upgrade_zookeeper.yml
Enables running the upgrade playbooks with `--check` which will run the playbook without doing any changes to the hosts, but report on the changes that would have occurred.
The hosts ordering tasks, which normally would be skipped were forced to run in check mode, and other were skipped or had their errors ignored because they could not succeed in check mode.
Ran all the upgrades with `--check`
=> Upgrade playbooks to allow for check mode runs

hosts_example.yml, roles/confluent.variables_handlers/defaults/main.yml
We've updated the custom properties dictionary variable name in the master branch, but should still honor the old variable
also kafka_broker_configure_additional_brokers was terribly named, so giving it a better name, but still honoring the original
Tested both ways of passing custom props
=> 60 making sure deprecated variables still work

roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.variables_handlers/vars/main.yml
Allows current and future version of cp-ansible to be used to install older pre 5.5.0 versions without overrides to the packaging
Used in building out personal test KSQL on 5.4.2 and used with customer for Ansible upgrade.
=> Ksql backwards compatibility support

roles/confluent.control_center/defaults/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.ksql/defaults/main.yml, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.zookeeper/defaults/main.yml
ZK service file has limitnofile in 60 release, so there is no need to overwrite it
Also improve the comment and code elsewhere around this var
Jenkins job will test this, its a trivial change
=> zk does not need a limit no file in 60, code cleanup around this variable

roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/main.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.control_center/tasks/health_check.yml, roles/confluent.kafka_broker/tasks/wait_for_urp.yml, roles/confluent.kafka_connect/tasks/health_check.yml, roles/confluent.kafka_rest/tasks/health_check.yml, roles/confluent.ksql/tasks/health_check.yml, roles/confluent.schema_registry/tasks/health_check.yml, roles/confluent.zookeeper/tasks/health_check.yml
Some ppl have noticed some hosts failing to install java, giving it 10 retries
Also giving other jar/cli installs retries
Lowering the number of retries on the component health checks
Hard to replicate the bug, but retries are only helpful so this should be good.
=> Adding retries to the java install and other installs

roles/confluent.kafka_broker/defaults/main.yml
Updated the group.initial.rebalance.delay.ms to correct default of 3000 as per documentation.
Tested via molecule playbook deployment.  Specifically ran plaintext-rhel.
Single cluster, on rhel with plaintext.
=> Updated group.initial.rebalance.delay.ms to correct default of 3000.

roles/confluent.common/tasks/ubuntu.yml, roles/confluent.test/molecule/Dockerfile-ubuntu.j2, roles/confluent.test/molecule/rbac-scram-custom-rhel/molecule.yml
Removes unnecessary steps in the ubuntu dockerfile
Adds ubuntu man pages task which enables our install to succeed on bare ubuntu image
Removes docker image build on molecule scenario Jenkins orchestrates
Ran the mtls-ubuntu scenario with/without dockerfile- succeeds
Other scenario gets tested with jenkins
=> Update ubuntu dockerfile, remove docker image build on jenkins test

VARIABLES.md, roles/confluent.variables/defaults/main.yml
Bugfix around if you are installing rbac without all the components it is discovered that some vars do not have defaults. This adds the dummy defaults to the ldap user vars and updates the docs
Tried rbac molecule scenario without ksql group
=> Rbac vars need documentation/ defaults

roles/confluent.kafka_broker/tasks/restart_kafka.yml, roles/confluent.zookeeper/tasks/restart_zookeeper.yml
Because keystores get fully replaced, serial restart of the brokers/zk leads to ssl errors. Adds conditional
Ran the mtls-ubuntu role twice, saw that it does parallel restart on kafka and zk
=> Parallel restart if the certs have been updated

Jenkinsfile
This PR adds the ability to specify override parameters for primarily three concepts:
* A different packages repo (ie: `confluent_common_repository_baseurl`)
* A different version, older or un-released (ie `confluent_package_version`)
* And because our Debian nightly packages use an odd version format (example: `5.4.3~SNAPSHOT-1`), a switch to tell the job "what kind of" release to install (ie: `confluent_package_redhat_suffix` & `confluent_package_debian_suffix`)
We use molecule's `--base-config` to set these values to override the values in the Anisble Playbooks - I've used this config with `--debug` and have verified that the intended versions are installed.
N/A
The last two Jenkins builds used
* No parameters to simulate testing that would be done locally (PASS)
* …
=> Add Override Parameters

.gitignore, .yamllint
The Jenkins job that writes the YAML file doesn't write a YAML document-start `---`, which trips up the `yamllint`-er:
```
14:23:21  yamllint -c ../../.yamllint ../..[0m
14:23:24  ../../roles/confluent.test/base-config.yml
14:23:24    1:1       error    missing document start "---"  (document-start)
14:23:24  
14:23:24  [31mERROR: Lint failed: Command 'set -e
```
=> MINOR: Add .yamllint to ignore document-start in base-config.yml

Jenkinsfile
This build failure in Jenkins reminds me that we should override `confluent_repo_version` if we're overriding the to-be-installed version.
=> MINOR: When Confluent Version is defined also override confluent_repo_version

Jenkinsfile
This change disables job reporting to Slack and Confluent's Test Break system when parameters are specified, as they may be incorrect that cause build failures.
=> MINOR: Disable Build Reporting when using parameters

Jenkinsfile
It was reported in a tools thread that there were running `molecule_local/geerlingguy/docker-centos7-ansible` Containers that were over 24 hours old. These were likely aborted jobs that never had a chance to clean up. This change adds a post-step that will execute `molecule destroy` at the end of the job irrespective of the outcome.
=> Add Cleanup post task to destroy/cleanup resources

roles/confluent.kafka_connect/tasks/confluent_hub.yml, roles/confluent.kafka_connect/tasks/connectors.yml
Setting 0755 permission explicitly on all unarchived connector plugins.
Fixes #366 
=> Set correct rights on unpacked files and unify umask entries

hosts_example.yml
Zookeeper can have acls on kafka data. This is controlled with the zookeeper.set.acl kafka property. This is a docs update to mention that this property gets set for kafka->zk auth modes: sasl_digest and sasl_md5sum.... It does not get set for mTLS, because that can be error prone. Customers will need to set that manually with kafka custom properties
Just a docs update
=> Minor docs mention to zk acls

roles/confluent.kafka_broker/tasks/rbac.yml, roles/confluent.kafka_broker/templates/server.properties.j2, roles/confluent.test/molecule/rbac-mtls-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mtls-rhel/verify.yml
super.users property can now be customized. this will append to custom super.users list with what cp-ansible thinks are the necessary super.users for rbac to function. it also removes duplicates from the list
Added custom super.users list to one molecule scenario with a test case
=> 55 customize super.users kafka property with rbac

roles/confluent.kafka_broker/tasks/set_principal.yml, roles/confluent.test/molecule/certs-create.sh, roles/confluent.test/molecule/rbac-mtls-provided-ubuntu/verify.yml
Added better logic for stripping spaces in mtls super user
Updates the test certs dname, and adds a test
rbac-mtls-provided-ubuntu scenario succeeds, and validates the bugfix
=> Bugfix- only strips spaces after commas in dname

Jenkinsfile
The typical pattern at Confluent is to have the `.x` branches in the project repositories to be targeting the "next" versioned release. This means the releases for that "next" Confluent Platform are not yet on https://packages.confluent.io. So say if we were to bump roles/confluent.variables_handlers/defaults/main.yml to the "next" version in 5.4.x of `5.4.3`, you would get this type of error:
```
failed: [zookeeper1] (item=confluent-common) => {"ansible_loop_var": "item", "changed": false, "item": "confluent-common", "msg": "No package matching 'confluent-common-5.4.3-1' found available, installed or updated", "rc": 126, "results": ["No package matching 'confluent-common-5.4.3-1' found available, installed or updated"]}
```
So this change aims to query the packaging job (the one that …
=> Use nightly builds in .x branch

roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_connect/tasks/confluent_hub.yml, roles/confluent.test/molecule/mtls-debian/molecule.yml
Changes the splits the unarchive task into get_url (with timeout) or copy, and then unarchive
Bug this resolves is around lack of timeout on the unarchive task. The get_url task now has a configurable timeout, defaulting to 90s
Updated the mtls-debian scenario to run the connect hub tasks, and it works
=> Connect Hub Timeout Bugfix

Jenkinsfile
In the 6.0.x branch, because `confluent_repo_version` is still set to 5.5, we get incorrect HTTP paths. Eg (in a 6.0.x Jenkins build):
```
17:21:36  [31mfatal: [control-center154]: FAILED! => {"attempts": 10, "changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from Confluent: [Errno 256] No more mirrors to try.\n${BASEURL}/rpm/5.5/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found"}[0m
```
When the 6.0.x Job queries the packaging job for the location if the nightly build. Luckily we can deduce what `confluent_repo_version` *should* be from the branch name, hence this override.
Did a replay with this change-of-sorts:
https://jenkins.confluent.io/job/confluentinc/job/cp-ansible/job/6.0.x/55/replay/diff
The job may have failed, but for a …
=> Override confluent repo version in dev

VARIABLES.md, all.yml, roles/confluent.test/molecule/mtls-java11-debian/molecule.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml, tasks/certificate_authority.yml
- Should be able to configure kafka_rest (or any other component group) alone. Useful for connecting component to ccloud kafka instance. 
- Adds flag for monitoring interceptors, now disableable
- Removes unnecessary c3 rbac props 
Reviewed logs of mtls scenario, made sure the certificate authority tasks did in fact only run once.
Everything else gets validated on any scenario run
=> Inventory supports any component group, does not require all

roles/confluent.test.ldap/tasks/tls_custom_certs.yml
Fixes molecule ldaps start up errors
Jenkins run will test it
=> Missing file permissions on ldaps cert files

roles/confluent.common/tasks/main.yml, tasks/certificate_authority.yml
Replaces synchronize module with fetch. 
Also fixes issues with libsss_sudo rsync errors
Fixes: https://github.com/confluentinc/cp-ansible/issues/390
mtls-debian scenario
=> Replacing Synchronize task w Fetch

roles/confluent.ksql/defaults/main.yml, roles/confluent.ksql/tasks/main.yml
Sets up directory for RocksDB on ksqldb hosts. By default uses the /tmp directory
Whatever directory set will get 777 so that any users run ksqldb queries what write on the directory
Fixes # (https://github.com/confluentinc/cp-ansible/issues/397)
Run any molecule scenario can see the directory created
=> RocksDB env var for ksqlDB

Jenkinsfile
This is to fix a build issue: https://jenkins.confluent.io/job/confluentinc/job/cp-ansible/job/6.0.x/140/replay/diff
TL;DR: I was checking the object used to put a parameter into the Job, not the parameter's *value*.
https://jenkins.confluent.io/job/confluentinc/job/cp-ansible/job/6.0.x/140/replay/diff
=> Use actual parameter value, not param choice

roles/confluent.kafka_broker/tasks/restart_kafka.yml, roles/confluent.zookeeper/tasks/restart_zookeeper.yml
, even in check mode, to avoid uninitialized variable.
We are trying to run the playbook (all.yml) in check mode on feature branches. This does not currently work, resulting in the following error message:
```
RUNNING HANDLER [confluent.zookeeper : Restart Zookeeper Serially] *************
fatal: [myhost.mydomain]: FAILED! => 
msg: |-
The conditional check 'substate.stdout == 'SubState=running'' failed. The error was: error while evaluating conditional (substate.stdout == 'SubState=running'): 'dict object' has no attribute 'stdout'
The error appears to be in '/builds/kafka/provisioner/cp-ansible/roles/confluent.zookeeper/tasks/restart_zookeeper.yml': line 10, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: Restart …
```
=> Force 'check if service running' tasks to run in normal mode

roles/confluent.test/molecule/custom-user-plaintext-rhel/verify.yml
Verify for custom-user-plaintext-rhel scenario was calling health checks for the broker restart from the wrong location, due to a change in the 6.0.0 release.
Tested by running custom-user-plaintext-rhel scenario with verify.
=> Updated verify to call health checks for broker from correct location.

roles/confluent.ssl/tasks/provided_keystore_and_truststore.yml
Minor changes which adds quotes around the export alias of the CA cert when it is exported from a provided trust store, to factor in spacing in the alias.
Validated with the following scenario:
rbac-mtls-provided-ubuntu
=> Added quotes around alias variable to allow for spaces in cert alias.

tasks/upgrade_component.yml, upgrade_kafka_broker.yml, upgrade_ksql.yml, upgrade_zookeeper.yml
Added additional tasks to upgrade plays to remove confluent-kafka-2.12 to prevent packaging conflict.
https://github.com/confluentinc/cp-ansible/issues/421
Manually tested upgrade from both 5.4.0 and 5.5.0 to 6.0.0 with Confluent-kafka installed.
1. Installed all components on AWS on unique hosts with both 5.4.0-post branch and 5.5.0-post branch
2. Upgraded from 5.4.0-post to 6.0.0-post with bug fix branch of …
=> Added additional tasks to remove cp-kafka 

roles/confluent.test/molecule/plain-rhel/molecule.yml, roles/confluent.test/molecule/plain-rhel/verify.yml, roles/confluent.test/tasks/check_property.yml, roles/confluent.zookeeper/tasks/main.yml
Adds tasks to set up the dataLogDir directory on zk hosts. 
Feature off by default. Must configure
```
zookeeper_custom_properties:
dataLogDir: /path
```
To use
Fixes # (https://github.com/confluentinc/cp-ansible/issues/214)
- Added custom property to plain-rhel scenario with verify tasks
- Tested default case manually with plaintext-rhel, and viewed the tasks were skipped
=> Zookeeper dataLogDir Configuration

VARIABLES.md, roles/confluent.ssl/defaults/main.yml, roles/confluent.ssl/tasks/self_signed_certs.yml, roles/confluent.test/molecule/certs-create.sh
Updated of the -genkey to -genkeypair as -genkey is deprecated.
https://github.com/confluentinc/cp-ansible/issues/426
Tested with the following scenarios:
rbac-mds-mtls-custom-rhel
rbac-mtls-rhel
=> Updated the -genkey switch to -genkeypair.

roles/confluent.kafka_connect/files/kafka_connect.yml, roles/confluent.kafka_rest/files/kafka_rest.yml, roles/confluent.ksql/files/ksql.yml, roles/confluent.schema_registry/files/schema_registry.yml, roles/confluent.zookeeper/files/zookeeper.yml
This fix updates JMX exporter configurations in cp-ansible to match configurations available in our https://github.com/confluentinc/jmx-monitoring-stacks repo. I am the original author for 6.x configurations in jmx-monitoring-stacks and would continue to sync the 2 repo's as necessary.
Also, this ensures parity with our open source dashboards in the stack repo to be compatible with cp-ansible. 
- [N] Bug fix (non-breaking change which fixes an issue)
- [Y] New feature (non-breaking change which adds functionality)
- [Maybe] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [N] This change requires a documentation update
Heavily tested when I released the 6.0.0-post branch with jmx-monitoring-stacks.  …
=> Update JMX Exporter configurations to match JMX-monitoring-stacks

roles/confluent.kafka_broker/templates/listener.j2
Fixes the issue for when Kerberos based listener is setup with a combination of other types of listeners like OAuthBearer.
The property `sasl.kerberos.service.name` needs to exist at the listener level and not just at the global level.
- [Y] Bug fix (non-breaking change which fixes an issue)
Deployment.
3 ZK, 3 Broker RBAC + Kerberos setup. Conencting to kafka broker via kafka client to Kerberos listener failed. 
Adding this property resolved the issue
- [Y] My code follows the style guidelines of this project
- [Y] I have performed a self-review of my own code
- [Y] My changes generate no new warnings
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] Any dependent changes have been merged and published in …
=> Fix for Kerberos listener sasl service name property

roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.test/molecule/kerberos-rhel/molecule.yml
Adds `-Dzookeeper.sasl.client.username` java arg to kafka process whenever the zk kerberos primary != 'zookeeper'
Makes sure to also have defaults which will be important in the 600 branch
Updated the kerberos-rhel scenario with new zk primary. Saw the failure, and upon adding the java arg it works
=> Zookeeper kerberos primary java arg

roles/confluent.kafka_broker/tasks/rbac.yml, roles/confluent.ssl/tasks/create_keystore_and_truststore.yml, roles/confluent.ssl/tasks/main.yml, tasks/rbac_setup.yml
Makes sure no ssl files are world readable
This is run on a c3 host
```
[root@control-center1 /]# ls -lat /var/ssl/private
total 36
drwxr-xr-x 2 root              root      4096 Oct 13 19:04 .
-rw-r----- 1 cp-control-center confluent 4809 Oct 13 19:04 control_center.keystore.jks
-rw-r----- 1 cp-control-center confluent 1330 Oct 13 19:04 control_center.crt
-rw-r----- 1 cp-control-center confluent 1856 Oct 13 19:04 control_center.key
-rw-r----- 1 cp-control-center confluent 1218 Oct 13 19:04 control_center.truststore.jks
-rw-r----- 1 cp-control-center confluent 1310 Oct 13 19:04 ca.crt
-rw-r----- 1 cp-control-center confluent  451 Oct 13 19:00 public.pem
```
Ran an rbac scenario with some components colocated to make sure the shared ownership onrbac pem file is ok. Did a …
=> Improve the file permissions on ssl files

Jenkinsfile
During jenkins run, ZK hostname verification failing in multi zookeeper deployment:
```
zookeeper3210.confluent210 zookeeper-server-start[1341]: Caused by: javax.net.ssl.SSLPeerUnverifiedException: Certificate for <zookeeper1210.confluent210> doesn't match any of the subject alternative names: [zookeeper1210, zookeeper1210.confluent]
```
This is not true when running locally, so as a quick fix, this adds zookeeper java args to the jenkinsfile to disable
Jenkins job must complete successfully
=> Jenkins bugfix for zk hostname verification

upgrade_kafka_broker.yml
confluent_server_enabled misspelled
Running the kafka upgrade on debian host and saw this
=> fixed typo in variable name in upgrade playbook

roles/confluent.kafka_broker/handlers/main.yml, upgrade_kafka_broker.yml, upgrade_kafka_broker_log_format.yml
I am trying to use the confluent.kafka_broker role as a role dependency, and that does not work - because it results in an incorrect path. This PR corrects this, and I have verified that it solves my use case.
I think it seems odd to refer to a role-internal file using an "external" path, starting with `roles/<role-name>` - as it really limits what will actually work. The bug seems to have been introduced in this commit, https://github.com/confluentinc/cp-ansible/commit/6d50a7f09d4843bcc1e85821613a560ffa5d95f3#diff-0fec400f04957013fee20d1dfd6d96128a0e5275684c5b0d6713d546b0a67c42, and I assume that the change was done to fix another issue. Let us 🤞 that this issue won't return...
If this PR is merged, the path will be equivalent to a similar reference in …
=> Fix internal kafka_broker role 'restart kafka' handler relative path

all.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/templates/kafka_jolokia.properties.j2, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect/templates/kafka_connect_jolokia.properties.j2, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.kafka_rest/templates/kafka_rest_jolokia.properties.j2, roles/confluent.ksql/defaults/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.ksql/templates/ksql_jolokia.properties.j2, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.schema_registry/templates/schema_registry_jolokia.properties.j2, roles/confluent.test/molecule/mtls-debian/molecule.yml, roles/confluent.test/molecule/mtls-debian/verify.yml, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml, roles/confluent.zookeeper/templates/zookeeper_jolokia.properties.j2, tasks/set_kafka_broker_jolokia_ssl_enabled.yml, tasks/wait_for_urp.yml
- Moves jolokia config properties into a file, which in turn removes passwords from the java process
- Enforces tlsv1.2 on jolokia endpoint
- Adds basic auth capability to jolokia configuration
- Adds missing conditional around creation of log4j conf
- Updates fact finding tasks for upgrade kafka, which figures out if jolokia has tls encryption on or not, to check both the override.conf and the jolokia config file
Updated the mtls-debian scenario to configure component jolokia w basic auth && added verify tasks
Manually tested the upgrade task change
=> Security Patch- Jolokia Agent Authentication

roles/confluent.test/molecule/mtls-debian/molecule.yml
fips should only be tested on rhel, will not work on debian
it is enabled/ tested in the scenario mtls-java11-rhel
Reran both scenarios
=> Minor change to mtls test/ fips

roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Zk will only have one exposed port, 2181 for no tls encryption and 2182 for tls encryption
All clients can now use either
Ran zookeeper-mtls and plain-rhel scenario
Todo test archive installer
=> Zookeeper ssl improvement

upgrade_kafka_connect.yml, upgrade_kafka_rest.yml, upgrade_schema_registry.yml
For SR, connect, and RP in 540 their mtls vars dont actually turn on mtls in their properties. And so in 5.5.0 when the upgrade happens it attempts to check an mtls endpoint.
There is no ksql 5.4.x -> 5.5.x playbook, but we may still want this piece of logic in the 5.5.1-post branch to be safe.
There is no mtls on c3
Ran the mtls-debian scenario in 5.4.0-post and then upgraded using this branch
=> Adds logic to set the mtls var during component upgrades

upgrade_ksql.yml
Properly sets the `ksql_ssl_mutual_auth_enabled` variable to ensure the correct health check runs
Ran playbook, debugged var
=> ksqldb upgrade mtls check

tasks/upgrade_component.yml, upgrade_ksql.yml, upgrade_zookeeper.yml
Both the upgrade_zookeeper and upgrade_ksql playbooks contained the incorrect variable name for checking if confluent-server was enabled or not.
Ran rbac-scram-provided-debian-upgrade-550-current.sh
=> Corrected confluent-server_enabled variable to correct name

roles/confluent.test/molecule/scram-rhel/molecule.yml, roles/confluent.test/upgrade_testing/cp-kafka-plain-rhel-upgrade-550-current.sh, tasks/set_confluent_server_enabled.yml, upgrade_kafka_broker.yml, upgrade_zookeeper.yml
Adds logic to the upgrade_kafka_broker.yml playbook to handle colocated zk and kafka, which when you upgrade in that configuration the kafka package will be upgraded during the zk upgrade and in the case of confluent-kafka-2.12, the package even switches names.
Fixes # (https://github.com/confluentinc/cp-ansible/issues/423)
Manually tested plaintext 3 node zk colocated w 3 node kafka upgrade
Both confluent_server_enabled: true/false
Ran the install, zk upgrade and kafka upgrade
=> 60 colocated upgrade bugfix

Jenkinsfile
As the title says, nanoversioning has been rolled out to the packaging job, so artifacts will no longer have the SNAPSHOT suffix in the release, its just 0 now.
A PR build here.
=> Remove SNAPSHOT suffix now that CP6.1 is nanoversioned

filter_plugins/filters.py, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.test/molecule/multi-ksql-connect-rhel/molecule.yml, roles/confluent.test/molecule/multi-ksql-connect-rhel/verify.yml, roles/confluent.test/molecule/plain-rhel/molecule.yml, roles/confluent.test/molecule/plain-rhel/verify.yml, roles/confluent.test/tasks/check_property.yml
If using the multi connect and connectors feature then you will only get connectors configured on one cluster. This resolves that as well as makes sure connect clusters can be configured separately and configured correctly in c3
updated the multi-ksql-connect-rhel and plain-rhel scenarios
=> Connect clusters can be configured with unique connectors

roles/confluent.control_center/defaults/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.ksql/defaults/main.yml, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.test/molecule/archive-plain-rhel/verify.yml, roles/confluent.test/tasks/check_log4j.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.zookeeper/defaults/main.yml
When there are multiple log4j args in the java processes and you use the archive installer, then our components fail to start up because the component process can't write the log files as defined in the out of the box log4j conf. They do not have permissions to write the logs. By using the correct env vars, we get rid of the extra args
Also fixes an archive installer bug w the jolokia config file path
Added verification task to archive installer scenario
=> log4j bugs with archive installer

roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/tasks/rbac_rolebindings.yml, roles/confluent.test/molecule/rbac-scram-custom-rhel/molecule.yml, roles/confluent.test/molecule/rbac-scram-custom-rhel/verify.yml, roles/confluent.variables_handlers/defaults/main.yml
Users in the `rbac_component_additional_system_admins` list do not get added as a kafka cluster sysadmin
added tests to rbac-scram-custom-rhel scenario
=> Configure additional kafka sys admins

VARIABLES.md, roles/confluent.kafka_connect/tasks/rbac.yml, roles/confluent.kafka_rest/tasks/rbac.yml, roles/confluent.ksql/tasks/rbac.yml, roles/confluent.test/molecule/rbac-scram-provided-debian/molecule.yml, roles/confluent.test/molecule/rbac-scram-provided-debian/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Now metrics reporter/ monitoring interceptors can be configured even if c3 not in inventory file. Now can make use of these vars
```
kafka_broker_metrics_reporter_enabled: true
monitoring_interceptors_enabled: true
```
Removed c3 container from rbac-scram-provided-debian and added vars to test the functionality
=> Metrics reporter logic improvement

roles/confluent.test/molecule/plain-rhel/molecule.yml, roles/confluent.test/molecule/plain-rhel/verify.yml, roles/confluent.variables/vars/main.yml
In a non rbac deployment, we should have connect worker configured as a kafka client with these properties:  `[producer|consumer].sasl.jaas.config` 
Connectors added to the cluster will inherit these properties, but can still override those them using this: https://docs.confluent.io/current/connect/references/allconfigs.html#override-the-worker-configuration
In an rbac deployment, we will force connectors to configure their `[producer|consumer].sasl.jaas.config` properties to make sure admins are properly thinking about access and role bindings.
Also fixes broken test in scenario. The test was around the dataLogDir custom property. it was somehow left out of the molecule.yml, but tested for in the verify.yml
Added verify task to plain-rhel scenario
=> Omitting connect producer/consumer jaas properties only when RBAC enabled

hosts_example.yml, roles/confluent.test/molecule/confluent-kafka-kerberos-customcerts-rhel/molecule.yml, roles/confluent.test/molecule/kerberos-rhel/molecule.yml, roles/confluent.test/molecule/kerberos-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml, sample_inventories/rbac_centralized_mds_kerberos_custom_certs_example.yml, sample_inventories/rbac_kerberos_custom_certs_example.yml
The `kerberos_kafka_broker_primary` variable is not necessary since it can be pulled out of the `kafka_broker_kerberos_principal` variable
Updated kerberos-rhel scenario to use non default primary value, added verify tasks
=> kafka kerberos primary variable deprecation

roles/confluent.common/tasks/main.yml, roles/confluent.test/molecule/mtls-debian/molecule.yml, roles/confluent.test/molecule/mtls-debian/verify.yml
Noticing bugs trying to use curl to get the confluent cli install script, replacing curl with get_url module
Added test to mtls-debian scenario which was not successfully installing the cli without the change
=> 55x cli install without curl

roles/confluent.ksql/tasks/rbac.yml
This PR corrects the following:
grant ResourceOwner on _confluent-ksql-<ksql-id>  topic (currently none)
grant ResourceOwner on _confluent-ksql-<ksql-id> subject (currently DeveloperRead)
Successfully validated against rbac-scram-custom-rhel scenario.
=> Added additional permission for KSQL RBAC access for interactive queries

roles/confluent.kafka_connect/tasks/rbac.yml, roles/confluent.variables/vars/main.yml
Proprietary Connectors for Confluent Platform require access to the licensing Topic in order to Operate.  This is accessed by the Connect user to validate the Connector is allowed to run.  
While we do document this on individual proprietary connectors, it's actually a setup step at the Connect Framework level, and not the Connector level and thus should be setup by default by CP-Ansible.
I have validated by running with the rbac-kerberos-debian scenario and validated with the Kafka Connect team.
=> Updated RBAC permissions for Connect to add Connect user as ResourceOwner

tasks/create_ordered_kafka_groups.yml
Added basic auth support to ordered restart logic in case user wishes to upgrade from one version of 5.5.x to another version of 5.5.x.
https://github.com/confluentinc/cp-ansible/issues/498
Ran RBAC-MTLS-RHEL scenario and set to 5.5.0, manually upgraded to 5.5.3.
=> Updated ordered restart to support basic auth on jolokia.

roles/confluent.common/tasks/main.yml
Directories to place JARs are being created with hard-coded paths. Instead jar_paths can be used to create a proper directory if variables change.
=> Create Jolokia and Prom JMX exporter directories based on jar path

VARIABLES.md, hosts_example.yml, roles/confluent.variables/defaults/main.yml
As regeneration of keystore/truststore triggers restarts, this can be explicitly stated on the docs and example.
=> [MINOR] Docs: Add comment about regenerate keystore/truststore

roles/confluent.variables/vars/main.yml
Monitoring interceptors are not configured for the license topic in Rest Proxy. This WARN log repeats indefinitely
```
WARN [Producer clientId=confluent.monitoring.interceptor.confluent-license-consumer] Bootstrap broker ip-172-30-30-215.eu-west-1.compute.internal:9092 (id: -3 rack: null) disconnected (org.apache.kafka.clients.NetworkClient)
```
According to [the docs](https://docs.confluent.io/platform/current/kafka-rest/production-deployment/rest-proxy/config.html)
> Use the client. prefix to override the default settings of admins, consumers and producers in Confluent REST Proxy
Ran rbac-mtls-rhel molecule scenario and validated the logs
=> Rest Proxy Monitoring Interceptors Bugfix

VARIABLES.md, roles/confluent.test/molecule/rbac-scram-custom-rhel/molecule.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
To deploy Confluent Replicator in a Connector cluster, monitoring extensions have to be added. Currently, this configuration is only modified when RBAC is enabled. 
This PR proposes a new variables to be concatenated when defined.
**Test Configuration**: molecule/rbac-scram-custom-rhel
=> Custom extension classes on Kafka Connect role

roles/confluent.test/molecule/rbac-mtls-rhel/verify.yml
Added verify task to in rbac-mtls-rhel
It appears tlsv1.2 is turned on by default for ksql in 6.0.1
rbac-mtls-rhel suceeds
=> Add test for ksql tls v1.2

VARIABLES.md, roles/confluent.control_center/defaults/main.yml, roles/confluent.control_center/templates/override.conf.j2, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/templates/override.conf.j2, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_connect/templates/override.conf.j2, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.kafka_rest/templates/override.conf.j2, roles/confluent.ksql/defaults/main.yml, roles/confluent.ksql/templates/override.conf.j2, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.schema_registry/templates/override.conf.j2, roles/confluent.test/molecule/plain-rhel/molecule.yml, roles/confluent.test/molecule/plain-rhel/verify.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/templates/override.conf.j2
Introduces new variables for each component to customize systemd unit section. Feature not used on most installs.
Improved docs around other override.conf dictionaries
added test to plain-rhel
=> Allow for customization of the Unit section of systemd service files

roles/confluent.kafka_broker/tasks/health_check.yml, roles/confluent.test/molecule/mtls-custombundle-rhel/molecule.yml, roles/confluent.test/molecule/mtls-custombundle-rhel/verify.yml, roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
- Kafka Health check uses full path for kafka-topics command to support both package and tar installation
- mtls-custom-bundle testing scenario now passing, verify tasks did not match the variables getting set
- mtls-custom-certs testing scenario now passing, there was a confluent-server test
archive-plain-rhel 
and rbac-scram-custom-rhel scenario should test both install modes
=> Path needs to accommodate for tar install

roles/confluent.kafka_broker/tasks/main.yml
When installing Confluent platform as archive and enable SCRAM, playbook fails creating scram users because kafka-configs is not in the path.
OS: RHEL7
Install method: Archive
Variables to set in hosts file to reproduce the issue:
```
confluent_archive_file_remote: false
confluent_archive_file_source: "/tmp/confluent-6.0.1.tar.gz" # local path on Ansible host where you downloaded the archive
sasl_protocol: scram
```
**Proposed fix**:
Prepend the `kafka-configs` command with the `binary_base_path` internal variable because it is [declared](https://github.com/confluentinc/cp-ansible/blob/daf14ea207be4fc09f43191b154a21713bfaccca/roles/confluent.variables/vars/main.yml#L1066) to use the Confluent archive path or `/usr` by default and it can be possibly overriden as per …
=> Archivepath

control_center.yml, kafka_broker.yml, kafka_connect.yml, kafka_connect_replicator.yml, kafka_rest.yml, ksql.yml, roles/confluent.control_center/defaults/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.ksql/defaults/main.yml, roles/confluent.ksql/tasks/rbac.yml, roles/confluent.ksql/templates/ksql-server_log4j.properties.j2, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.test/molecule/confluent-kafka-kerberos-customcerts-rhel/verify.yml, roles/confluent.test/molecule/plain-erp-tls-rhel/verify.yml, roles/confluent.variables/vars/main.yml, roles/confluent.zookeeper/defaults/main.yml, zookeeper.yml
- Tar install failing kafka start up with:
```
Feb 03 05:32:21 kafka-broker1.confluent systemd[1]: Started Apache Kafka - broker.
Feb 03 05:32:21 kafka-broker1.confluent kafka-server-start[5062]: mkdir: cannot create directory ‘/opt/confluent/confluent-6.1.0/bin/../logs’: Permission denied
```
By making sure `LOG_DIR` env var is always set, these logs get written to the correct location
- Package name updated from confluent-kafka-2.12 to confluent-kafka - This fix should be backported
- Admin api property changed `confluent.metadata.server.listeners` - > `confluent.http.server.listeners` - This may need to be backported
- On some SELinux enabled hosts where you remove the packages, rerunning the install will error out with
```
TASK [Check if Zookeeper Service Running] …
```
=> More 6.1.x Bugfixes

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/tasks/rbac.yml, roles/confluent.kafka_broker/tasks/set_principal.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
- Fixes bug where serial reconfiguration not working in an rbac deployment. Need to make sure the super users gathering happens across all brokers. When running serial that was not happening before this PR
- Adds missing `common` tag
Reran rbac-mtls-rhel multiple times, works with this branch
=> 61x Reconfigure RBAC Bugfix

roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
Corrects `plugin.path` property when `installation_method: archive`
Keeps /usr/share/java in there in case additional plugins are installed
Added test to archive-scram-rhel
=> Connect Plugin path for Tar Install

tasks/create_ordered_kafka_groups.yml
Missing spaces causing zookeeper shell connection without properties
Need to handle server.properties that has been generated with the secrets protection scripts
Ran the install with a secrets protection enabled kafka
=> Missing spaces in property check in upgrade conditional

roles/confluent.kafka_broker/tasks/rbac.yml, roles/confluent.kafka_broker/tasks/set_principal.yml
Using 6.1.0-post with an RBAC enabled cluster, deploying kafka brokers with the rolling strategy results in malformed super.users. As a result, broker restart fails.
Core reason is that task 'Normalize User Name' (roles/confluent.kafka_broker/tasks/set_principal.yml) performs an update on the variable 'kafka_broker_principal' but may be executed multiple times from the loop in rbac.yml and/or when executing for multiple broker hosts. 
To resolve the issue, this PR:
- Builds the correctly formed principal in each task, and removes the update step 'Normalize User Name'.
- Replaces the 2 loops in rbac.yml which call set_principal in different modes, with a single loop over all broker hosts + run_once.
Fixes # 569
- Tested against 1 ZK, 3 Broker setup
- Tested with PLAIN and mTLS interbroker …
=> 20210303 fix malformed super users #569

roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.test/molecule/plain-rhel/molecule.yml
User recently misconfigured this property:
```
kafka_broker:
datadir:
/var/lib/kafka/my-data
```
where datadir *should be a list*. This resulted in a catastrophic reconfiguration of the VM where all files changed ownership to the kafka_broker_user. This PR validates that catastrophe will not happen!
Now this is how it will error out:
```
TASK [confluent.kafka_broker : Assert log.dirs Property not Misconfigured] *****
fatal: [kafka-broker1]: FAILED! => {"assertion": "kafka_broker_final_properties['log.dirs'].split(',')[0] != \"/\"", "changed": false, "evaluated_to": false, "msg": "Make sure datadir key is set to list of directories, NOT a string or dictionary."}
```
Tested with the misconfiguration in the description, got the error message, and the playbook stopped, without …
=> log.dirs Assertion

roles/confluent.variables/defaults/main.yml
- Puts conditional logic into the sasl user dictionaries, this way if a specific group is not in inventory, the sasl user for that group will not get created unnecessarily
Tested with a few inventories, and debugged the variables
=> Sasl User Conditional logic

upgrade_kafka_broker.yml
I am expecting an attempt to "upgrade" from/to same version to be a noop - i.e. idempotent. This does not seem to be the case, and this PR is an attempt to fix this.
To reproduce (with reference to [Upgrade Confluent Platform with Ansible Playbooks](https://docs.confluent.io/ansible/current/ansible-upgrade.html)):
```shell
git checkout 6.0.2-post
ansible-playbook -i /path/to/hosts.yml upgrade_kafka_broker.yml -e kafka_broker_upgrade_start_version=6.0
```
Expected behavior:
- Playbook runs without errors, but no Kafka Broker hosts are upgraded.
Actualt behavior:
```log
TASK [Set Inter-Broker Protocol Version to Current Version] ********************
fatal: [<kafka_broker host>]: FAILED! => 
msg: |-
The task includes an option with an undefined variable. The error was: …
```
=> fix: Support for noop "upgrade" from/to same version

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml
The 6.1.x branch contains an incorrect task reference statement for the secrets_protection file.  It was trying to pull the file from the root of the project, instead of importing it from the common role.
This patch corrects the location.
Successfully validated with the rbac-plain-provided-debian molecule scenario, which implements secrets protection.
See rbac-plain-provided-debian role.
=> Corrected location of secrets_protection.yml for each component.

roles/confluent.common/tasks/update_log4j.yml
With `--check` option, ansible fail on "Add Max Size Property" of cp-ansible/roles/confluent.common/tasks/update_log4j.yml
Addind `check_mode: false` on previous task (which clearly have no side effect) solves this issue
run playbook with `--check`
=> avoid fail in check mode

roles/confluent.variables/vars/main.yml
`control.plane.listener.name` assignment fails (at least with ansible 2.7) when `kafka_broker_control_plane_listener_name` defaults to `controller` but there's no listeners with this name.
This change let the `default()` call use default value instead of failing
Bug fix (non-breaking change which fixes an issue)
Run playbook with inventory containing several listeners but no `controller` one
- ansible 2.7
- `kafka_broker_configure_control_plane_listener` = `false`
- inventory declares `kafka_broker_custom_listeners` with several listeners, but none of them named `controller`
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [N/A] Any dependent changes have been merged and …
=> don't fail when control plane listener name is undefined

roles/confluent.zookeeper/tasks/health_check.yml
We are including the `health_check.yml` tasks in some custom playbooks, e.g. patching and rebooting:
```yaml
import_role:
name: confluent.zookeeper
tasks_from: health_check.yml
```
We prefer to run everything in check mode on feature branches in our GitOps approach. While the Kafka Broker health checks are running fine in check mode, the Zookeeper health checks are not. This PR fixes this issue.
Verified ok in our GitOps managed environments. Running fine both in check mode and non check mode.
=> Allow Zookeeper health check in check mode

VARIABLES.md, roles/confluent.kafka_broker/tasks/dynamic_groups.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml
jmx config file is hardcoded in playbook, but confluent grafana dashboards expect onather version
This change allow user to specify an alternative file to use as source.
New feature (non-breaking change which adds functionality)
run playbook with an inventory containing `kafka_broker_jmxexporter_config_file` and/or `zookeeper_jmxexporter_config_file` defined to a custom jmx config file
=> define jmx config file thru variables

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
This PR allows package install tasks to fail in check mode. This should give better support for desired state upgrades, ref. #591.
We prefer to run all desired state playbooks in check mode before we apply changes to a system, typically `ansible-playbook --check --diff <playbook>`. This allows us to QA the changes that will be applied - before running the playbook "for real". Not all Ansible modules supports diff mode, but this has proven to be a very useful technique.
When switching to a new version branch of cp-ansible as part of an upgrade, the package install tasks are currently failing in check mode - because the package repository hasn't been updated yet. This PR fixes this, and I hope this is an acceptable change.
Fixes # (#591)
Tested that this fixes our check mode issue.
=> Ignore errors for package install tasks in check mode

roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.test.ldap/tasks/main.yml, roles/confluent.test/molecule/certificates.yml, roles/confluent.test/molecule/mtls-custombundle-rhel/prepare.yml, roles/confluent.zookeeper/tasks/main.yml, tasks/certificate_authority.yml
This PR replaces all loops on package install tasks with a list of packages supplied to the `yum` and `apt` ansible modules. This should improve performance on the desired state package tasks.
I have left out the upgrade-playbooks, at least for now, as they are not idempotent (#https://github.com/confluentinc/cp-ansible/issues/588) and will typically be run just once.
=> Use list in all yum/apt package install tasks

roles/confluent.control_center/defaults/main.yml
Adding `CONTROL_CENTER_LOG4J_OPTS` variable back.
=> [MINOR] Adding C3 LOG4J_OPTS variable back

roles/confluent.common/tasks/remove_packages.yml, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
The installed packages will now be checked for an eventual upgrade/downgrade of packages - including upgrading from confluent-kafka to confluent-server (and vice versa).
Obsolete packages are removed [_after stopping service_](https://github.com/confluentinc/cp-ansible/pull/607#issuecomment-805343543), and the existing desired state package install will take care of installing correct packages.
Fixes #591 
Tested partially in our custom playbooks upgrading from CP 5.4 to 5.5. Also tested upgrade/downgrade a few times CP 6.1.0 <-> CP 6.1.1. My test environment is colocated, and that seems worse than non colocated...
=> Support for desired state package upgrade/downgrade

VARIABLES.md, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/templates/kafka_server_jaas.conf.j2, roles/confluent.test/molecule/zookeeper-kerberos/molecule.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml, roles/confluent.zookeeper/templates/zookeeper_jaas.conf.j2
- Fixes bug that actually enforces digest auth for server to server auth. 
- Creates two new variables `zookeeper_quorum_authentication_type` and `zookeeper_client_authentication_type` - before it was unclear what auth was applied to client vs quorum connections
ZK Docs: https://cwiki.apache.org/confluence/display/ZOOKEEPER/Server-Server+mutual+authentication
Reran zk-kerberos and zk-digest scenarios
=> ANSI-721 - ZK Digest Auth Mode fix + variable rename

galaxy.yml, meta/runtime.yml
Relates to https://github.com/confluentinc/cp-ansible/issues/613
This PR adds `galaxy.yml`, that fulfills the minimal requirements to use `ansible-galaxy` CLI to install the contents of cp-ansible repository as an Ansible Collection.
```script
$ ansible-galaxy collection install git+https://github.com/erikgb/cp-ansible.git,ansible-galaxy-cli
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'confluent.kafka:6.2.0' to '/home/erikbo/.ansible/collections/ansible_collections/confluent/kafka'
Created collection for confluent.kafka at /home/erikbo/.ansible/collections/ansible_collections/confluent/kafka
confluent.kafka (6.2.0) was installed successfully
```
I scaffolded a new collection using ansible-galaxy
```script
$ …
```
=> Add initial Ansible collection meta

VARIABLES.md, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/tasks/set_principal.yml, roles/confluent.ksql/tasks/set_principal.yml, roles/confluent.ksql/templates/ksql-server_log4j.properties.j2, roles/confluent.test/molecule/scram-rhel/molecule.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/filter_plugins/filters.py, roles/confluent.variables/vars/main.yml
Can now set `sasl_protocol: scram256` 
`scram` will represent scram-512
Solves a ksql bug which checked for scram 256
Updates the client_properties and listener_properties filter
Still will only allow one sasl protocol per listener, but can have different scrams on different listeners
Updated `scram-rhel` scenario to test both scram options
=> ANSI-730 - Scram 256 sasl mechanism

.ansible-lint.yml, .github/workflows/linter.yml, DEVELOPMENT_GUIDE.md
Add `ansible-lint` to the linter GitHub Actions workflow. The initial ansible-lint configuration is **very** loose, since it is configured to pass with the existing codebase, and should be thightened over time.
Ansible-lint will lift the general code quality (opinionated), support PR review and avoid writing ALL details in the newly added developer guidelines.
The config file currently has the .yml extension, which is not the ansible-lint default. I have filed https://github.com/github/super-linter/pull/1424 to be able to name the file according to the ansible-lint default (`.ansible-lint`). But until that fix is available in a release, you'll have to run `ansible-lint -c .ansible-lint.yml` to check locally.
Also fixed a minor bug in the dev guide TOC.
=> Add ansible-lint to linter GHA workflow

.ansible-lint, roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/failure_handling.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.control_center/tasks/main.yml, tasks/masterkey.yml, tasks/upgrade_component.yml, upgrade_kafka_broker.yml, upgrade_ksql.yml, upgrade_zookeeper.yml
to enable `risky-file-permissions` ansible-lint rule.
File permissions are now mentioned in the development guidelines. To facilitate PR review, it seems attractive to fix all missing file permissions in current codebase and enable the `risky-file-permissions` ansible-lint rule. Then at least file permissions must be set, and can be reviewed.
=> Add missing file permissions

.ansible-lint, tasks/masterkey.yml, upgrade_kafka_connect.yml, upgrade_kafka_rest.yml, upgrade_ksql.yml, upgrade_schema_registry.yml
Any tasks marked as changed, if nothing is changed, annoys me. Fixing the existing violations allowing us to enable the `no-changed-when` rule will ensure any future PR will have to consider this.
=> Add missing changed_when to enable no-changed-when ansible-lint rule

.ansible-lint, control_center.yml, kafka_broker.yml, kafka_connect.yml, kafka_connect_replicator.yml, kafka_rest.yml, ksql.yml, zookeeper.yml
and enable `command-instead-of-module` ansible-lint rules.
Removing more rules from the ansible-lint skip list could improve code quality over time.
=> Convert systemctl shell tasks to module

.yamllint
Minor change of the yamllint rules. Instead of having to ignore selected files, I suggest to disable the `truthy.check-keys` rule. I think this could/should be merged into the 6.1.1-post branch, but feel free to disagree. 😉
=> Disable yamllint truthy.check-keys

roles/confluent.common/tasks/main.yml
The change made is purely a cosmetic fix for the cp-ansible respository. It was discovered when I was updating the cp-ansible repository for my organization and I ran into a typo in your play. 
Changed the registered value, as well as the conditional value from:
joklokia_download_ressult -> jolokia_download_result
The changes are only cosmetic, the play "roles/confluent.common/tasks/main.yml Download Jolokia Jar" registers that jolokia have been downloaded. Ansible will not proceed with the next play until it has succeeded downloading using the "until" conditional. 
=> Fixed typo in confluent.common/tasks/main.yml joklokia_download_result -> jolokia_download_result

roles/confluent.common/tasks/rbac_setup.yml, upgrade_kafka_broker_log_format.yml, upgrade_kafka_rest.yml, upgrade_schema_registry.yml, upgrade_zookeeper.yml
When `installation_method: archive`:
- The path to the zookeeper shell binary is hard to keep track of on all of the ZK hosts (because they may or may not be upgraded at this point and the path has a version number built in) -> removed the task that checks quorum after one host is shut down. We do not do that for kafka, wont do it with ZK
- zookeeper-shell command for getting the kafka cluster id has non secure port (2181) hardcoded and the binary path will not work for archive install. Fortunately in the case of creating role bindings, we can assume the MDS is running and can request the kafka cluster ID from the Admin API. In the future, can update the get cluster id code from ZK to match `roles/confluent.kafka_broker/tasks/dynamic_groups.yml`.
- Gathers `ansible_os_family` fact in all …
=> 611 Upgrade Bugfixes

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
The `Create Zookeeper User` task fails for hosts that have non local linux users. (ie users saved in active directory). Adding a simple check to see if the user exists, and skipping that task as necessary. Uses the [getent Module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/getent_module.html) which returns a dictionary named `getent_passwd` that will have a subdictionary for the username searched. Like this:
```
ok: [schema-registry1] => {
"getent_passwd": {
"cp-schema-registry": [
"x",
"991",
"998",
"Confluent Schema Registry",
"/tmp",
"/sbin/nologin"
]
}
}
```
Also updated the User comment to match that of the users that get created with package installation.
Ran this with `plain-rhel` scenario, and saw that the task gets skipped (bc the …
=> Support non-local linux Users

roles/confluent.variables/vars/main.yml
Minor bugfix for replicator properties, missing argument to the client filter
Ran the `molecule converge -s kafka-connect-replicator-mtls-scram-rhel`
=> Replicator filter bugfix

roles/confluent.variables/vars/main.yml
client_properties filter had mis ordered arguments, causing connect failures
ran `rbac-plain-provided-debian` test successfully
=> 62x Fix the client_properties filter arguments

roles/confluent.kafka_broker/tasks/dynamic_groups.yml, roles/confluent.zookeeper/tasks/dynamic_groups.yml, upgrade_kafka_broker_log_format.yml
dynamic_groups.yml tasks fail when `installation_method: archive` and `confluent_package_version` gets switched - this is because the commands are built out of full paths that have the version built in. The solution is to first figure out what the current version is before running those commands and add a variable.
Without this essentially upgrades with `installation_method: archive` fail.
Ran zookeeper.yml and kafka_broker.yml with `confluent_package_version: 6.1.0` and then set it to 6.1.1
=> Archive upgrade bugfix for archive installer

roles/confluent.test/molecule/Dockerfile.j2, roles/confluent.test/molecule/kafka-connect-replicator-plain-kerberos-rhel/molecule.yml, upgrade_kafka_broker_log_format.yml
Between 6.1.0-post and 6.1.1-post we changed the logic around sasl plain and sasl scram users, so that only the components which exist in the inventory file will have a user created.  Previously we created all default users no matter which components were defined.
With this change, it broke the kafka-connect-replicator-plain-kerberos-rhel molecule scenario due to the kafka-connect-replicator group not existing when the first MDS cluster is created.  This led to the replicator user credentials not being added to the MDS cluster, which was preventing replicator from consuming from this cluster.
By overriding the users for the mds cluster, to include the replicator user and password, we bypass this issue.
Validated kafka-connect-replicator-plain-kerberos-rhel  with the fix in …
=> Replicator plain kerberos fix

roles/confluent.variables/vars/main.yml
kafka-topic command is complaining that BCFKS type keystore, not supported. Simple solution is to make sure the kafka client uses the PKCS12 keystores instead
`mtls-custombundle-rhel` tests fips enabled and was failing
=> Client properties should not be using BCFKS Keystores

roles/confluent.common/tasks/remove_packages.yml
fully qualified module name is not compatible with ansible 2.7, error from customer: 
```
TASK [Stop Service and Remove Packages on Version Change] ******************************************************************************************************************************************************
task path: /etc/ansible/standalone/cp-ansible-6.2.0-post/roles/confluent.zookeeper/tasks/main.yml:17
Monday 21 June 2021  11:59:39 -0700 (0:00:00.980)       0:01:36.965 ***********
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.
The error appears to have been in '/etc/ansible/standalone/cp-ansible-6.2.0-post/roles/confluent.common/tasks/remove_packages.yml': line 32, column 3, but may
be elsewhere in the file depending on the exact …
```
=> removing the ansible fully qualified module name

roles/confluent.kafka_broker/tasks/dynamic_groups.yml
Fix to support dynamic groups with zk chroot
Ran `zookeeper-mtls` scenario twice with `deployment_strategy: rolling`
dynamic groups works
=> ZK Chroot logic fix

roles/confluent.variables/vars/main.yml
`kafka_connect_ssl_mutual_auth_enabled` was not properly setting connect properties. Only need to make the change for connect
Connect docs: show the client.auth property options as required, requested, none
https://docs.confluent.io/platform/current/kafka/encryption.html#encryption-ssl-rest
SR Docs, show this property uses boolean
https://docs.confluent.io/platform/current/schema-registry/installation/config.html#ssl-client-auth
RP Docs: show this property uses a boolean
https://docs.confluent.io/platform/current/kafka-rest/production-deployment/rest-proxy/security.html#id1
ksqldb docs show this property is a boolean:
https://docs.ksqldb.io/en/latest/operate-and-deploy/installation/server-config/security/#configuring-listener-for-ssl-encryption
Fixes # …
=> Corrects kafka connect mtls property

roles/confluent.test/molecule/mtls-java11-debian/molecule.yml, roles/confluent.test/molecule/mtls-java11-ubuntu/molecule.yml
A report from support indicated that a user was seeing failures in user and directory creation when running playbooks with CP-Kafka on ubuntu 20 and Debian 10.  We advised both are currently not supported, however validated against our latest branch of Ubuntu 18.04 and Debian 9, and confirmed that functionality works as expected.
Discovered that the two scenarios required usage of docker files, to configure OS dependencies.  This PR adds the appropriate docker files to those scenarios.
Validated against the following molecule scenarios:
mtls-java11-debian
mtls-java11-ubuntu
=> Updates to two molecule scenarios.

roles/confluent.kafka_rest/tasks/rbac.yml
Updated rbac topic permissions for rest proxy to be resource owner on monitoring interceptor to allow the automated creation of the monitoring interceptor topic when C3 is not present and to prevent race conditions leading to functionality issues.
Validated with rbac-kerberos-debian scenario.  Specifically confirmed that denials for the rest proxy user no longer occur when the cluster is stood up due to race conditions and also when C3 is not present.
=> Updated rbac topic permissions for rest proxy to be resource owner.

ansible.cfg
This change adds the poperty to the ansible config for setting the remote tmp location for ansible to use.  It's set to ansible's default, however by being present allows the customer to easier override this, when in secure/locked down environments.
Validated with archive-plain-rhel scenario.
=> Added property for setting remote tmp location in ansible config.

hosts_example.yml, roles/confluent.test/molecule/archive-plain-rhel/molecule.yml, roles/confluent.test/molecule/archive-plain-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
Updated hosts_example to remove deprecated datadir variable.  All log location overrides should be handled via custom broker properties:
kafka_broker_custom_properties:
log.dirs: dir1,dir2
https://github.com/confluentinc/cp-ansible/issues/690
=> Updated hosts_example to remove deprecated datadir variable

control_center.yml, kafka_broker.yml, kafka_connect.yml, kafka_connect_replicator.yml, kafka_rest.yml, schema_registry.yml, zookeeper.yml
Getting reports that with `deployment_strategy: rolling` - and a host failure, playbook execution is continuing. Upon local testing I can't replicate
But reading the docs: https://docs.ansible.com/ansible/latest/user_guide/playbooks_error_handling.html#aborting-a-play-on-all-hosts
It says:
> By default, Ansible continues to execute tasks as long as there are hosts that have not yet failed.
So to be safe, I am adding `any_errors_fatal: true` on any rolling deployment playbooks.
Set a variable that does not work with a rolling deployment, do a rolling deployment and make sure the playbook does not continue
=> Force playbook failure on any failure

roles/confluent.common/tasks/rbac_setup.yml, roles/confluent.control_center/tasks/rbac.yml, roles/confluent.kafka_broker/tasks/rbac_rolebindings.yml, roles/confluent.kafka_connect/tasks/rbac.yml, roles/confluent.kafka_rest/tasks/rbac.yml, roles/confluent.ksql/tasks/rbac.yml, roles/confluent.schema_registry/tasks/rbac.yml
Update RBAC URI calls, along with API calls to retrieve cluster_ID to not run during check mode, as they require interaction with the API which is generally not available when running check mode.
Tested with scenario: rbac-scram-custom-rhel
1. Run scenario rbac-scram-custom-rhel
2. Run the scenario again via cache, with --check option: 
ansible-playbook -i ~/.cache/molecule/confluent.test/rbac-scram-custom-rhel/inventory all.yml --check
=> Updated RBAC URI calls to not run when using check mode

roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.test/molecule/archive-plain-rhel/molecule.yml
Cluster Registry is apart of the MDS.  Customers have been confused by not running MDS and receiving errors when specifying a cluster name.
I have added an additional logic gate to prevent registrations calls from running unless MDS is enabled.
I have updated the archive-plain-rhel scenario to use register cluster names, while rbac is not enabled.  This validates that the calls are not made.
=> Cluster Registration requires MDS activation

.ansible-lint
This updates the ansible-lint config to skip a [disputed](https://github.com/ansible-community/ansible-lint/discussions/1589) experimental rule that is already "violated" in our code base.
Ran `ansible-lint -c .ansible-lint -qq --force-color *.yml` locally without errors.
=> Fix ansible-lint config: skip experimental rule

roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/tasks/health_check.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/templates/client.properties.j2, roles/confluent.test/molecule/mtls-custombundle-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
This PR adds functionality to encrypt the kafka client properties when secrets protection is enabled.
Validated and added a test on mtls-custombundle-rhel.
`    - name: Secrets Protection Test Client Configuration
import_role:
name: confluent.test
tasks_from: check_property.yml
vars:
file_path: /etc/kafka/client.properties
property: ssl.truststore.password
expected_value: ${securepass:/var/ssl/private/kafka-broker-client-security.properties:client.properties/ssl.truststore.password}`
=> Encrypt kafka client

VARIABLES.md, roles/confluent.test/molecule/kafka-connect-replicator-mtls-scram-rhel/molecule.yml, roles/confluent.test/molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, roles/confluent.variables/defaults/main.yml
This PR updates documentation and molecule scenarios to use TLS keystore/truststore variables appropriately.  No logic changes were required.
Validated against the following scenarios:
rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel
kafka-connect-replicator-mtls-scram-rhel
kafka-connect-replicator-plain-kerberos-rhel
=> Updated documentation around variables for TLS keystore/truststore.

roles/confluent.kafka_broker/files/kafka.yml
This change updates and optimizes the Kafka Broker JMX Exporter Rules to export all the JMX MBeans available and reducing the scrape to half its average values earlier. Another big change is that the MBeans that have the largest volume have been promoted towards the top so that the pattern matcher moves to the next case with minimum number of checks. 
This Scrape configuration has been tested with the jmx-monitoring-stacks repository. 
=> Optimized Metric scrape rule parsing

roles/confluent.ksql/tasks/rbac.yml
Failing to finish install when remote MDS is used due to incorrectly constructed mds URL when centralized MDS is used.
Executed installation with remote MDS with provisioning of ksql_processing_log
RBAC deployment with centralized MDS and KSQL processing log streamed to a topic ie `ksql_log_streaming_enabled:true`
=> fix for rolebinding for ksql_log_streaming_enabled with centralized MDS

roles/confluent.ssl/tasks/export_certs_from_keystore_and_truststore.yml
Minor bug fix to standardize the output of '.jks' to lower case to make sure that the correct checks are run when exporting from user provided keystores and truststores.
This has been validated against the following molecule scenario:
rbac-plain-provided-debian
=> Updated export check of certs from jks file to be lower case

.gitignore, molecule/Dockerfile-debian.j2, molecule/Dockerfile-debian10-archive.j2, molecule/Dockerfile-ubuntu.j2, molecule/Dockerfile-ubuntu2004.j2, molecule/Dockerfile.j2, molecule/plaintext-rhel/verify.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/verify.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/verify.yml, molecule/rbac-mtls-provided-ubuntu/verify.yml, molecule/rbac-mtls-rhel8/verify.yml, molecule/rbac-plain-provided-debian/verify.yml, roles/common/defaults/main.yml, roles/common/tasks/debian.yml, roles/common/tasks/redhat.yml, roles/common/tasks/ubuntu.yml, roles/kafka_broker/tasks/main.yml, roles/variables/defaults/main.yml
This PR includes changes to reflect the new packaging model for confluent platform.  Client packages are now being split out independently with the 7.0 release, so they can be updated/iterated on faster then the rest of the platform.
This PR adds the new package repos to all supported OS.
The following molecule scenarios have been updated to validate that new packages are setup on all supported platforms:
rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004
rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10
rbac-mtls-rhel8
plaintext-rhel
rbac-mtls-provided-ubuntu
rbac-plain-provided-debian
=> Updated packaging paths for kafka clients

roles/confluent.ksql/templates/ksql-server_log4j.properties.j2
Tested with Kafka listener with mTLS and  ```ksql_log_streaming_enabled: true``` in the inventory file. This setup was failing with error ```errorMessage=SSL handshake failed caused by Empty client certificate chain``` . This got resolved when the additional setting was added. This matches the example provided in the ksql documentation here https://github.com/confluentinc/cp-demo/blob/master/scripts/helper/log4j-secure.properties …
=> fixed SSL handshake issue for ksql streaming log into kafka usig mTLS

roles/confluent.kafka_broker/tasks/dynamic_groups.yml, roles/confluent.zookeeper/tasks/dynamic_groups.yml
Update regex to get the correct version of Confluent Platform
Converged scenario archive-plain-debian
In first pass the dynamic_goups tasks doesn't get triggered
converge the scenario again
Verify the path in confluent.zookeeper : Get Leader/Follower
Tested with below values for archive_destination_path
/svc/engn001/confluent
/opt/confluent700/
/opt/confluent
Local Environment
=> Update regex to get correct version of cp archive

Jenkinsfile
The Ci/CD Nightly job will pass a URL that will (likely) return a 400 as its an S3 bucket + key path. Which there is no indexing. Trust that the triggering job knows that there are packages at confluent_common_repository_baseurl.
This check was added: https://github.com/confluentinc/cp-ansible/commit/cc7d5f341bc7c6d11c83ec9cde7e225b7308653e some time back. In the nightly CI/CD context though, this check is meaningless, because whats passed for CI/CD will return a 400, as there is no Key at (for example) `https://s3-us-west-2.amazonaws.com/<nightly-bucket>/6.2.x/433`, but RPM, DEB and Archive packages are there if the paths are appended (ie: `https://s3-us-west-2.amazonaws.com/<nightly-bucket>/6.2.x/433/archive/6.2/confluent-6.2.1.tgz` ), so we disable this check in CI/CD. …
=> build: Set validate_hosts to false when triggered by CI/CD Nightly Job

roles/confluent.variables/vars/main.yml
When CCloud Schema Registry is enabled, and no schema_registry group defined, URL is not set properly.
Fixes #802
Against CCloud.
=> fix(ccloud): set SR url when ccloud SR is enabled

roles/confluent.test.ldap/tasks/tls_custom_certs.yml
There are a few scenarios which uses prepare steps. In recent fix, we added a flag to suppress sensitive information. This variable is not available to prepare step, hence adding it manually
Tested locally 
```
molecule --debug converge -s rbac-scram-custom-rhel
```
Local Docker envionment
=> Update test configuration

hosts_example.yml, roles/variables/vars/main.yml
Per host, in case there are multiple interfaces and you need to listen on only one of them, you can also specify which interface to listen on, per listener.
On each listener, you need to add an 'ip' value. This will adjust the 'listeners' section per host.
Inventory example is provided.
We have tested it at the customer site.
=> Ability to specify the interface to listen on for the broker listeners

roles/confluent.common/tasks/host_validations.yml
We are using a proxy to reach https://packages.confluent.io, and this proxy insists on a trailing slash added to `confluent_common_repository_baseurl` variable to return HTTP 200 OK as part of the "host validations". This trailing slash is unwanted in our configuration because it "breaks" the other variables deduced from `confluent_common_repository_baseurl`.
This PR fixes this by allowing temporary redirect status codes (302 and 307) in addition to 200 OK.
=> fix: more lenient Internet access check

roles/confluent.common/tasks/redhat.yml
This PR is a partial revert of https://github.com/confluentinc/cp-ansible/pull/786. It removes the `yum makecache` tasks - which seems to slow down our pipeline significantly and requires a lot more disk space for the yum cache than it used to (blowing our disks in a couple of clusters). And there should be no need to build up a full cache right after `yum clean all` (the task right before).
Also cleaned up the when on the `yum-clean-all` task - to make it more readable. The play will still always run `yum clean all` for configurations with `repository_configuration == 'custom'` - as introduced with https://github.com/confluentinc/cp-ansible/pull/786.
It would be nice if @22RC could check this feature branch with regards to https://github.com/confluentinc/cp-ansible/issues/785.
And I …
=> fix: remove 'yum makecache' task

roles/confluent.kafka_broker/tasks/set_principal.yml
This PR addresses the use case where a user has enabled RBAC but not set an authentication mechanism on the internal listener.  Previously in this scenario, a generic ansible error for an undefined error would be thrown.  Now a clear error stating that authentication must be set on the internal listener is thrown:
```
"Role Based Access Control (RBAC) requires that an authorization mechanism is set on the internal listener, please review Confluent documentation for further details."
```
ANSIENG-940
This has been validated by running the rbac-scram-custom-rhel molecule scenario and not setting the sasl_protocol variable.
Output:
```
TASK [confluent.kafka_broker : Validate that auth is set for RBAC on internal listener] ***
fatal: [kafka-broker2]: FAILED! => {"changed": …
```
=> Error check to validate authentication is set with RBAC.

roles/confluent.kerberos/defaults/main.yml, roles/confluent.kerberos/templates/krb5.conf.j2
This PR adds an additional configuration property to the krb5.conf to true in order to better support Active Directory when it is being used as the KDC.  It makes sure that the correct principal is used when RBAC and ACLs are enabled with kerberos on AD.
ANSIENG-164
This has been validated by running the kerberos-rhel scenario to validate that the additional property does not break existing functionality as well as working with the MIT KDC.
Output of krb5.conf here:
```
[libdefaults]
default_realm = REALM.EXAMPLE.COM
dns_lookup_realm = false
dns_lookup_kdc = false
ticket_lifetime = 24h
forwardable = true
udp_preference_limit = 1
default_tkt_enctypes = aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96 arc-four-hmac rc4-hmac
default_tgs_enctypes = aes256-cts-hmac-sha1-96 …
```
=> Added canonicalize = false property to krb5.conf to better support Active Directory.

roles/confluent.test/molecule/archive-plain-rhel/molecule.yml
Update the docker image for `archive-plain-rhel` scenario. With vanilla image, the test fails to find the keytool causing the scenario to fail
Verified on local environment. The mask_sensitive_log flag was disabled for debugging purposes 
Before the fix
```
TASK [confluent.platform.ssl : Create Truststore and Import the CA Cert] *******
fatal: [zookeeper1]: FAILED! => {"changed": true, "cmd": "keytool -noprompt -keystore /var/ssl/private/zookeeper.truststore.jks  -storetype pkcs12  -alias CARoot  -import -file /var/ssl/private/ca.crt  -storepass confluenttruststorepass  -keypass confluenttruststorepass\n", "delta": "0:00:00.119394", "end": "2021-12-02 13:05:38.098466", "msg": "non-zero return code", "rc": 127, "start": "2021-12-02 13:05:37.979072", "stderr": "/bin/sh: …
```
=> Test Fix: Update image for test scenario

roles/confluent.test/molecule/zookeeper-mtls/molecule.yml, roles/confluent.test/molecule/zookeeper-mtls/verify.yml
Molecule tests for scenario zookeeper-mtls were failing on task 
`TASK [confluent.ssl : Copy CA Cert to Host]`
because of the task  `Create Certificate Authority and Copy to Ansible Host` getting skipped. 
Setting ssl_enabled to true fixes the issue. 
Accordingly, one of the VERIFY tasks need to be changed since the expected value of property kafkastore.security.protocol will now be SASL_SSL. 
Fixes # ([As part of 5.5.x release readiness](https://confluentinc.atlassian.net/browse/ANSIENG-963?atlOrigin=eyJpIjoiYTU0MThmZGMyZjc1NGY5MGFhOTUyMzEyMTA1N2M3MjUiLCJwIjoiaiJ9))
`molecule --debug test -s zookeeper-mtls` gives an all pass/success. 
**Test Configuration**:  molecule run for scenario zookeeper-mtls on 5.5.x
=> Fix molecule tests for scenario 'zookeeper-mtls'

Jenkinsfile, VARIABLES.md, roles/common/defaults/main.yml
This change fixed a CI issue where the values feed into CONFLUENT_PACKAGE_BASEURL now longer have a `/clients` repo behind them. The ideal situation is that `https://packages.confluent.io/clients/` is unconditionally used irrespective of where we point `confluent_common_repository_baseurl` too with a nightly/staged release.
You can see these failures in CI when triggered by the upstream CI Packaging job.
CI runs with params and without should work.
=> feat: Refactor c/c++ clients release repository.

roles/confluent.test/molecule/rbac-mtls-provided-ubuntu/molecule.yml
This PR corrects a bug in the 5.5.x molecule scenario rbac-mtls-provided-ubuntu.  The LDAP password for accessing the trust store to authentication was not set correctly.
This has been validated by running the rbac-mtls-provided-ubuntu scenario on the 5.5.x and validating that verification passes.
=> Corrected password for trust store access for LDAP configuration.

roles/confluent.test/molecule/rbac-mtls-rhel/verify.yml
'Verify' step in molecule tests of scenario 'rbac-mtls-rhel' fails on task `Create connector`
Issue is resolved with the updated name of the connector. 
`molecule --debug test -s rbac-mtls-rhel` on branch 5.5.x gives all pass/success.
=> Fix connector name in 'verify' for scenario 'rbac-mtls-rhel'

roles/confluent.kafka_broker/tasks/rbac_rolebindings.yml, roles/confluent.test/molecule/rbac-mds-kerberos-mtls-custom-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-mtls-custom-rhel/molecule.yml
This PR addresses two bugs in testing scenarios:
1. Audit log variable was spelled incorrectly
2. The expected http response for audit log role bindings should be 200 not 204.
Have run and successfully validated the rbac-mds-mtls-custom-rhel scenario.
=> Corrected variables and role binding response.

roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml
Molecule tests for the scenario 'mtls-customcerts-rhel' were failing on task:
`TASK [confluent.zookeeper : Install the Zookeeper Packages]` with error as `Error: confluent-server conflicts with confluent-kafka-2.12-5.5.7-1.noarch`
Enabling default value of 'confluent_server_enabled' (which is true) resolved the issue. 
Fixes # ([As part of 5.5.x release readiness](https://confluentinc.atlassian.net/browse/ANSIENG-963?atlOrigin=eyJpIjoiYjZhOTEyNGUwYzgxNGRhMjllNGVkZmMzNWRlMDdiNWYiLCJwIjoiaiJ9))
`molecule --debug test -s mtls-customcerts-rhel` gives all pass/success.
**Test Configuration**: molecule run for scenario mtls-customcerts-rhel on 5.5.x
=> Fix molecule tests for scenario 'mtls-customcerts-rhel'

roles/confluent.kafka_broker/tasks/set_principal.yml
This PR removes a check on the internal listener when RBAC is enabled, to confirm a principal is set.  Unfortunately this code behaves inconsistently for an unknown reason, thus we are removing it for now.
This has been validated by running the rbac-mds-mtls-rhel scenario and validating it passes.
=> Remove internal listener principal check, due to inconsistent behaviour.

roles/confluent.kafka_broker/tasks/rbac_rolebindings.yml, roles/confluent.kafka_broker/tasks/set_principal.yml, roles/confluent.test/molecule/rbac-mds-mtls-custom-rhel/molecule.yml
This PR corrects the following:
1. Updates the rbac-mds-mtls-custom-rhel scenario to use cluster names to test audit logging properly
2. Removes hardcoded URL paths for setting RBAC permissions on audit logs
3. Added both 200 and 204 codes as acceptable responses for RBAC permission creation for audit logs.
3. Removes a check for the user being set on the internal listener due to inconsistent performance.
This has been validated by running the  rbac-mds-mtls-custom-rhel scenario with full verification.
=> Audit logs test scenario update

VARIABLES.md, roles/confluent.kafka_broker/tasks/set_principal.yml, roles/confluent.test/molecule/kafka-connect-replicator-plain-kerberos-rhel/molecule.yml, roles/confluent.test/molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, roles/confluent.variables/defaults/main.yml
This PR updates the Kafka Connect Replicator Plain Kerberos RHEL scenario to properly run.  We needed to add additional properties for keystore and truststore passwords, remove rbac and ldap related properties as this scenario was introduced before RBAC support on replicator.
ansieng-985.
This Kafka Connect Replicator Plain Kerberos RHEL scenario  now completes and the verification produces and consumes data while it is transferred between clusters via replicator.
=> 61x kafka connect replicator plain kerberos rhel

roles/confluent.common/tasks/redhat.yml, roles/confluent.common/templates/confluent.repo.j2, roles/confluent.common/vars/main.yml
This PR makes cp-ansible fully manage the yum `confluent.repo` file using a template; to mend the version upgrade/downgrade issues described in #833. This will assure the correct/desired state on the repo-file when repositories are removed on upgrade/downgrade.
This might be considered a breaking change if any user has added additional repositories to `confluent.repo`.
Fixes #833 
=> fix: fully manage yum confluent.repo file

roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_monitoring.yml
Remove duplicate and invalid tasks from rbac_replicator_rolebinding task
Fixes # (ANSIENG-1012)
` molecule --debug converge -s rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel`
```
TASK [confluent.kafka_connect_replicator : Create SSL Certificate Directory] ***
skipping: [kafka-connect-replicator1]
TASK [confluent.kafka_connect_replicator : Copy in MDS Public Pem File] ********
skipping: [kafka-connect-replicator1]
TASK [confluent.kafka_connect_replicator : Grant connect user the DeveloperWrite role on Monitoring Interceptor Topic] ***
skipping: [kafka-connect-replicator1]
TASK [confluent.kafka_connect_replicator : Grant connect user the DeveloperWrite role on Monitoring Interceptor Topic] ***
ok: [kafka-connect-replicator1]
```
=> Remove deuplicate tasks from rbac_replicator_monitoring

VARIABLES.md, roles/confluent.common/tasks/main.yml, roles/confluent.variables/defaults/main.yml
I was originally trying to fix an issue related to check mode when trying to upgrade Prometheus JMX Exporter. Somehow I didn't understand why some of the tasks were skipped in check mode - until I discovered https://github.com/ansible/ansible/issues/65687.
Then I actually tried to upgrade, and discovered that files were actually NOT updated. After some digging, it seems like we need to set the [force parameter](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/get_url_module.html#parameter-force) when using the `get_url` module, because the destination file does not change when modifying the version inventory variable. So without this fix, you will be stuck with the version installed initially.
Setting `force` to `true` is not recommended, since the file will be …
=> Add force: true when using get_url module to better support upgrade

tasks/rbac_setup.yml
1. Removed hardcoded zookeeper port
2. Run the command kafka broker using zookeeper fqdn
3. Update the logic for secure zookeeper to include `-zk-tls-config-file`
Fixes # (RCCA-5206)
` molecule --debug converge -s rbac-scram-custom-rhel ` removed the when condition for the task ` Get Kafka Cluster ID from Zookeeper` and added a debug messsage 
```
TASK [confluent.platform.common : Get Kafka Cluster ID from Zookeeper] *********
changed: [kafka-broker1]
changed: [kafka-broker3]
changed: [kafka-broker2]
TASK [confluent.platform.common : debug cluser id form zookeeper] **************
ok: [kafka-broker1] => {
"msg": {
"id": "xQMFtit3SUK3Z1jgEV09HA",
"version": "1"
}
}
ok: [kafka-broker2] => {
"msg": {
"id": "xQMFtit3SUK3Z1jgEV09HA",
"version": "1"
}
}
ok: [kafka-broker3] => {
"msg": {
"id": …
```
=> Update command to get cluster id from secured zookeeper

roles/confluent.kafka_broker/defaults/main.yml
This issue updates the location of SystemD override locations for kafka brokers as per the best practices of systemD docs.
https://www.freedesktop.org/software/systemd/man/sysctl.d.html
Corrects: ANSIENG-909
This has been validated by running the plaintext-rhel scenario successfully.
Have also manually verified the location of the overrides file on the file system.
=> Updated systemD override location for kafka brokers.

tasks/certificate_authority.yml
Add task to generate MDS private key. This task was missing in recent changes. 
` molecule --debug converge -s mtls-java8-ubuntu`
```
TASK [Register if MDS Private Key Exists on Ansible Controller] ****************
ok: [zookeeper1 -> localhost]
````
```
control-center1            : ok=68   changed=29   unreachable=0    failed=0    skipped=35   rescued=0    ignored=0
kafka-broker1              : ok=73   changed=34   unreachable=0    failed=0    skipped=43   rescued=0    ignored=0
kafka-broker2              : ok=73   changed=34   unreachable=0    failed=0    skipped=40   rescued=0    ignored=0
kafka-broker3              : ok=73   changed=34   unreachable=0    failed=0 …
```
=> Add missing task for MDS private key extraction

roles/confluent.common/tasks/rbac_setup.yml, roles/confluent.variables/filter_plugins/filters.py, roles/confluent.variables/vars/main.yml
This PR adds required properties for all CP components to talk to secured Metadata Server.  The detailed doc is [here](https://docs.confluent.io/platform/current/kafka/configure-mds/mds-ssl-config-for-components.html)
Fixes # ([FF-6440](https://confluentinc.atlassian.net/browse/ANSIENG-1024))
` molecule --debug converge -s rbac-mds-plain-custom-rhel`
```
control-center1            : ok=71   changed=30   unreachable=0    failed=0    skipped=40   rescued=0    ignored=0
kafka-broker1              : ok=86   changed=33   unreachable=0    failed=0    skipped=64   rescued=0    ignored=0
kafka-broker2              : ok=79   changed=33   unreachable=0    failed=0    skipped=46   rescued=0    ignored=0
kafka-broker3 …
```
=> Add client properties for secure mds

roles/zookeeper/tasks/dynamic_groups.yml
Use serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory as the canary
instead of ssl.clientAuth=need.
Change canary search for SSL-enabled ZooKeeper from ssl.clientAuth=need to serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory.
cp-ansible searches for the string
ssl.clientAuth=need
to determine if ZooKeeper has SSL enabled for the health check (done via FourLetterWord).
Customers who use SASL for the brokers to authenticate against ZooKeeper have ssl.clientAuth=none set instead (since ZooKeeper 3.5.7).
Therefore the health check will fail for rolling deployments.
This fix changes the search string to
serverCnxnFactory=org.apache.zookeeper.server.NettyServerCnxnFactory
This setting is a necessary requirement for enabling TLS for ZooKeeper …
=> Fix problem with healthcheck for ssl-enabled zookeeper.

roles/common/tasks/host_validations.yml, roles/common/tasks/main.yml
This PR adds unique tags for each host validation check.  This allows the end user to have greater control over which validations they wish to run when deploying the platform.
ANSIENG-1041
Validated successful completion of plaintext-rhel scenario.
Validated by skipping the /tmp directory check, note it skips and moves on to platform setup after internet check:
command: `molecule --debug converge -s plaintext-rhel -- --skip-tags="validate_tmp_access"|tee test1.txt`
Output:
`TASK [confluent.platform.common : Fail Provisioning because No Network Connectivity] ***
skipping: [zookeeper1]
skipping: [zookeeper2]
skipping: [zookeeper3]
skipping: [kafka-broker1]
skipping: [kafka-broker2]
skipping: [schema-registry1]
skipping: [kafka-connect1]
skipping: [ksql1]
skipping: …
=> Added additional tags to host validations to allow for greater control.

roles/variables/vars/main.yml
Why -> https://confluentinc.atlassian.net/browse/DGS-2898
As part of https://confluentinc.atlassian.net/browse/KC-1266 and https://confluentinc.atlassian.net/browse/FF-3817
There's been a change in license.topic used by cp components. 
Quoting from above links ->
`_confluent-command - Is where C3, Connect, Replicator and other CP components by default will look for their license.
`
In our codebase, we use the new license.topic for connect, replicator already. This PR aims to extend that for Schema Registry and Kafka rest. 
Local run on scenario mtls-customcerts-rhel passes. It uses schema_registry_authentication_type == 'mtls'
=> Change license topic for sr, kafka rest

molecule/rbac-mtls-rhel/molecule.yml, molecule/rbac-mtls-rhel/verify.yml, plugins/filter/filters.py, roles/kafka_broker/tasks/set_principal.yml
CP-Ansible has been ignoring the provided ssl.principal.mapping.rule This change enables to extract the Distingushed name from the keystore based on the provided rule. If there ain't any rule OR rule doesn't match to any common name, it defaults back to existing behavior. Which is extract the first common name as distinguished name
We need to escape the $ character while providing the rules in inventory file. Please see the testing section below. 
Fixes # ([ANSIENG-983](https://confluentinc.atlassian.net/browse/ANSIENG-983))
Reference doc - https://cwiki.apache.org/confluence/display/KAFKA/KIP-371%3A+Add+a+configuration+to+build+custom+SSL+principal+name
`molecule --debug converge -s rbac-mtls-rhel`
The default case when no mapping rule is specified 
```
TASK [confluent.kafka_broker : …
```
=> Add support for dmame extratction with given mapping rule

roles/confluent.kafka_broker/tasks/dynamic_groups.yml
Detailed history on the inc-rcca-5725 [slack channel](https://join.slack.com/share/enQtMzEwOTkxNzQwMDk3Ni0zMGIwYmNiNzIyOTc4ZDk4NWMxNTY4N2JlYTgzNjNkMjkxOTY1MGRkNjlhYTlmNGUxZGMyNjBkOTg5YWUxNWM3) 
This change will read broker.id from meta.properties in place of server.properties in dynamic_groups.yml. 
Reason for the change: 
During upgrade of co-located components, when all confluent services are stopped on the host, the server.properties gets wiped out and the broker.id goes to 0. This is restored by the end of upgrade for all but the host which is the kafka controller (for reasons unknown as of now). When we use the tasks in dynamic_groups.yml to read broker.id from meta.properties, things work as expected. The broker.id upholds its original value at the end of the upgrade. 
Fixes # …
=> Rcca 5725 - Get broker.id from meta properties

molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/verify.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/verify.yml, molecule/rbac-mtls-provided-ubuntu/verify.yml, molecule/rbac-plain-provided-debian/verify.yml
Verify playbooks of molecule were using hard coded client repository base url. This PR changes that to read from the variable defined in the role 'common' 
Tested by running verify stage of scenario - rbac-mtls-provided ubuntu on 7.0.x
=> Generalise client repo url in molecule verify

roles/confluent.kafka_broker/tasks/dynamic_groups.yml
This is to apply https://github.com/confluentinc/cp-ansible/pull/911 to 6.1.x too. 
Since, this branch also follows the similar flow of reading broker.id. 
As tested on 6.2.x (prev PR) 
=> (Copy of #911) Read broker.id from meta properties file

VARIABLES.md, roles/common/tasks/host_validations.yml, roles/common/tasks/main.yml, roles/variables/defaults/main.yml
This PR adds additional hosts checks to confirm that their is enough memory to install and run the given component.  Note, this is specifically to run the component based on its default heap size with extra buffer (1GB) for the operating system.  It is not considered to be the recommended setting for a production environment.
ANSIENG-256
This has been validated by running the mtls-customcerts-rhel scenario and confirm that all checks pass in addition to the replicator memory check being skipped as it's not available in this scenario.  This confirms that logic is correct for when to run the given check.
`TASK [confluent.platform.common : Validate enough free memory for Zookeeper hosts] ***
skipping: [kafka-broker1]
skipping: [kafka-broker2]
skipping: [kafka-broker3] …
=> 71x validate memory

roles/common/tasks/host_validations.yml
Noticed that the spacing/indentation on the following task was wrong in the host_validations.yml:
- name: Validate enough free disk space for package installation
assert:
that: item.size_available > {{ required_disk_space_mb }}|float
fail_msg: >- 
"Not enough free disk space for package installation.  Minimum space required is {{ required_disk_space_mb }}MB, please free up more disk space 
to continue installation. To skip host validations, set validate_hosts to false."
with_items: "{{ ansible_mounts }}"
tags: 
- validate
- validate_disk_usage
Ran mtls-customcerts-rhel to validate it runs correctly.
TASK [confluent.platform.common : Validate enough free disk space for package installation] ***
ok: [kafka-broker1] => (item={'block_used': 8916424, 'uuid': 'N/A', …
=> Corrected indentation on disk space validation task.

roles/confluent.variables/vars/main.yml
Based on the findings of https://confluentinc.atlassian.net/browse/ANSIENG-1050 and test failures visible in jenkins job for 6.2.x and 7.0.x, 
Changing the license.topic for sr, kafka rest and kafka brokers. 
Similar to https://github.com/confluentinc/cp-ansible/pull/906 where we made the fix for 7.1.x
Fixes # ([issue](https://confluentinc.atlassian.net/browse/ANSIENG-1050))
Tested as part of https://github.com/confluentinc/cp-ansible/pull/906
=> Fix license topic 6.2.x onwards

molecule/mtls-java8-debian/verify.yml, molecule/mtls-java8-rhel/verify.yml, molecule/mtls-java8-ubuntu/verify.yml
The scenarios mtls-java8-ubuntu, mtls-java8-debian and mtls-java8-rhel were updated to use java8 in place of java11. But the verify.yml of these scenarios weren't updated corresponding to that change. 
This PR asserts the java version to be 8 in place of 11.
`java --version` is erroneous and hence `java -version` has been used. 
Surprisingly, the stderr_lines contained the real version output and not the stdout_lines which was empty. Hence, it has been used. 
Fixes # (ANSIENG-1075 ANSIENG-1077)
Tested locally with max verbosity for mtls-java8-ubuntu using `molecule verify -s mtls-java8-ubuntu`
The scenario in itself runs without any issue -> cp-ansible-on-demand run 83
=> Assert java version to be 8

roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Discontinue the deprecated way of providing/overriding the data directory for kafka. Going forward, we should be using 
kafka_broker_custom_properties for the same. 
```
kafka_broker_custom_properties:
log.dirs: dir1,dir2
```
`molecule --debug converge -s mtls-ubuntu `
Docker based molecule scenario.
```
control-center1            : ok=78   changed=31   unreachable=0    failed=0    skipped=40   rescued=0    ignored=0
kafka-broker1              : ok=83   changed=36   unreachable=0    failed=0    skipped=48   rescued=0    ignored=0
kafka-broker2              : ok=83   changed=36   unreachable=0    failed=0    skipped=45   rescued=0    ignored=0
kafka-broker3 …
```
=> Discontinue deprecated way of specifying kafka logs dir

roles/variables/defaults/main.yml
As part of this PR https://github.com/confluentinc/cp-ansible/pull/783 to enable rootless installs, new variables to skip handlers were created. But a variable was left to be defined. This PR defines the variable `kafka_connect_replicator_skip_restarts`
Fixes # (ANSIENG-1073)
Also fixes 1056, 1069, 1064
cp-ansible-on-demand job 78. The logs are available on the jenkins job. 
=> ANSIENG 1073

roles/common/tasks/host_validations.yml
This PR updates the mount storage check to be informational only.  This is due to limitations in confluent packaging as well different packaging mechanisms (snap).
ANSIENG-1051
This has been validated against mtls-ubuntu.
`TASK [confluent.platform.common : Validate disk space usage] *******************
skipping: [zookeeper1] => (item={'mount': '/run', 'device': '/dev/vda1', 'fstype': 'ext4', 'options': 'rw,relatime,bind', 'size_total': 270294650880, 'size_available': 228907823104, 'block_size': 4096, 'block_total': 65989905, 'block_available': 55885699, 'block_used': 10104206, 'inode_total': 16777216, 'inode_available': 16401038, 'inode_used': 376178, 'uuid': 'N/A'})
skipping: [zookeeper1] => (item={'mount': '/tmp', 'device': '/dev/vda1', 'fstype': …
=> Updated mount storage host check to be informational.

molecule/zookeeper-mtls-rhel/molecule.yml, molecule/zookeeper-tls-rhel/molecule.yml
Molecule tests for zookeeper-tls-rhel and zookeeper-mtls-rhel use the incorrect location of all.yml. This PR resolves that. 
Fixes # (ANSIENG-1063 ANSIENG-1067)
cp-ansible-on-demand run 77 passes for both zookeeper-tls-rhel and zookeeper-mtls-rhel. Logs available on the jenkins job. 
=> ANSIENG-1063/1067

roles/kafka_broker/tasks/main.yml
This PR adds a new task to create the sysctl.d directory in /usr/lib as it is no longer present by default in Debian 10, despite being a valid configuration directory for systemd.  It previously existed in Debian 9.
ANSIENG-1054
Successfully ran the rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10 scenario after adding this additional task.
Original error:
`An exception occurred during task execution. To see the full traceback, use -vvv. The error was: FileNotFoundError: [Errno 2] No such file or directory: '/usr/lib/sysctl.d/.ansible_m_sysctl_c8kl51w4.conf'
failed: [mds-kafka-broker1] (item={'key': 'vm.max_map_count', 'value': 262144}) => {"ansible_loop_var": "item", "changed": false, "item": {"key": "vm.max_map_count", "value": 262144}, "module_stderr": …
=> Added additional task to create sysctl.d directory on Debian 10.

roles/confluent.kafka_broker/tasks/main.yml
This PR adds an additional task to create the sysctl.d directory in  /usr/lib in order to facilitate systemd service configuration.
Its a back port of: https://github.com/confluentinc/cp-ansible/pull/926
ANSIENG-1083.
Validated by running the rbac-kerberos-debian scenario and completing successfully.
=> Added additional task to create sysctl.d directory for configuration.

molecule/rbac-mtls-rhel8/molecule.yml, molecule/rbac-mtls-rhel8/verify.yml
This PR updates the rbac-mtls-rhel8 scenario to use the correct docker file.  It also updates the verification to not check the ldap host for confluent client packages as they are not installed there.
ANSIENG-1084
Successfully ran rbac-mtls-rhel8 scenario with verification:
`PLAY RECAP *********************************************************************
control-center1            : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker1              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker2              : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker3              : ok=2    changed=1    unreachable=0    failed=0 …
=> Updated scenario to use correct docker file.

roles/confluent.test/molecule/Dockerfile-debian.j2, roles/confluent.test/molecule/Dockerfile-ubuntu.j2, roles/confluent.test/molecule/Dockerfile.j2
https://confluentinc.atlassian.net/browse/ANSIENG-1047?atlOrigin=eyJpIjoiOWEyOWJkNmRlMzc4NDBiYTk3Nzc5YjM0NDk2MDc3MDYiLCJwIjoiaiJ9
For automating our patch releases, we need to read new binaries directly when running molecule tests. This change introduces env variables which'll resolve to new package binaries and new versions at runtime. 
With these change in place, to run a new patch, we'll need to set env variables COMMON_REPO_URL and VERSION before running the molecule tests to change dockerfiles. To make other relevant changes, we'll need to pass variables confluent_common_repository_baseurl and confluent_package_version/confluent_repo_version in molecule run. 
Default behaviour stays unchanged. 
cp-ansible-on-demand run 74. 
=> Reading binaries/version for molecule tests from env variables

molecule/rbac-mtls-rhel/verify.yml
Slack discussion - https://confluent.slack.com/archives/C020B5SDHB5/p1646054260762619
This PR will use the role name as variables in place of confluent.variables when importing, to conform to the latest changes. 
Fixes # (ANSIENG-1070)
Tested with running verify step on new ec2 instance. 
=> Fix import role in rbac-mtls-rhel verify.yml

roles/ssl/tasks/custom_certs.yml, roles/ssl/tasks/self_signed_certs.yml
New PR to replace https://github.com/confluentinc/cp-ansible/pull/751 because of issues with CI-pipelines.
Use Ansible module community.crypto.certificate_complete_chain to make SSL cert handling more robust. Targeting the `7.0.x` branch, since older branches might have users with older Ansible versions - that do not support using the `community.crypto` collection.
Fixes #737 #738 
I do not currently have an environment available to run CP 7.x, so I trust the CI to catch any problems.
=> Improve internal handling of SSL certificates

roles/confluent.test/molecule/Dockerfile-debian.j2, roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/Dockerfile-ubuntu.j2, roles/confluent.test/molecule/Dockerfile.j2
Extension of https://github.com/confluentinc/cp-ansible/pull/918 for 6.0.x
This also fixes a Dockerfile where we were reading 6.0.0 in place of 6.0.5
Tested as part of 918
=> Read packages/version from env vars - 6.0.x

roles/kafka_broker/defaults/main.yml, roles/kafka_connect/defaults/main.yml
Fixing the issue with kafka_broker and kafka_connect log4j config files getting defaulted to wrong filepath
`molecule converge -s archive-plain-debian10`
```
PLAY RECAP ************************************************************************************************************************************
control-center1            : ok=44   changed=0    unreachable=0    failed=0    skipped=42   rescued=0    ignored=0
kafka-broker1              : ok=52   changed=2    unreachable=0    failed=0    skipped=50   rescued=0    ignored=0
kafka-connect1             : ok=52   changed=2    unreachable=0    failed=0 …
```
=> Fixing the issue with kafka_broker and kafka_connect log4j config

VARIABLES.md, roles/confluent.kafka_broker/tasks/health_check.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
`mds_advertised_listener_hostname` is used to reference any external mds server. However the same is neither part of default variables, nor of doc.
A null or empty string doesn't translate to None while evaluating in the playbook. We have to evaluate as binary to work it in expected way. 
` molecule --debug converge -s mtls-debian`
```
control-center1            : ok=66   changed=37   unreachable=0    failed=0    skipped=30   rescued=0    ignored=0
kafka-broker1              : ok=78   changed=40   unreachable=0    failed=0    skipped=38   rescued=0    ignored=0
kafka-broker2              : ok=78   changed=40   unreachable=0    failed=0    skipped=37   rescued=0    ignored=0
kafka-broker3 …
```
=> Add mds_advertised_listener_hostname to default variables

molecule/zookeeper-mtls-rhel/verify.yml, molecule/zookeeper-mtls-secrets-rhel/verify.yml
Since this was a non-RBAC scenario, secret protection was not enabled by default here. And there will be no CLI installed here.
By running successfully following molecule scenarios
`zookeeper-mtls-rhel`
`zookeeper-mtls-secrets-rhel`
=> CLI won't be installed if secret_protection is disabled

molecule/multi-ksql-connect-rhel/verify.yml
Fixing an issue where a plus sign (+) was mistakenly left due to copy paste from github.
By running the same scenario `multi-ksql-rhel`
=> fix typo which made additional + on the begining of the line

Jenkinsfile
Our pre-commit tests fails intermittently for host validations. 
Our test infra doesn't has to be of same configuration as recommended for production system. We will skip the validation for memory and disk in pre-commit tests. However these tests should get executed in our regression jobs. 
Not tested
=> Skip memory and disk validation in regular pre-commit tests

roles/common/tasks/secrets_protection.yml, roles/kafka_broker/tasks/secrets_protection.yml, roles/ssl/tasks/provided_keystore_and_truststore.yml
For Secrets Protection, confluent client need to connect to MDS and if TLS is enabled, it need ca.crt to be available. So far we were not copying the certs until MTLS is enabled. This commit makes the condition to copy the ca.crt to host wider, and also includes the situation where RBAC and secrets_protection are enabled.
This is fixing the following 2 test cases
- rbac-plain-provided-debian
- rbac-mtls-rhel
=> Fix issues with provided cert and secrets enabled

roles/ksql/tasks/set_principal.yml
Noticed rolebindings for the ksql processing topic created with **User:User:principal** . This is caused by the following code
```
- name: Normalize User Name
set_fact:
ksql_log4j_principal: "User:{{ ksql_log4j_principal }}"
when: ksql_log4j_principal is defined
```
Removed the User: prefix as it is added during the rolebinding again.
Verified the code, the only place this is used is in the rolebinding.
7.1.x
=> fixed principal construction causing double User in the principal name

roles/common/tasks/rbac_setup.yml, roles/control_center/tasks/rbac.yml, roles/kafka_broker/tasks/rbac_rolebindings.yml, roles/kafka_connect/tasks/rbac.yml, roles/ksql/tasks/rbac.yml, roles/schema_registry/tasks/rbac.yml
Add a retry to certain tasks which we have recently seen failing intermittently with message - 
```
{"error_code": 50003, "message": "For requests intended only for the leader, this error indicates that the broker is not the current leader. For requests intended for any replica, this error indicates that the broker is not a replica of the topic partition."}
```
The error has been discussed at multiple places including users setups. The mitigation of this error is to wait till leader selection process is complete. 
In our tests this has been failing intermittently for different CP component ( i.e SR, Ksql ). This changes fixes the issue when we try to do some write operation when leader selection is in process. 
Fixes # ([ANSIENG-1162](https://confluentinc.atlassian.net/browse/ANSIENG-1162) …
=> Add retry to some tasks

roles/confluent.zookeeper/templates/zookeeper_log4j.properties.j2
Zookeeper server was not able to load the log Appender class due to trailing spaces in ap[pender class name.
Scenario `custom-user-plaintext-rhel` is runninng successul now
```
molecule verify -s custom-user-plaintext-rhel
control-center1            : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-connect1             : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-rest1                : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
ksql1                      : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
schema-registry1 …
```
=> Fixing zookeeper logs issue and yaml lint issues

roles/confluent.test/molecule/confluent-kafka-kerberos-customcerts-rhel/molecule.yml, roles/confluent.test/molecule/customcerts-rhel/molecule.yml, roles/confluent.test/molecule/kerberos-customcerts-rhel/molecule.yml, roles/confluent.test/molecule/kerberos-rhel/molecule.yml, roles/confluent.test/molecule/mtls-custombundle-rhel/molecule.yml, roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml, roles/confluent.test/molecule/plain-customcerts-rhel/molecule.yml, roles/confluent.test/molecule/rbac-kerberos-debian/molecule.yml, roles/confluent.test/molecule/rbac-mtls-provided-ubuntu/molecule.yml, roles/confluent.test/molecule/rbac-scram-custom-rhel/molecule.yml, roles/confluent.test/molecule/rbac-scram-provided-debian/molecule.yml, roles/confluent.test/molecule/zookeeper-kerberos/molecule.yml
As part of upgrade automation, we use the inventory file created by the molecule run of scenarios. These inventory files with all variables are based out of molecule.yml files. 
When upgrades are run with starting branches below 7xy and end branches above 7xy, we aren't able to resolve the correct location/path of the these variables, since there path have been hardcoded in molecule.yml files for starting branches. This PR aims to resolve the path from env variables. 
Fixes # (ANSIENG-1222)
https://jenkins.confluent.io/job/cp-ansible-on-demand/146/
=> Remove hardcoded path in molecule files

roles/confluent.test/molecule/mtls-custombundle-rhel/molecule.yml, roles/confluent.test/molecule/plaintext-basic-rhel/molecule.yml, roles/confluent.test/molecule/plaintext-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-kerberos-debian/molecule.yml, roles/confluent.test/molecule/rbac-mds-kerberos-mtls-custom-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-mtls-custom-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-plain-custom-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-scram-custom-rhel/molecule.yml
https://github.com/confluentinc/cp-ansible/pull/979
Similar to above PR. After pint merging the above PR, some new scenarios in 60x were left with these hardcoded path. Fixing those here
Fixes # (ANSIENG-1222)
=> Remove hardcoded path in molecule files 60x

roles/confluent.test/molecule/mtls-java11-rhel/molecule.yml
Since it's known that fips doesn't work with java11, this PR disables it for java11 related scenario. Has also been removed in later branches - https://github.com/confluentinc/cp-ansible/blob/6.1.x/roles/confluent.test/molecule/mtls-java11-rhel/molecule.yml#L100
=> Disable fips for java11 related scenario

roles/confluent.test/molecule/kafka-connect-replicator-mtls-scram-rhel/molecule.yml, roles/confluent.test/molecule/kafka-connect-replicator-plain-kerberos-rhel/molecule.yml, roles/confluent.test/molecule/provided-rhel/molecule.yml, roles/confluent.test/molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml
https://github.com/confluentinc/cp-ansible/pull/988
Similar to above PR. After pint merging the above PR on 60x to all downstream, some new scenarios in 61x were left with these hardcoded path. Fixing those 4 files here. 
Fixes # (ANSIENG-1222)
=> Remove hardcoded path in molecule files 61x

roles/confluent.ksql/tasks/main.yml, roles/confluent.ksql/tasks/register_cluster.yml, sample_inventories/rbac_mutiple_ksql.yml
Cluster registration against MDS is not working properly when multiple ksql clusters are defined in the inventory. The registration is done only once and for the first cluster sub-group, moreover it includes all the hosts of the other groups too.
I've tested this deploying against a group of VM's in GCP. With and without ksql subgroups. The relevant parts of the inventory files are these...
```yaml
ksql:
vars: 
ksql_cluster_name: ksql
hosts:
dfederico-demo-ksql-0:
dfederico-demo-ksql-1:
dfederico-demo-ksql-2:
``` 
Works as expected!
```
ksql_default:
vars:
ksql_cluster_name: ksql
ksql_service_id: default_
hosts:
dfederico-demo-ksql-0:
ksql_wraggle:
vars:
ksql_cluster_name: ksql-wraggle
ksql_service_id: wraggle-ksql_
hosts:
dfederico-demo-ksql-1:    
ksql_analytics:
vars: …
```
=> first fix registering multiple ksql with MDS

roles/confluent.ksql/tasks/register_cluster.yml
Fixing a conditional check in #1004 
Due to missing quotes, the conditional always evaluated to false due to which no ksql cluster was getting registered for any scenario. 
Tested locally
and here - https://jenkins.confluent.io/job/cp-ansible-on-demand/183/
=> Add quotes to fix the condition when registering ksql cluster

docs/VARIABLES.md, roles/kafka_broker/tasks/main.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
We have variable `kafka_broker` defined in vars as well as in default. Since vars has higher precedence then default, the resultant dictionary doesn't have any `properties` key. This causes the play to fail with error 
```
fatal: [zookeeper1]: FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ zookeeper_combined_properties | combine(zookeeper_custom_properties) }}: {{ zookeeper.properties }}: 'dict object' has no attribute 'properties'\n
```
Fixes #[RCCA-6061](https://confluentinc.atlassian.net/browse/RCCA-6061)
` ansible-playbook -i ../../hosts.ini ../../all.yml `
Since the user was trying out with ini file, we have verified with an ini file
Local environment
=> Remove conflicting properties

roles/confluent.ksql/templates/ksql-server_log4j.properties.j2
The log4j template does not prefix the service id.
=> log4j template does not prefix the ksql service id

roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
As JAAS Login Configuration files may contain secrets, they should be diffed - unless configured to do so. We discovered this when attempting to introduce digest authentication between zookeepers.
Not tested with this change, but it follows an established pattern for masking secrets in cp-ansible.
=> fix: no diff on JAAS login configuration files (may contain secrets)

roles/ksql/templates/ksql-server_log4j.properties.j2
ksqlDB property is defined [here](https://github.com/confluentinc/cp-ansible/blob/fa209b47eb0b2f4b3cd6642c183f1fec95d60680/roles/variables/vars/main.yml#L882) as  `ksql.logging.processing.topic.name: "{{ksql_service_id}}{{ksql_processing_log}}"` 
But log4j properties [here](https://github.com/confluentinc/cp-ansible/blob/fa209b47eb0b2f4b3cd6642c183f1fec95d60680/roles/ksql/templates/ksql-server_log4j.properties.j2#L52) is defined: `log4j.appender.kafka_appender.Topic={{ksql_processing_log}}`
These should be the same, based on https://docs.ksqldb.io/en/latest/reference/processing-log/#configuration-using-log4j
**Test …
=> fix(ksql): align processing log topic

roles/confluent.kafka_broker/tasks/main.yml
Ensure `kafka_server_jaas.conf` file is created when `zookeeper_client_authentication_type` is set to `kerberos` or `digest`.
Fixes #733 
Closes #733 
Tested on local development cluster.
```yaml
zookeeper_quorum_authentication_type: digest_over_tls
zookeeper_client_authentication_type: digest
```
Did not set `zookeeper_sasl_protocol`.
=> Create broker jaas file when client sasl authentication is enabled

playbooks/fetch_logs.yml
This PR will enable running fetch_logs playbook standalone. Earlier, it was failing due to undefined variables. 
This'll help us to collect all logs from all components using a single playbook.
To be used as: `ansible-playbook -i hosts.yml confluent.platform.fetch_logs`
Fixes # (ANSIENG-1311)
Tested locally. 
=> Enable running fetch logs playbooks standalone

plugins/filter/filters.py
CP-Ansbile 7.1 does support python2.7 This PR removes python 3 specific code from filters plugin. 
Verified with `rbac-mtls-rhel` molecule scenario
=> Make filter code python2 compatible

roles/common/tasks/host_validations.yml
This marks shell tasks as idempotent by adding `changed_when: false`. Using shell/command tasks in Ansible should be "last resort", and I think replacing these tasks with community.crypto module(s) would be nice. But it seems like there is a need to support pre-historical versions of Python/Ansible - at least for now.
I would also suggest to include the idempotence checks in our molecule tests, to avoid making these errors for the future. But that will slow down the slow CI build even more.....
Ran our playbook with this change in our local DEV environment.
=> Mark shell tasks as idempotent with changed_when: false

tasks/masterkey.yml
No tasks are run for masterkey tag if we follow the cp installation using tags as mentioned [here](https://docs.confluent.io/ansible/7.1.1/ansible-install.html)
To fix this and also to make it consistent with tasks in certificate_authority.yml, we need to add the tag. 
The tag based installation using masterkey is used 6.2.x onwards, but I've targeted it on 6.0.x to make it consistent with certificate_authority.yml
Fixes # (ANSIENG-1320)
Tested locally.
=> Add masterkey tags in masterkey.yml

docs/VARIABLES.md, roles/variables/defaults/main.yml
Change cli download condition to only rbac enabled.
Since 7.1 onwards, secrets protection enabled is only valid if rbac_enabled
Slack discussion - https://confluent.slack.com/archives/C020B5SDHB5/p1646731249453449?thread_ts=1646659961.309819&cid=C020B5SDHB5
Haven't tested.
=> Change cli download condition to only rbac enabled

molecule/rbac-mtls-rhel/verify.yml, roles/kafka_broker/tasks/set_principal.yml
To make filters work with collections and ansible 2.9, we need to prefix them with confluent.platform
Fixes # (ANSIENG-1334)
=> Prefix confluent.platform to filter resolve_principal

roles/confluent.test/molecule/mtls-custombundle-rhel/molecule.yml, roles/confluent.test/molecule/mtls-custombundle-rhel/verify.yml
This `mtls-custombundle-rhel` scenario was failing only on 6.0.x. It turned out that mutual auth doesn't work well with fips enabled. Same changes has been done on 6.1.x branches onwards.
`molecule converge -s mtls-custombundle-rhel`
`molecule verify -s mtls-custombundle-rhel`
=> Made parity with 6.1.x onwards branches to make mtls-custombundle

roles/kafka_broker/tasks/secrets_protection.yml
When secret protection is enabled, ansible playbook generates the master key and adds it to the systemd as an override, this requires systemd daemon to be reloaded for the changes to be picked up. 
Fixes # (ANSIENG-1327)
Doesn't break anything else - https://jenkins.confluent.io/job/cp-ansible-on-demand/229/
And verified by support team for their use case. 
=> Add daemon reload after secret protection related tasks

VARIABLES.md, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
I've added 2 new variables that lets you select an specific listener for Kafka Connect consumers and producers.
By default Connector producers and consumers are configured by cp-ansible to work against the Internal listener (9092). So all your connectors will use (e.g.) the `SASL_SSL` listener, but you might want to authenticate using mTLS, so you have an `SSL` listener. With this variables you can select the specific listener you want yo use for internal kafka connect clients.
I've made a preliminary version of this changes for a customer on site, which is now deployed and working as expected in different environments.
In this PR I've given better naming and the needed doc, not an extensive change
=> Allow selecting specific kafka listeners for Kafka Connect consumers and producers

molecule/custom-user-plaintext-rhel/molecule.yml, roles/kafka_broker/tasks/secrets_protection.yml
Custom user scenario was using a very old and deprecated key appender_log_dir, which is no more supported.
Successfully running with scenario `custom-user-plaintext-rhel`
=> Custom user log dir fix

VARIABLES.md, roles/confluent.common/tasks/main.yml, roles/confluent.kafka_broker/tasks/dynamic_groups.yml, roles/confluent.ssl/tasks/create_keystores_from_certs.yml, roles/confluent.ssl/tasks/import_ca_chain.yml, roles/confluent.test/molecule/mtls-custombundle-rhel/molecule.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml, roles/confluent.zookeeper/tasks/dynamic_groups.yml, tasks/upgrade_component_archive.yml, upgrade_control_center.yml, upgrade_kafka_broker.yml, upgrade_kafka_connect.yml, upgrade_kafka_rest.yml, upgrade_ksql.yml, upgrade_schema_registry.yml, upgrade_zookeeper.yml
This is a forward pint merge of changes we made in 6.0.x to properly deal the slashes `/` in path variables. We have unified the variables which were getting evaluated at multiple places, hence were creating a chance of error and ambiguity.
Tested Locally
archive-plain-rhel
archive-scram-rhel
mtls-custombundle-rhel
rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel
multi-ksql-connect-rhel
rbac-mds-kerberos-mtls-custom-rhel
Archive Custom Plain Rhel
https://jenkins.confluent.io/job/cp-ansible-on-demand/271/
Cloud Kafka rest
https://jenkins.confluent.io/job/cp-ansible-on-demand/272/
Kerberos customcerts rhel
https://jenkins.confluent.io/job/cp-ansible-on-demand/273/
mtls-customcerts-rhel
https://jenkins.confluent.io/job/cp-ansible-on-demand/276/
cp-kafka-plain-rhel …
=> 6.1.x pint

roles/kafka_broker/tasks/main.yml, roles/variables/vars/main.yml
dataDir under kafka properties has been obsolete way of providing the data directories. The recommended way is to use `log.dirs` key under `kafka_broker_custom_properties`
Local molecule scenario
=> Remove unused datadir variable

.bumpversion.cfg, docs/VARIABLES.md, roles/variables/defaults/main.yml
The description of `secrets_protection` feature was getting updated because of bumpversion regex match. updated the regex to match the filed which qualifies for version update. 
Local version update
=> Exclude the version from variable description

roles/confluent.kafka_broker/tasks/health_check.yml
Our code fell prey to an infamous ansible default behaviour - registering vars even for skipped tasks. 
Refer https://github.com/ansible/ansible/issues/17500 or https://github.com/ansible/ansible/issues/4297
The suggested solution is to use separate variables to register output of separate tasks. 
Fixes # https://github.com/confluentinc/cp-ansible/issues/954 and https://github.com/confluentinc/cp-ansible/issues/1041
Tested locally with the fix. 
=> use separate var to register output of each health check task

Jenkinsfile
Adding sanity test on the CI runs. To always be certification ready.
tested with cp-ansible-internal. We'll only know more once it's merged. 
=> add sanity test to ci builds

Jenkinsfile
Reverts confluentinc/cp-ansible#1079
If we see the latest run logs (https://jenkins.confluent.io/job/confluentinc/job/cp-ansible/job/7.0.x/508/console), we can see that the ansible-test sanity is reading some unexpected files like  /usr/local/lib/python3.9/site-packages/ansible_test/_data/sanity/pylint/config/collection.cfg and also throwing some new errors in the .py files (not visible on local - maybe because of the python version) 
Thus, reverting for now.
=> Revert "add sanity test to ci builds"

roles/variables/vars/main.yml
The ability to have a custom name for the Kafka Connect properties file is broken in 7.0.x after adding "community.general.path_join" to create the path.
The introduced bug is on roles/variables/vars/main.yml | kafka_connect>config_file ... the file name is hardcoded
`config_file: "{{ (config_base_path,'etc/kafka/connect-distributed.properties') | community.general.path_join }}"`
As an example, the line from 7.0.1-post looks like
`config_file: "{{ archive_config_base_path if installation_method == 'archive' else '' }}/etc/kafka/{{kafka_connect_config_filename}}"`
The missing part is in fact a reference to  `{{kafka_connect_config_filename}}`
Being consequent with the removal of 'archive_config_base_path' I've just changed the line to
`config_file: "{{ …
=> Fix ability to have custom filename for kafka connect config/properties

molecule/ksql-scale-up/converge.yml
The inventory file in this test has `ksql_advertised_listener_hostname: ksql2.confluent` . Updating the verify step accordingly.
Fixes # ([ANSIENG-1484](https://confluentinc.atlassian.net/browse/ANSIENG-1484))
Local verification 
` molecule converge -s ksql-scale-up`
```
control-center1            : ok=56   changed=4    unreachable=0    failed=0    skipped=53   rescued=0    ignored=0
kafka-broker1              : ok=53   changed=0    unreachable=0    failed=0    skipped=62   rescued=0    ignored=0
kafka-broker2              : ok=53   changed=0    unreachable=0    failed=0    skipped=59   rescued=0    ignored=0
kafka-broker3              : ok=53   changed=0    unreachable=0    failed=0    skipped=59   rescued=0 …
```
=> Fix ksql scale up test failures

roles/kafka_broker/tasks/main.yml, roles/kafka_broker/tasks/secrets_protection.yml
We were missing flushing the handlers after all secrets protections task. This fixes that. 
Fixes # (ANSIENG-1524)
(https://jenkins.confluent.io/job/cp-ansible-on-demand/378/)
=> Fix system restart after secret protection tasks

molecule/archive-plain-rhel/verify.yml
With #1091, default redactor being used with connect would remove the word being redacted, hence removing it from the verification stage.
Fixes # (weekly test failure)
Ran local verify
=> Remove component where redacted word unavailable

roles/variables/defaults/main.yml
Fixes failing weekly jobs cp-kafka-plain-rhel and confluent-kafka-kerberos-customcerts-rhel
Root cause - from 7.2 onwards, confluent community packages will fail if confluent metrics reporter is enabled. 
We have a flag `kafka_broker_metrics_reporter_enabled` controlling properties related to metric reporter.
If ccs used, this will be defaulting to false. If ce kafka used, this will check if control center is available or not. 
Locally.
=> Change condition for including metric reporter

docs/VARIABLES.md, molecule/archive-plain-debian/molecule.yml, molecule/archive-plain-debian/verify.yml, roles/common/tasks/confluent_cli.yml
We need to update the Confluent CLI client based on the variable `confluent_cli_version`. This change creates a new directory based on the cli version defined. The task gets skipped if the CLI of the given version is already present ( current behaviour )
Fixes # (ANSIENG-1532)
Verified the changes with molecule scenarios 
https://jenkins.confluent.io/job/cp-ansible-on-demand/389/
=> Update Confluent CLI based on provided version

roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml, tasks/reinstall_and_restart_components.yml, tasks/reinstall_components.yml, tasks/upgrade_component.yml, upgrade_kafka_broker.yml, upgrade_ksql.yml, upgrade_zookeeper.yml
Made changes for backup directory location and schema-registry plugins.
- changed backup directory from /tmp/upgrade to /opt/upgrade
- added confluent-schema-registry-plugins in the list of schema-registry plugins to be installed
- corrected filename for zookeeper_log4j.properties from /etc/kafka/zookeeper-log4j.properties to /etc/kafka/zookeeper_log4j.properties (issue was seen while upgrading soak cluster 1 from 7.1 build to 7.2 RC build)
Fixes #
https://confluentinc.atlassian.net/browse/QEC-7880
https://confluentinc.atlassian.net/browse/QEC-7879
=> Change backup directory location from /tmp

VARIABLES.md, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml, roles/variables/defaults/main.yml, roles/zookeeper/tasks/main.yml
cp-ansible creates a custom user for each component which owns the component service. 
This PR aims to introduce a default user login shell for all such created users. It'd be defaulting to /sbin/nologin coz we don't need these users to interactively login. 
This'll enhance security but the users will not be able to login. 
Fixes # (ANSIENG-1590)
Tested locally on a single scenario
https://jenkins.confluent.io/job/cp-ansible-on-demand/411/ for ALL scenarios.
=> Specify default value of user login shell

roles/ssl/tasks/custom_certs.yml
The string that we were searching for in the slurped private key content to evaluate whether it's encrypted or not is not deterministic. 
Based on some online references like [this](https://serverfault.com/questions/628921/how-do-i-know-if-pem-is-password-protected-using-ssh-keygen), there are some more deterministic ways to evaluate whether a key is encrypted or not. 
Searching for string 'ENCRYPTED' covers more use cases. 
A customer hit some issues due to the logic in the mentioned RCCA
RCCA-8063
=> Improve logic for identifying whether a custom key needs to be decrypted

roles/confluent.kafka_broker/tasks/set_principal.yml
https://github.com/confluentinc/cp-ansible/blob/7.1.1-post/roles/kafka_broker/tasks/set_principal.yml#L29-L30 
This statement fails for fips keystore (.bcfks) with the following error: 
`keytool error: java.io.IOException: Invalid keystore format
java.io.IOException: Invalid keystore format
at sun.security.provider.JavaKeyStore.engineLoad(JavaKeyStore.java:666)
at sun.security.provider.JavaKeyStore$JKS.engineLoad(JavaKeyStore.java:57)
at sun.security.provider.KeyStoreDelegator.engineLoad(KeyStoreDelegator.java:224)
at sun.security.provider.JavaKeyStore$DualFormatJKS.engineLoad(JavaKeyStore.java:71)
at java.security.KeyStore.load(KeyStore.java:1445)
at sun.security.tools.keytool.Main.doCommands(Main.java:839)
at sun.security.tools.keytool.Main.run(Main.java:380)
at …
=> Extract DNAME from BCFKS keystore

roles/confluent.variables/vars/main.yml
This PR aims to remove deprecated properties from Kafka Broker properties. RBAC related configs i.e. `confluent.metadata.server.token.auth.enable` and `confluent.metadata.server.public.key.path` are removed in this PR. 
Fixes # [ANSIENG-1600](https://confluentinc.atlassian.net/browse/ANSIENG-1600)
This was tested in cp-ansible-on-demand on all rbac scenarios. Here is the result [Test Report](https://jenkins.confluent.io/job/cp-ansible-on-demand/414/testReport/)
=> Remove Deprecated Properties from Kafka Broker

roles/zookeeper/tasks/main.yml
When we give variable `zookeeper_skip_restarts=true`, intent is to skip zookeeper restarts. And it happens that we don;t restart zookeeper in such case. But there is a message which gets printed that it's restarting zookeeper, which causes confusions. This fix is to suppress that false message in case of variable `zookeeper_skip_restarts` is given as true.
`ansible-playbook -i ~/.cache/molecule/platform/archive-plain-rhel/inventory confluent.platform.all --tags zookeeper --skip-tags "privileged,sysctl,filesystem,package,systemd,health_check" --limit zookeeper1 -e zookeeper_skip_restarts=true`
```
TASK [confluent.platform.zookeeper : Restart zookeeper] **********************************
Wednesday 07 September 2022  12:44:45 +0000 (0:00:01.363)       0:01:25.189 *** …
```
=> zookeeper_skip_restart prints message restarting zokeeper

roles/kafka_broker/tasks/health_check.yml
This PR aims to resolve rbac-mtls-rhel test failure. rbac-mtls-rhel was failing on branch 7.2.x due to a warning message in Health Check. This warning message was coming in the newer versions of Java.
Fixes # [ANSIENG-1572](https://confluentinc.atlassian.net/browse/ANSIENG-1572) 
rbac scenario has been tested locally and all scenarios were tested on cp-ansible-on-demand. These are the 2 jenkins jobs
[Test1](https://jenkins.confluent.io/job/cp-ansible-on-demand/461/) , [Test 2](https://jenkins.confluent.io/job/cp-ansible-on-demand/463/)
=> Resolve rbac-mtls-rhel Test Failure

roles/kafka_connect/tasks/main.yml, roles/kafka_connect/tasks/register_cluster.yml
Kafka Connect Cluster registration against MDS is not working properly when multiple kafka connect clusters are defined in the inventory (children). The registration is done only once and for the first cluster sub-group, moreover it includes all the hosts of the other groups too. I've followed the same approach of PR #991, with the addition of resolving the hostname using 'confluent.platform.resolve_hostname' in case 'hostname_aliasing_enabled: true' 
Using a connect an inventory with a kafka_connect similar to this one:
`
kafka_connect:
vars:
hostname_aliasing_enabled: true
children: 
connect-main:
vars:
kafka_connect_cluster_name: connect-main 
kafka_connect_group_id: connect-main
kafka_connect_service_name: connect-main
kafka_connect_config_filename: connect-main-distributed.properties …
=> Fixed Kafka Connect children registration with MDS

roles/kafka_connect/tasks/main.yml, roles/ssl/tasks/create_keystores_from_certs.yml, roles/variables/defaults/main.yml
When running multiple services in the same host, in particular for multiple connect workers, there is concurrency and race conditions can happen when manipulating the certificate files and keystores
(attaching picture of the error) 
Using the following host section example for sharing the host between connect services
`
all:
vars:
...
ssl_enabled: true
ssl_custom_certs: true
ssl_ca_cert_filepath: ~/inventories/gcp-sandbox/ssl/generated/CAcert.pem
ssl_signed_cert_filepath: ~/inventories/gcp-sandbox/ssl/generated/server.pem
ssl_key_filepath: ~/inventories/gcp-sandbox/ssl/generated/server-key.pem
regenerate_keystore_and_truststore: true
...
kafka_connect:
vars:
hostname_aliasing_enabled: true
children: 
connect-main:
vars:
kafka_connect_cluster_name: connect-main 
kafka_connect_group_id: …
=> Separate trustore/keystore creation for multple service in the same host

roles/common/tasks/host_validations.yml
SSL key file may be stored in ansible inventory as ansible-vault file.
In this case, check between key and certificate fails because shell task doesn't decrypt file
- set `ssl_custom_certs` true
- Store ssl key in a vault file
- set `ssl_key_filepath` to this file path
cp-ansible 7.2.1-post with 7.2 cluster : step doesn't fails anymore
=> accept ssl key file in ansible-vault format

roles/common/tasks/host_validations.yml
When broker server accesses internet thru a proxy, the step `Check Internet Access for Confluent Packages/Archive` fails, while the generated configuration is correct
just addind a "when" to set proxy n environment solves the issue
cp-ansible 7.2.1-post with 6.1 and 7.2 cluster : step doesn't fail anymore
=> Check Internet Access thru proxy if any

roles/confluent.common/defaults/main.yml, roles/confluent.common/tasks/debian.yml
This PR aims to provide a custom variable for adding Sid Repo. The default value for add_sid_repo is false. This change would stabilize Java 11 installation on Debian 10 
Fixes # [ANSIENG-1650](https://confluentinc.atlassian.net/browse/ANSIENG-1650)
I have tested both locally and on jenkins for all debian scenarios. The changes have been made on base 6.1.x Here are the test Results [test1](https://jenkins.confluent.io/job/cp-ansible-on-demand/480/) [test2](https://jenkins.confluent.io/job/cp-ansible-on-demand/481/) 
=> Add Sid Repo variable for Debain 10

docs/VARIABLES.md, roles/kafka_broker/tasks/set_principal.yml, roles/ssl/tasks/create_keystores_from_certs.yml, roles/ssl/tasks/import_ca_chain.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
The community.general was used in cp-ansible to support 2.9 since path_join filter was introduced from 2.10 onwards. 
Since cp-ansible 7.2 and up don't support 2.9 anymore, we are deprecating the use of community.general 
Fixes # (ANSIENG-1589)
https://jenkins.confluent.io/job/cp-ansible-on-demand/508/testReport/
In above test, mtls-custombundle-rhel and connect-scale-up, both are unrelated failure
=> Deprecate community.general

roles/confluent.kafka_broker/tasks/rbac.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ssl/tasks/export_certs_from_keystore_and_truststore.yml, roles/confluent.ssl/tasks/main.yml, tasks/rbac_setup.yml
The inventory file generated from ansible takeover will assume all existing clusters to be a case where keystores and truststores and mds-pem files will already be present on the host nodes. 
If the playbook is then run with the generated inventory file, some mandatory steps might get skipped and some unneeded ones might get executed and error out. This PR fixes those problems. 
https://jenkins.confluent.io/job/cp-ansible-on-demand/473/
With the latest changes - https://jenkins.confluent.io/job/cp-ansible-on-demand/511/
=> Make ansible takeover work for 6x

roles/common/tasks/host_validations.yml
Fix zookeeper ssl test failure in mtls-custombundle-rhel on 7.2.x
Fixes # [ANSIENG-1677](https://confluentinc.atlassian.net/browse/ANSIENG-1677)
tested on jenkins job using 7.2.2 confluent package version [Result](https://jenkins.confluent.io/job/cp-ansible-on-demand/517/)
=> Fix Zookeeper ssl Test failure on 7.2.x

docs/VARIABLES.md, roles/common/tasks/fetch_logs.yml, roles/variables/defaults/main.yml
adding the ability to control the path of the on controlled nodes logs fetching directory, currently set to `/tmp`
=> Fetch logs path added as var 

docs/HOW_TO_TEST.md, roles/common/tasks/main.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_broker/tasks/rbac.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml, roles/zookeeper/tasks/main.yml
This PR fixes couple of problems working with Ansible 2.13 -
1. `ansible_ssh_host` being undefined in ansible 2.13
2. Templating issue in rbac.yml while appending items to list
3. There's recent issue with molecule-docker 2.1.0 latest version, Added a note in HOW_TO_TEST.md for the same
This PR should now support both Ansible 2.13 and 2.12 versions.
**Note:** Jenkins on demand job has been updated to accept ansible version as configurable parameter. 
Fixes # 
https://confluentinc.atlassian.net/browse/ANSIENG-1556
All rbac scenarios were run and tested on all three ansible versions 2.11, 2.12, 2.13
=> Support for Ansible 2.13

roles/variables/defaults/main.yml
https://github.com/confluentinc/packaging/pull/1018 - After we raised a question about pinned cli version for cp 7.3, this PR was raised. Hence, we're now updating default cli version to 2.28.1
Another relevant PR - https://github.com/confluentinc/muckrake/pull/1841
https://jenkins.confluent.io/job/cp-ansible-on-demand/589/
Ran all rbac scenarios which has confluent cli enabled
=> Update cli version to 2.28.1 from 2.19

VARIABLES.md, roles/confluent.kafka_broker/tasks/rbac.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.variables/defaults/main.yml, tasks/rbac_setup.yml, tasks/secrets_protection.yml
For all places where we are delegating to localhost to read/check a file (anything to do with a file), it looks for root permission on the controller node (which might not be required)
This causes issues when user doesn't have root permissions when running the playbooks.
Hence, we are explicitly setting ansible_become to false for such tasks (using a new var - ansible_become_localhost) 
Fixes # (ANSIENG-1801)
All pass
https://jenkins.confluent.io/job/cp-ansible-on-demand/597/
=> Set ansible_become to false when delegating to localhost

roles/ssl/tasks/custom_certs.yml, roles/ssl/tasks/self_signed_certs.yml
Reimplemented #934 - Improve internal handling of SSL certificates. 
This change was reverted earlier as it used the community.crypto collection not supported in older versions of python and ansible. 
Now that we are supporting ansi 2.11, 2.12, 2.13 versions & python 3.6+, bring these changes back and would be testing rbac, ssl scenarios.
Fixes # 
https://confluentinc.atlassian.net/browse/ANSIENG-1318
Have been verifying changes by running cp-ansible-on-demand jobs for mtls + rbac scenarios -
https://jenkins.confluent.io/job/cp-ansible-on-demand/592/ (ansible 2.13)
https://jenkins.confluent.io/job/cp-ansible-on-demand/594/ (ansible 2.12)
https://jenkins.confluent.io/job/cp-ansible-on-demand/593/ (ansible 2.11)
=> Reimplement #934 - Improve internal handling of SSL certificates

molecule/plaintext-rhel/verify.yml, playbooks/restart.yml
This PR aims to provide the feature to restart services manually via cp-ansible. A new playbook has been added for that purpose. This issue was raised in [721](https://github.com/confluentinc/cp-ansible/issues/721) and [806](https://github.com/confluentinc/cp-ansible/issues/806)
Fixes # [ANSIENG-1517](https://confluentinc.atlassian.net/browse/ANSIENG-1517)
Tested the playbook locally to check if the deployed components are able to restart and also on the scenario plaintext-rhel [here](https://jenkins.confluent.io/job/cp-ansible-on-demand/600/)
=> Add playbook to force service restart manually

roles/confluent.variables/vars/main.yml
Removing some unused properties. Replacing these confluent.ssl.* with ssl.* props also worked fine. 
Fixes # ([issue](https://github.com/confluentinc/cp-ansible/issues/1193))
https://jenkins.confluent.io/job/cp-ansible-on-demand/605/testReport/
Tested all scenarios on 6.0.x - nothing breaks after removing these properties
Will test on 7.3.x too to be more sure.
=> Remove unused confluent.ssl.* prop

docs/hosts_example.yml, roles/common/tasks/host_validations.yml, roles/common/templates/confluent.repo.j2
https://confluentinc.atlassian.net/browse/ANSIENG-1515
Supports both https_proxy and http_proxy for yum repo
Fixes 
Github issue #891
This was tested by spinning up a fresh redhat EC2 instance, and running playbook with above fix.
/etc/yum.repos.d/confluent.repo will now appropriately set proxy using fall back chain from https -> http-> none.
https://jenkins.confluent.io/job/cp-ansible-on-demand/652/
=> GH issue #891 Fix proxy settings for yum repo

roles/confluent.variables/vars/main.yml
After removal of unused confluent.ssl.* props, we explored the ssl.* properties
https://docs.confluent.io/platform/current/kafka/encryption.html#brokers talks about the usage of ssl.* properties for broker
https://docs.confluent.io/platform/current/installation/configuration/broker-configs.html#ak-broker-configurations-for-cp
The enable condition for these properties have been kept the same as ssl role for kafka brokers, which'll ensure that these properties show up only and whenever required.
Fixes # (ANSIENG-1826)
On 6.0.x - https://jenkins.confluent.io/job/cp-ansible-on-demand/665/
On 7.3.x - https://jenkins.confluent.io/job/cp-ansible-on-demand/662/
=> Add ssl.* props for kafka broker

molecule/mtls-customcerts-rhel/molecule.yml, roles/common/tasks/debian.yml, roles/common/tasks/redhat.yml, roles/common/tasks/ubuntu.yml
Installing pip and cryptography on managed nodes via playbooks itself. This is needed for ansible community.crypto module to work.
Fixes # 
Background - https://github.com/confluentinc/cp-ansible/pull/1214
Created custom docker image wadhwa1/docker-centos7:v2 so as to first reproduce the cp-env issue via molecule tests and make our tests fail.
Verified via cp-ansible-ondemand-job (Test failed as expected) https://jenkins.confluent.io/job/cp-ansible-on-demand/656/testReport/molecule.mtls-customcerts-rhel.molecule/yml/test/
After fix, here are on demand job run- https://jenkins.confluent.io/job/cp-ansible-on-demand/660/
=> Install pip and cryptography on managed nodes for community.crypto module

roles/variables/vars/main.yml
Earlier [PR](https://github.com/confluentinc/cp-ansible/pull/1221) had fixed the issue https://confluentinc.atlassian.net/browse/ANSIENG-1764 schema registry url being wrongly generated
`confluent.controlcenter.schema.registry.url = [http://:8081]`
but it broke few molecule scenarios.
Raising another PR, have tested this fix with both - 
- Executing ansible playbook with manually generated inventory.yml file
- All failed molecule scenarios are passing now https://jenkins.confluent.io/job/cp-ansible-on-demand/679/
https://confluentinc.atlassian.net/browse/ANSIENG-1764
https://jenkins.confluent.io/job/cp-ansible-on-demand/679/
=> Fix schema registry url

roles/common/tasks/debian.yml, roles/common/tasks/redhat.yml, roles/common/tasks/ubuntu.yml
We always run plays in check mode against our first environment (dev) on feature branches. We just tried out the recent 7.3.0-post branch, and check mode is currently borked with the following error:
````
TASK [confluent.platform.common : Print Java Version] **************************
fatal: [REDACTED]: FAILED! => 
msg: |-
The task includes an option with an undefined variable. The error was: list object has no element 0
The error appears to be in '/home/ansible/.ansible/collections/ansible_collections/confluent/platform/roles/common/tasks/redhat.yml': line 64, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: Print Java Version
^ here
````
Intentionally targeting the release branch (7.3.0-post). …
=> fix: support running plays in check mode

roles/control_center/tasks/main.yml
Gh issue 633 remove unnecessary permissions. https://github.com/confluentinc/cp-ansible/issues/633
removed unnecessary block to add permissions
custom-user-plaintext-rhel scenario
=> removed unneccesary block to add permisisons

roles/common/tasks/debian.yml, roles/common/tasks/redhat.yml, roles/common/tasks/ubuntu.yml
Make pip install and upgrade pip tasks skippable with `tags: package` 
[ANSIENG-1953](https://confluentinc.atlassian.net/browse/ANSIENG-1953)
=> Make pip install and upgrade tasks skippable

roles/confluent.variables/vars/main.yml
https://github.com/confluentinc/cp-ansible/issues/1243
For upgrades with archive installation, zookeeper_health_check was failing when being called in dynamic_groups.yml
In our code, zookeeper_health_check var was resolving with the incorrect/target version, while it should be resolving with starting version (because the tasks in dynamic_groups.yml file are pre-upgrade)
Similar issue for kafka_broker
Fixing base_path and binary_base_path utilises the var archive_version which is set here - https://github.com/confluentinc/cp-ansible/blob/6.2.7-post/roles/confluent.zookeeper/tasks/dynamic_groups.yml#L31 by slurping the properties file
Fixes # ([issue](https://confluentinc.atlassian.net/browse/ANSIENG-1943))
Tested archive-plain-rhel locally.
Tested manual upgrade of both zookeeper and kafka …
=> Fix upgrades for archive installation

docs/MOLECULE_SCENARIOS.md, docs/molecule_doc.py
We've been using os.listdir to generate list of molecule scenarios and then we use that list to build molecule doc file. 
os.listdir return a list containing the names of the entries in the directory given by path but the list is in arbitrary order. [Ref](https://docs.python.org/3/library/os.html#os.listdir)
Hence, everytime we run molecule_doc.py, we get huge changes. 
Trying to fix this henceforth by sorting
Locally
=> Fix order of scenarios in molecule doc

roles/kafka_broker/tasks/main.yml
While updating my own cp-ansible hosts file to upgrade from 6 to 7, I came across this message in during execution:
```
Providing 'datadir' in inventory file is no more supported way to configure data directories for kafka brokers.
```
I am suggesting improving the language to be more clear:
```
The 'datadir' configuration property is now obsolete for configuration of kafka broker data directories.
```
N/A - this is a simple update to a string
**Test Configuration**: N/A
=> update 'logdirs' failure message for clarity

roles/confluent.variables/vars/main.yml
Addresses - https://github.com/confluentinc/cp-ansible/issues/1298
If multiple connect clusters want different config file, we need a variable to define it separately.
PR CI tests - just need to test if connect starts up successfully
=> get connect config file from var

hosts_example.yml, molecule/kerberos-rhel/molecule.yml, molecule/rbac-kerberos-debian/molecule.yml, molecule/rbac-kerberos-debian/prepare.yml, molecule_doc.py, molecule_scenarios.md, playbooks/fetch_logs.yml, playbooks/health_check.yml, roles/control_center/defaults/main.yml, roles/kafka_broker/defaults/main.yml, roles/kafka_broker/tasks/health_check.yml, roles/kafka_connect/defaults/main.yml, roles/kafka_connect_replicator/defaults/main.yml, roles/kafka_rest/defaults/main.yml, roles/kerberos/tasks/main.yml, roles/ksql/defaults/main.yml, roles/schema_registry/defaults/main.yml, roles/variables/defaults/main.yml, roles/zookeeper/defaults/main.yml, test_roles/confluent.test.kerberos/defaults/main.yml
This PR enhances our security configurations.
It allows customer to specify custom location of their kerberos client configuration file for both cases (where they want cp-ansible to configure the file and where they want to configure the file themselves) 
We use a variable kerberos_client_config_file_dest for the same. This custom path needs to be specified as java arg for each of our services.
Tests have been added for both cases:
custom location with cp-ansible confguring the file
custom location with customer configuring and providing the file
The change requires public facing doc change - will open a ticket after approval
Fixes # (ANSIENG-1964)
https://jenkins.confluent.io/job/cp-ansible-on-demand/966/
One failing fixed in - https://jenkins.confluent.io/job/cp-ansible-on-demand/967/ …
=> Support custom kerberos client config file and custom path

roles/kafka_broker/templates/kafka.yml.j2
See also: https://github.com/confluentinc/jmx-monitoring-stacks/pull/96
Has four changes:
* Move the more-specific rule containing `type,name,clientId,topic,partition` ABOVE less-specific rule containing `type,name,topic,partition` so that clientId is properly parsed as a separate capture group (rather than as part of the name). This initially resulted in the 'name' capture group looking something like this: `ConsumerLag, clientId=ReplicaFetcherThread-0-103-Default`
* Creates a duplicate of the rule capturing `type, name, clientId, brokerHost, brokerPort`, but with a Count instead of Value
* Create two additional rules capturing arbitrary key-value pairs when there are 6 and 5 arbitrary pairs (in front of the rule capturing 4 arbitrary pairs
Please include a summary of the change and …
=> Fix JMX Exporter Rules

docs/hosts_example.yml, docs/sample_inventories/kraft_controller.yml, roles/common/tasks/main.yml
This PR aims to Add sample kraft inventory and failure task when both zookeeper and controller present
Fixes # [ANSIENG-1999](https://confluentinc.atlassian.net/browse/ANSIENG-1999)
Tested locally
[ANSIENG-1999]: https://confluentinc.atlassian.net/browse/ANSIENG-1999?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add sample kraft inventory and failure task when both zookeeper and controller present

roles/confluent.ssl/tasks/export_certs_from_keystore_and_truststore.yml, roles/confluent.ssl/tasks/main.yml, roles/confluent.test/molecule/rbac-mtls-provided-ubuntu/molecule.yml
`Export Certs from Keystore and Truststore` happening twice in some cases and second one fails with error - 
“Can’t open /var/ssl/private/generation/zookeeper.p12 for reading, No such file or directory”
PR aims to rectify above issue.
https://confluentinc.atlassian.net/browse/ANSIENG-2023
Modified one of the molecule scenarios to test this, as you can see in the screenshot, first `Export Certs from Keystore and Truststore` task passed through and second one got skipped.
https://jenkins.confluent.io/job/cp-ansible-on-demand/991/
https://jenkins.confluent.io/job/cp-ansible-on-demand/990/
=> ANSIENG-2023 Fix export certificate logic

roles/confluent.kafka_broker/templates/kafka.yml.j2
Cherry-picking https://github.com/confluentinc/cp-ansible/pull/1304 into 6.1.x
For pint purposes: note that this has already been merged into 7.3.x
See also: https://github.com/confluentinc/jmx-monitoring-stacks/pull/96
Has four changes:
* Move the more-specific rule containing `type,name,clientId,topic,partition` ABOVE less-specific rule containing `type,name,topic,partition` so that clientId is properly parsed as a separate capture group (rather than as part of the name). This initially resulted in the 'name' capture group looking something like this: `ConsumerLag, clientId=ReplicaFetcherThread-0-103-Default`
* Creates a duplicate of the rule capturing `type, name, clientId, brokerHost, brokerPort`, but with a Count instead of Value
* Create two additional rules capturing arbitrary …
=> Fix JMX Exporter Rules (6.1.x)

HOW_TO_TEST.md, molecule/archive-plain-rhel/verify.yml, molecule/multi-ksql-connect-rhel/molecule.yml, molecule/plain-rhel/verify.yml, plugins/modules/kafka_connectors.py, test_roles/confluent.test/tasks/check_connector.yml
- Improve error handling while deploying connectors (Based on previous PR - https://github.com/confluentinc/cp-ansible/pull/490 + added error handling in create_new_connector)
- Fix kafka_connectors module to support ssl_enabled=true
- Updated molecule scenarios to test above - error handling of module + deploying connectors with ssl_enabled=true
GH #401  
https://jenkins.confluent.io/job/cp-ansible-on-demand/996/
=> ANSIENG-1990 Improve error handling deploying connectors

discovery/manager/manager.py, discovery/utils/utils.py
Multiple changes:
- Ansible runner by default dumps the entire output of the ansible task onto stdout, which is very overwhelming. Preventing that.
- Default logging level was bugged. It defaulted to CRITICAL, which has been fixed to INFO.
- Fix the logic to have all variables supported both as part of input file as well as command line arguments. Variables can be passed from either of these two places (cl arguments having higher priority)
- The CLI args which were given any default value (other than None) always override no matter what was supplied in the input file. For ex, ansible_python_intepretor even if supplied in input file was always overriden by the default value of CLI arg, which was 'auto'. Now, we want to assign default value to var if it's not present in both input file and …
=> Fix logic related to input file/cli args, fix logging

roles/common/handlers/main.yml, roles/common/tasks/debian.yml, roles/common/tasks/redhat.yml
Command warnings feature has been deprecated, setting warn=false is resulting into an error in latest ansible-core 2.14.
reference - https://github.com/ansible/ansible/pull/70504
https://jenkins.confluent.io/job/cp-ansible-on-demand/1019/testReport/junit/molecule.plain-rhel.molecule/yml/test/
Initially, running playbook against ansi-core 2.14 resulted into error ☝️ 
After fixing, ran few scenarios against both ansi versions - 2.13 and 2.14
https://jenkins.confluent.io/job/cp-ansible-on-demand/1022/ ✅ 
https://jenkins.confluent.io/job/cp-ansible-on-demand/1028/ ✅ 
=> Remove command warnings to support latest ansible

molecule/archive-plain-rhel/molecule.yml, molecule/archive-plain-rhel/verify.yml, molecule/mtls-java11-rhel/verify.yml
Tweaked couple of molecule scenarios to check FIPS support for both RHEL7 and RHEL8, seems to work fine. 
https://jenkins.confluent.io/job/cp-ansible-on-demand/1077/ 🟢 
=> Test FIPS support on rhel7 and rhel8

roles/kafka_connect/tasks/confluent_hub.yml
This PR allows the playbook to only install the connect plugins that are either absent, or do not match the requested version.
This code change has been tested against my sandbox environment, and functions as expected with both new plugins, and installed plugin versions that do not match the required version.
=> Only install/update appropriate connect plugins

docs/VARIABLES.md, molecule/rbac-kerberos-debian/molecule.yml, molecule/rbac-mds-kerberos-debian/molecule.yml, roles/kerberos/defaults/main.yml, roles/kerberos/templates/krb5.conf.j2, roles/variables/defaults/main.yml
https://confluentinc.atlassian.net/browse/ANSIENG-2056
Context on what the variable does - https://web.mit.edu/kerberos/krb5-1.12/doc/admin/conf_files/krb5_conf.html#libdefaults
Default value is set to false
Context on why we need to expose this var - https://confluentinc.atlassian.net/browse/FF-9024
Target branch is kept to 7.3.x since we started supporting java17 from 7.3
https://jenkins.confluent.io/job/cp-ansible-on-demand/1097/
https://jenkins.confluent.io/job/cp-ansible-on-demand/1096/
=> Enable allow_weak_crypto as a kerberos setting

roles/confluent.variables/vars/main.yml
Reverts confluentinc/cp-ansible#1208
It's a miss. Recently found in oncall that these props are required. 
Our existing tests didn't catch this even though being very similar to the customer's env. So, can't add any other tests.
Customer can be unblocked by mentioning these props in kafka_broker_custom_properties for now.
=> Revert "Remove unused confluent.ssl.* prop"

docs/VARIABLES.md, roles/common/defaults/main.yml, roles/variables/defaults/main.yml
Bumping up pinned cli version for cp 7.4 from 2.28.1 to 3.2.1
Reference thread - https://confluent.slack.com/archives/C010Y0EP5MZ/p1675164016491029
Another related PR - https://github.com/confluentinc/packaging/pull/1049
https://jenkins.confluent.io/job/cp-ansible-on-demand/1130/ ✅ 
=> Bump CLI to v3.2.1

roles/kafka_connect/tasks/zos_connect_plugins.yml
Modify the step to copy over .jars to each connector's lib directory.
Instead we copy these jars just once to the java ext directory.
The LIBPATH environment variable points to the native libraries.
=> Copy only MQ jars to ext folder to be loaded by the extension classloader

VARIABLES.md, roles/variables/defaults/main.yml
As requested in [on-call issue](https://confluent.slack.com/archives/CMTBL483Y/p1677186314680819), one of the customers was looking to customize the timestamps topic used by replicator (__consumer_timestamps). However, Kafka (base feature) itself doesn't support this. To avoid confusion, we are removing it from VARIABLES.md
=> kafka_connect_replicator_consumer_timestamps_topic is not configurable

molecule/archive-plain-debian/molecule.yml, roles/common/defaults/main.yml
Users experiencing issues with downloading confluent CLI v3 because - 
for CLI v3 and above, archive name is somewhat different - confluent_v3.2.1_linux_amd64.tar.gz should become confluent_3.2.1_linux_amd64.tar.gz (remove leading ‘v’)
PR is to fix above problem.
Before - https://jenkins.confluent.io/job/cp-ansible-on-demand/1216/ 🔴 failed, Failure downloading https://s3-us-west-2.amazonaws.com/confluent.cloud/confluent-cli/archives/3.2.1/confluent_v3.2.1_linux_amd64.tar.gz, HTTP Error 404: Not Found
After fix - https://jenkins.confluent.io/job/cp-ansible-on-demand/1217/ 🟢 passed
=> Fix errors downloading confluent CLI v3

roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/health_check.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml
With version 3 of the CLI confluent secrets command, the RBAC login requirement was removed. The playbooks have not been updated to reflect this change and secrets management is getting disabled.
Fixes issues https://confluent.slack.com/archives/CM80GTNUQ/p1656981267820799
These changes have been tested against EC2 instances running in AWS on a n mTLS non RBAC cluster with secret management and health checks enabled.
=> Don't require RBAC for confluent secret v3

docs/VARIABLES.md, roles/kerberos/templates/krb5.conf.j2
As described in https://github.com/confluentinc/cp-ansible/issues/1371
Added variables for kerberos port(s) with defaults for the currently hard-coded values in krb5.conf.j2 to allow installation e.g. in cloud-hosted MS AD setups.
Fixes #1371 
* Local testing of template in ansible
* Integration - full deployment in target system with modified template
- fallback / defaults: 
```bash
ansible all -i "localhost," -c local -m template -a "src=./roles/kerberos/templates/krb5.conf.j2 dest=./test.txt" --extra-vars='{kerberos: {realm: TEST.REALM, dns_lookup_realm: test.realm, dns_lookup_kdc: test.kdc, ticket_lifetime: 42, forwardable: false, udp_preference_limit: 4242, default_tkt_enctypes: aes256-cts-hmac-sha1-96 aes128-cts-hmac-sha1-96, default_tgs_enctypes: default, …
```
=> Added ports for kerberos template with defaults

roles/kafka_connect/tasks/health_check.yml, roles/kafka_connect_replicator/tasks/health_check.yml, roles/kafka_rest/tasks/health_check.yml, roles/ksql/tasks/health_check.yml, roles/schema_registry/tasks/health_check.yml
In some cases deploying cp with mTLS, `Wait for API to return 200 - mTLS` tasks fail if you provide providing a full chain in the inventory (custom certs) due to incorrect extracted server certificate. 
```yml
- name: Extract Final Cert from Signed Cert Chain
shell: |
tac {{ ssl_file_dir_final }}/{{service_name}}.chain | awk '!flag; /-----BEGIN CERTIFICATE-----/{flag = 1};' | tac > {{cert_path}}
diff: "{{ not mask_sensitive_diff|bool }}"
```
The  `Extract Final Cert from Signed Cert Chain` task above can extract the CA (or the intermediate) instead of the server certificate since the extraction depends on the order of the certificates in the bundle, **the server certificate is always expected to be the last**, which is not always the case. If that happens the health check fails.
This was …
=> Fixing mTLS healthcheck extracting wrong certificate when providing a full chain bundle

molecule/rbac-mtls-rhel/verify.yml, plugins/filter/filters.py
Fixed below issues
- `RULE:pattern/replacement/[LU],DEFAULT` - was resulting into error
- Fixed - Support for comma separated mapping rules RULE:pattern1/replacement/[LU],RULE:pattern2/replacement/[LU]
- Fixed - First matching rule should get applied, and rest of the list should be ignored
Added few assertions to test above fixes in molecule verify
https://jenkins.confluent.io/job/cp-ansible-on-demand/1251/
=> SSL principal mapping rule fixes

docs/VARIABLES.md, playbooks/tasks/certificate_authority.yml, roles/ssl/defaults/main.yml, roles/variables/defaults/main.yml
1. Currently, hard code with [the number of days from Certificate Authority creation to expiration](https://github.com/confluentinc/cp-ansible/blob/7.3.4-post/playbooks/tasks/certificate_authority.yml#L103)
2. No keystore_expiration_days variable in docs VARIABLES.md for guideline.
1. Run ansible playbook to generate the certificate authority (CA)
2. Check expiration days of certificate authority (CA) with `openssl x509 -enddate -noout -in ca.crt`
=> Add variable to customize the number of days from Certificate Authority creation to expiration

discovery/manager/manager.py, discovery/utils/utils.py
Fixes minor bugs in discovery. 
1. the regex pattern to get environment variables was giving wrong output for the last variable in the variables list
2. the path to get config files was absolute and hence, the code was throwing utils - ERROR - Cannot find config file zookeeper.yml. Returning an empty config.   and adding unnecessary properties in the inventory file
Fixes # [ANSIENG-2280](https://confluentinc.atlassian.net/browse/ANSIENG-2280)
tested locally 
[ANSIENG-2280]: https://confluentinc.atlassian.net/browse/ANSIENG-2280?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix bugs in discovery 

molecule/Dockerfile-debian-archive.j2, molecule/Dockerfile-debian-java8.j2, molecule/Dockerfile-debian.j2, roles/common/tasks/debian.yml
- debian9 has been moved to archived status because of which few of our molecule tests started failing across 7.0.x to master branches
- Updated dockerfiles to point to archive repo url
Failing weekly tests - https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.0.x/131/testReport/
Re-ran failing tests https://jenkins.confluent.io/job/cp-ansible-on-demand/1275/, they are all passing now
=> Switch to archive repo for debian9

discovery/README.md, discovery/manager/manager.py, discovery/service/kafka_broker.py, discovery/service/service.py, discovery/system/system.py, discovery/utils/utils.py
Ansible Runner APIs truncates larger string of service environment variable. As a result we have been seeing [unprintable] while trying to discover jolokia and jmx properties. This change now directly reads from the service and override files and creates environment variable map. 
Tested on molecule scenarios with Jolokia and Prometheus enabled. 
=> Fix service environment issue

roles/kafka_broker/tasks/set_controller_principal.yml
This PR aims to add each broker's principal to Controller's super users list on RBAC cluster with mTLS
Fixes # [ANSIENG-2385](https://confluentinc.atlassian.net/browse/ANSIENG-2385)
tested locally
[ANSIENG-2385]: https://confluentinc.atlassian.net/browse/ANSIENG-2385?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add each broker's principal in Controller's super user list

docs/sample_inventories/rbac_sso_c3.yml, plugins/filter/filters.py
This PR adds principal builder for Kafka when OIDC is enabled
Fixes # [ANSIENG-2500](https://confluentinc.atlassian.net/browse/ANSIENG-2500)
[ANSIENG-2500]: https://confluentinc.atlassian.net/browse/ANSIENG-2500?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Confluent Kafka Principal Builder when OIDC is enabled

VARIABLES.md, hosts_example.yml, molecule_scenarios.md, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.test/molecule/zookeeper-digest-mtls-secrets-rhel/molecule.yml, roles/confluent.test/molecule/zookeeper-digest-mtls-secrets-rhel/verify.yml, roles/confluent.test/molecule/zookeeper-digest-rhel/molecule.yml, roles/confluent.test/molecule/zookeeper-kerberos-rhel/molecule.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml
Server - Server authentication via kerberos is not supported in cp. Hence the value of variable for server to server authentication should also not be 'kerberos' as it might be misleading.  Also updated molecule scenarios to remove use of depricated variable zookeeper_sasl_protocol
Fixes # [ANSIENG-2480](https://confluentinc.atlassian.net/browse/ANSIENG-2480)
several jenkins scenarios with different types of auth mechanisms.
[ANSIENG-2480]: https://confluentinc.atlassian.net/browse/ANSIENG-2480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> removed server-server kerberos auth and updated molecule scenarios to remove depricated variable

MOLECULE_SCENARIOS.md, VARIABLES.md, hosts_example.yml, molecule/zookeeper-digest-mtls-secrets-rhel/molecule.yml, molecule/zookeeper-digest-mtls-secrets-rhel/verify.yml, molecule/zookeeper-digest-rhel/molecule.yml, molecule/zookeeper-kerberos-rhel/molecule.yml, roles/kafka_broker/tasks/main.yml, roles/variables/defaults/main.yml, roles/zookeeper/defaults/main.yml, roles/zookeeper/tasks/main.yml
Pint merge to push the fix to newer branches
Server - Server authentication via kerberos is not supported in cp. Hence the value of variable for server to server authentication should also not be 'kerberos' as it might be misleading.  Also updated molecule scenarios to remove use of depricated variable zookeeper_sasl_protocol
Fixes # [ANSIENG-2480](https://confluentinc.atlassian.net/browse/ANSIENG-2480)
several jenkins scenarios with different types of auth mechanisms.
[ANSIENG-2480]: https://confluentinc.atlassian.net/browse/ANSIENG-2480?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Pint resolve 7.0.x

Jenkinsfile
Updating Jenkins to use rbac-mtls-rhel8 for PR checks, instead of rbac-scram-custom-rhel since rbac-scram-custom-rhel has been changed to rbac-scram-custom-rhel-fips, a fips enabled scenario. 
=> Update Jenkins test scenario

molecule/Dockerfile-rhel9-java11.j2, plugins/filter/filters.py, roles/variables/vars/main.yml
this PR aims to add TLSv1.3 in FIPS Enabled clusters. Both TLSv1.2 and TLSv1.3 are now supported.
Fixes # [ANSIENG-2524](https://confluentinc.atlassian.net/browse/ANSIENG-2524)
[jenkins job](https://jenkins.confluent.io/job/cp-ansible-on-demand/1681/)
[ANSIENG-2524]: https://confluentinc.atlassian.net/browse/ANSIENG-2524?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add TLSv1.3 support for FIPS

roles/confluent.test/molecule/mtls-ubuntu-acl/molecule.yml, roles/confluent.test/molecule/mtls-ubuntu-acl/verify.yml
added test for kafka ACL. removed super.users from the test since it defeats the purpose of ACL
Fixes # [ANSIENG-2551](https://confluentinc.atlassian.net/browse/ANSIENG-2551)
https://jenkins.confluent.io/job/cp-ansible-on-demand/1727/
[ANSIENG-2551]: https://confluentinc.atlassian.net/browse/ANSIENG-2551?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add test for Apache kafka ACL

molecule/rbac-mds-kerberos-debian/molecule.yml, molecule/rbac-mds-plain-custom-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml, molecule/rbac-scram-custom-rhel-fips/molecule.yml
SSO credentials need to be stored in vault. Our molecule tests would then use these variables via jenkins. cp-ansible-on-demand and cp-ansible-weekly jobs need to be updated as well. The env variables need to be passed by the user when running a scenario locally.
Fixes # [ANSIENG-2553](https://confluentinc.atlassian.net/browse/ANSIENG-2553)
[jenkins job](https://jenkins.confluent.io/job/cp-ansible-on-demand/1732/)
[ANSIENG-2553]: https://confluentinc.atlassian.net/browse/ANSIENG-2553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add env variables to use SSO tokens from vault

DEVELOPMENT_GUIDE.md, roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/fetch_logs.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/dynamic_groups.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_consumer.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_monitoring.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_producer.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml, tasks/certificate_authority.yml, tasks/masterkey.yml, tasks/upgrade_component.yml, tasks/upgrade_component_archive.yml, upgrade_kafka_broker.yml, upgrade_ksql.yml, upgrade_zookeeper.yml
As per Ansible official documentation in the file module mode should be in qoutes. If mode is in octal format then in certain cases like loops it might fail. [docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html)
Fixes # [ANSIENG-2525](https://confluentinc.atlassian.net/browse/ANSIENG-2525)
[ANSIENG-2525]: https://confluentinc.atlassian.net/browse/ANSIENG-2525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> changed mode from octal to string in 6.1.x

DEVELOPMENT_GUIDE.md, roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/fetch_logs.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/dynamic_groups.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_consumer.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_monitoring.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_producer.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml, tasks/certificate_authority.yml, tasks/masterkey.yml
As per Ansible official documentation in the file module mode should be in qoutes. If mode is in octal format then in certain cases like loops it might fail. [docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html)
Fixes # [ANSIENG-2525](https://confluentinc.atlassian.net/browse/ANSIENG-2525)
[ANSIENG-2525]: https://confluentinc.atlassian.net/browse/ANSIENG-2525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> changed mode from octal to string 6.2.x

docs/DEVELOPMENT_GUIDE.md, playbooks/tasks/certificate_authority.yml, roles/common/tasks/debian.yml, roles/common/tasks/fetch_logs.yml, roles/common/tasks/masterkey.yml, roles/common/tasks/redhat.yml, roles/common/tasks/ubuntu.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/dynamic_groups.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_broker/tasks/secrets_protection.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/kafka_connect_replicator/tasks/rbac_replicator.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_consumer.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_monitoring.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_producer.yml, roles/kafka_rest/tasks/main.yml, roles/kerberos/tasks/main.yml, roles/ksql/tasks/ccloud_certs.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml, roles/ssl/tasks/provided_keystore_and_truststore.yml, roles/zookeeper/tasks/main.yml
As per Ansible official documentation in the file module mode should be in qoutes. If mode is in octal format then in certain cases like loops it might fail. [docs](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/file_module.html)
Fixes # [ANSIENG-2525](https://confluentinc.atlassian.net/browse/ANSIENG-2525)
[ANSIENG-2525]: https://confluentinc.atlassian.net/browse/ANSIENG-2525?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> converted mode from octal to string in 7.3.x

VARIABLES.md, roles/confluent.variables/defaults/main.yml
Bumping up pinned cli version for cp 6.0 from 1.43.0 to 1.43.2
[1749](https://jenkins.confluent.io/job/cp-ansible-on-demand/1749/) ✅ 
[1761](https://jenkins.confluent.io/job/cp-ansible-on-demand/1761/) ✅
=> bump cli version to 1.43.2 for 6.0.x

VARIABLES.md, roles/confluent.variables/defaults/main.yml
Bumping up pinned cli version for cp 6.1 from 1.43.0 to 1.43.2
[1750](https://jenkins.confluent.io/job/cp-ansible-on-demand/1750/) ✅ 
[1762](https://jenkins.confluent.io/job/cp-ansible-on-demand/1762/) ✅
=> bump cli version to 1.43.2 for 6.1.x

VARIABLES.md, roles/confluent.variables/defaults/main.yml
Bumping up pinned cli version for cp 6.2 from 1.43.0 to 1.43.2
[1751](https://jenkins.confluent.io/job/cp-ansible-on-demand/1751/) ✅ 
[1763](https://jenkins.confluent.io/job/cp-ansible-on-demand/1763/) ✅
=> bump cli version to 1.43.2 for 6.2.x

docs/VARIABLES.md, roles/variables/defaults/main.yml
Bumping up pinned cli version for cp 7.1 from 2.3.1 to 2.38.1
[1753](https://jenkins.confluent.io/job/cp-ansible-on-demand/1753/) ✅ 
[1765](https://jenkins.confluent.io/job/cp-ansible-on-demand/1765/) ✅
=> bump cli version to 2.38.1 for 7.1.x

VARIABLES.md, roles/variables/defaults/main.yml
Bumping up pinned cli version for cp 7.0 from 1.43.0 to 2.38.1
[1752](https://jenkins.confluent.io/job/cp-ansible-on-demand/1752/) ✅ 
[1764](https://jenkins.confluent.io/job/cp-ansible-on-demand/1764/) ✅
=> bump cli version to 2.38.1 for 7.0.x

docs/VARIABLES.md, roles/variables/defaults/main.yml
Bumping up pinned cli version for cp 7.2 from 2.19.0 to 2.38.1
[1760](https://jenkins.confluent.io/job/cp-ansible-on-demand/1760/) ✅ 
[1766](https://jenkins.confluent.io/job/cp-ansible-on-demand/1766/) ✅
=> bump cli version to 2.38.1 for 7.2.x

docs/VARIABLES.md, molecule/archive-plain-debian/molecule.yml, roles/variables/defaults/main.yml
Bumping up pinned cli version for cp 7.4 from 3.2.1 to 3.30.1
[1756](https://jenkins.confluent.io/job/cp-ansible-on-demand/1756/) [1768](https://jenkins.confluent.io/job/cp-ansible-on-demand/1768/) ✅  (zk)
[1757](https://jenkins.confluent.io/job/cp-ansible-on-demand/1757/) [1775](https://jenkins.confluent.io/job/cp-ansible-on-demand/1775/) ✅  (kraft)
=> bump cli version to 3.30.1 for 7.4.x

docs/VARIABLES.md, roles/variables/defaults/main.yml
Bumping up pinned cli version for cp 7.3 from 2.28.1 to 2.38.1
[1755](https://jenkins.confluent.io/job/cp-ansible-on-demand/1755/) ✅ 
[1767](https://jenkins.confluent.io/job/cp-ansible-on-demand/1767/) ✅
=> bump cli version to 2.38.1 for 7.3.x

docs/VARIABLES.md, molecule/archive-plain-debian/molecule.yml, roles/variables/defaults/main.yml
Bumping up pinned cli version for cp 7.5 from 3.2.1 to 3.30.1
[1758](https://jenkins.confluent.io/job/cp-ansible-on-demand/1758/) [1770](https://jenkins.confluent.io/job/cp-ansible-on-demand/1770/) ✅ (zk)
[1759](https://jenkins.confluent.io/job/cp-ansible-on-demand/1774/) [1749](https://jenkins.confluent.io/job/cp-ansible-on-demand/1774/) ✅ (kraft)
=> bump cli version to 3.30.1 for 7.5.x

roles/confluent.variables/vars/main.yml
Update default number of threads for C3 to 12
Fixes # [ANSIENG-2632](https://confluentinc.atlassian.net/browse/ANSIENG-2632)
[jenkins](https://jenkins.confluent.io/job/cp-ansible-on-demand/2106/)
[ANSIENG-2632]: https://confluentinc.atlassian.net/browse/ANSIENG-2632?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update default number of threads for C3

molecule/rbac-mtls-rhel/verify.yml, roles/kafka_broker/tasks/main.yml
Fixes secrets protection of Kraft Controller with mutual TLS on RBAC cluster
Fixes # [ANSIENG-2741](https://confluentinc.atlassian.net/browse/ANSIENG-2741)
[jenkins tests](https://jenkins.confluent.io/job/cp-ansible-on-demand/2105/testReport/)
[ANSIENG-2741]: https://confluentinc.atlassian.net/browse/ANSIENG-2741?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Secrets protection of Kraft with mTLS

roles/kafka_controller/tasks/rbac.yml
improves error handling for Kraft controller
Fixes # [ANSIENG-2857](https://confluentinc.atlassian.net/browse/ANSIENG-2857)
locally
[ANSIENG-2857]: https://confluentinc.atlassian.net/browse/ANSIENG-2857?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Improve error handling when RBAC cluster has no auth

molecule/Dockerfile-debian-archive.j2, molecule/Dockerfile-debian.j2, molecule/Dockerfile-rhel7-java17.j2
Dockerfiles are used for molecule testing. Rhel7, Debian9 do not support arm architecture and hence from dockerfiles which were used by rhel7, debian9 scenarios removed arm related variables.
Fixes # [2958](https://confluentinc.atlassian.net/browse/ANSIENG-2958)
=> Removed arm variables from dockerfiles of Rhel7, Debian9

meta/runtime.yml
Since Ansible-core 2.13 reached EOL in November 2023, update minimum supported version to 2.14 as per RedHat requirements. Our playbooks are still compatible with 2.11+ but 2.14 is recommended
Fixes # [ANSIENG-2938](https://confluentinc.atlassian.net/browse/ANSIENG-2938)
tested locally
[ANSIENG-2938]: https://confluentinc.atlassian.net/browse/ANSIENG-2938?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Minimum Ansible version to 2.14

docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, docs/hosts_example.yml, meta/runtime.yml, molecule/archive-plain-ubuntu2004/molecule.yml, molecule/archive-plain-ubuntu2004/verify.yml, molecule/connect-scale-up/molecule.yml, molecule/connect-scale-up/verify.yml, molecule/kerberos-rhel/molecule.yml, molecule/kerberos-rhel/verify.yml, molecule/ksql-scale-up/molecule.yml, molecule/ksql-scale-up/verify.yml, molecule/multi-ksql-connect-rhel/molecule.yml, molecule/multi-ksql-connect-rhel/verify.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-plain-provided-debian9/molecule.yml, molecule/rbac-plain-provided-debian9/verify.yml, molecule/rbac-scram-custom-rhel-fips/molecule.yml, molecule/rbac-scram-custom-rhel-fips/verify.yml, plugins/modules/kafka_connectors.py, roles/kafka_connect/tasks/deploy_connectors.yml, roles/kafka_connect/tasks/rbac_connectors.yml, roles/kafka_connect/tasks/role_bindings_connector.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
This PR adds a new feature to deploy connectors on a RBAC cluster. Along with that, deploying connectors with mutual TLS is also supported in this PR. 
Fixes # [ANSIENG-2939](https://confluentinc.atlassian.net/browse/ANSIENG-2939)
tested in on-demand job
[ANSIENG-2939]: https://confluentinc.atlassian.net/browse/ANSIENG-2939?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Deploy Connectors in a RBAC cluster

docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, molecule/cp-kafka-plain-rhel/molecule.yml, roles/kafka_controller/tasks/health_check.yml, roles/variables/defaults/main.yml
This PR adds support for custom Kraft Controller port. Customers can now use `kafka_controller_port` to expose the kraft port, with default being 9093
Fixes # [ANSIENG-3149](https://confluentinc.atlassian.net/browse/ANSIENG-3149)
tested on scenario cp-kafka-plain-rhel
[ANSIENG-3149]: https://confluentinc.atlassian.net/browse/ANSIENG-3149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2966] | Add custom port for Kraft Controller

playbooks/ZKtoKraftMigration.yml, playbooks/migration_precheck.yml
Migration pre-check should fail if Kraft Controller port is already occupied by Zk broker. In that case, the customer needs to use some other port for Kraft using kafka_controller_port
Fixes # [ANSIENG-3149](https://confluentinc.atlassian.net/browse/ANSIENG-3149)
tested locally
[ANSIENG-3149]: https://confluentinc.atlassian.net/browse/ANSIENG-3149?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-3149] | Add precheck for Kraft Controller port availability

roles/kafka_broker/tasks/rbac.yml, roles/kafka_broker/tasks/set_controller_principal.yml
Fix to get correct node id for Colocated Kraft and broker having RBAC enabled and mutual TLS
Fixes # [ANSIENG-3153](https://confluentinc.atlassian.net/browse/ANSIENG-3153)
tested different combinations with 7.6.x branch, back-porting to 7.4.x
- Greenfield kraft setup having RBAC + mtls + all colocated Controller and Broker
- Greenfield kraft setup having RBAC + mtls + some Controllers are colocated with Broker
- Greenfield kraft setup having RBAC + mtls + no colocation
- Migration to Kraft setup having RBAC + mtls + all colocated Controller and Broker 
- Migration to kraft setup having RBAC + mtls + some Controllers are colocated with Broker
- Migration to kraft setup having RBAC + mtls + no colocation
- [] I have made corresponding changes to the documentation
[ANSIENG-3153]: …
=> [ANSIENG-3153] | Resolve node id in Colocated Kraft Controller and broker

molecule/Dockerfile-rhel-java11.j2, molecule/Dockerfile-rhel-java17.j2, molecule/Dockerfile-rhel-java8.j2, molecule/Dockerfile-rhel-tar.j2
Molecule scenarios having ubi9-minimal image were failing due to a cd command in dockerfile. Modified the dockerfile by removing the line.
Fixes # [ANSIENG-3229](https://confluentinc.atlassian.net/browse/ANSIENG-3229)
Test scenarios based on  ubi8,ubi9,rocky8,rocky9,oracle8,oracle9 -> [jenkins-2451](https://jenkins.confluent.io/job/cp-ansible-on-demand/2451/testReport/)
[ANSIENG-3229]: https://confluentinc.atlassian.net/browse/ANSIENG-3229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-3229] | modified dockerfiles for ubi9-minimal

roles/variables/vars/main.yml
This PR aims to add broker's jaas configs in Kraft Controller. With kip 966, Controller now needs to communicate with Broker as well. Earlier it was one way communication broker-> controller. Starting CP 7.6, both controller-> broker and broker->controller communication happens internally. For this, Controller needs the jaas configs of broker when sasl protocol is plain.
Fixes # [ANSIENG-3230](https://confluentinc.atlassian.net/browse/ANSIENG-3230)
jenkins jobs
[ANSIENG-3230]: https://confluentinc.atlassian.net/browse/ANSIENG-3230?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-3230]  | Add broker's jaas configs in Kraft Controller

molecule/archive-plain-rhel-fips/molecule.yml, molecule/archive-plain-rhel-fips/verify.yml, molecule/archive-plain-ubuntu2004/molecule.yml, molecule/broker-scale-up/molecule.yml, molecule/connect-scale-up/molecule.yml, molecule/kerberos-rhel/molecule.yml, molecule/kerberos-rhel/verify.yml, molecule/ksql-scale-up/molecule.yml, molecule/multi-ksql-connect-rhel/molecule.yml, molecule/multi-ksql-connect-rhel/verify.yml, molecule/plain-rhel/molecule.yml, molecule/plain-rhel/verify.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel-fips/verify.yml, molecule/rbac-plain-provided-debian9/molecule.yml, molecule/rbac-scram-custom-rhel-fips/molecule.yml
Updating CP-Ansible tests to use FileStream Connectors since Verifiable Connector is no longer packaged with kafka.
Fixes # [ANSIENG-3235](https://confluentinc.atlassian.net/browse/ANSIENG-3235)
https://jenkins.confluent.io/job/cp-ansible-on-demand/2507/ 
https://jenkins.confluent.io/job/cp-ansible-on-demand/2508/
[ANSIENG-3235]: https://confluentinc.atlassian.net/browse/ANSIENG-3235?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update Molecule tests to use FileStream Connector

molecule/Dockerfile-rhel9-java11.j2, molecule/Dockerfile-rhel9-java17.j2, molecule/Dockerfile-rhel9-java8.j2, molecule/Dockerfile-rhel9-tar.j2
Molecule scenarios having ubi9-minimal image were failing due to a cd command in dockerfile. Modified the dockerfile by removing the line.
Fixes # [ANSIENG-3229](https://confluentinc.atlassian.net/browse/ANSIENG-3229)
Test scenarios based on  ubi9 -> [jenkins](https://jenkins.confluent.io/job/cp-ansible-on-demand/2459/testReport/)
[ANSIENG-3229]: https://confluentinc.atlassian.net/browse/ANSIENG-3229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-3229] | remove cd command to fix  docker img creation for ubi9-minimal

molecule/Dockerfile-rhel9-java11.j2, molecule/Dockerfile-rhel9-java17.j2, molecule/Dockerfile-rhel9-java8.j2, molecule/Dockerfile-rhel9-tar.j2
Molecule scenarios having ubi9-minimal image were failing due to a cd command in dockerfile. Modified the dockerfile by removing the line.
Fixes # [ANSIENG-3229](https://confluentinc.atlassian.net/browse/ANSIENG-3229)
Test scenarios based on ubi9 -> [jenkins](https://jenkins.confluent.io/job/cp-ansible-on-demand/2459/testReport/)
[ANSIENG-3229]: https://confluentinc.atlassian.net/browse/ANSIENG-3229?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-3229] | removed cd to fix dockerfile for ubi9-min

molecule/broker-scale-up/verify.yml, molecule/rbac-mtls-rhel/verify.yml, roles/common/tasks/configure_logredactor.yml
Modifed verify files to remove jinja usage in when and that statements as it causes error for ansible version 7
Fixes # [(issue)](https://confluentinc.atlassian.net/browse/ANSIENG-3489)
ansible version 4.10.0 [Jenkins-2601](https://jenkins.confluent.io/job/cp-ansible-on-demand/2601/)
ansible version 5.5.0 [Jenkins-2600](https://jenkins.confluent.io/job/cp-ansible-on-demand/2600/)
ansible version 6.4.0 [Jenkins-2599](https://jenkins.confluent.io/job/cp-ansible-on-demand/2599/)
ansible version 7.1.0 [Jenkins-2598](https://jenkins.confluent.io/job/cp-ansible-on-demand/2598/)
=> Remove jinja from when and that ANSIENG-3489

roles/kafka_connect/tasks/main.yml, roles/kafka_connect/tasks/register_cluster.yml, roles/ksql/tasks/main.yml, roles/ksql/tasks/register_cluster.yml
Bug fix for registering Connect and Ksql clusters on colocated components
Fixes # [ANSIENG-3494](https://confluentinc.atlassian.net/browse/ANSIENG-3494)
tested locally
[ANSIENG-3494]: https://confluentinc.atlassian.net/browse/ANSIENG-3494?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-3474] | Fix Connect and Ksql Cluster Registry in colocated cluster

playbooks/validate_hosts.yml
validate_hosts playbook did not have rhel 9 in supported OS list, even though RHEL9 is supported starting CP-Ansible 7.4.x
Fixes # [ANSIENG-3148](https://confluentinc.atlassian.net/browse/ANSIENG-3148)
[ANSIENG-3148]: https://confluentinc.atlassian.net/browse/ANSIENG-3148?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add Rhel 9 in supported OS list

docs/VARIABLES.md, roles/variables/defaults/main.yml
PR to Update default Kafka Controller log dir documentation. The default location is /var/log/controller, whereas in the variables.md file, it was /var/log/kafka by mistake
=> Update default Kafka Controller log dir documentation

molecule/plain-rhel/molecule.yml, molecule/plain-rhel/prepare.yml
Currently the CDN URL is used to get connector plugins, updating and using confluent-hub api. CDN `d1i4a15mxbxib1` is being deprecated as part of cc-root-1 migration - https://confluentinc.atlassian.net/browse/CC-22768
confluent-hub api should be used to download connector plugins which redirects to the updated EBS and CDN
Test job: https://jenkins.confluent.io/job/cp-ansible-on-demand/2650/console
=> Use confluent-hub api to download connect-plugins

roles/kafka_broker/tasks/get_meta_properties.yml, roles/kafka_controller/tasks/get_meta_properties.yml
This PR aims to fix bug raised in https://github.com/confluentinc/cp-ansible/issues/1587
Fixes # [ANSIENG-3696](https://confluentinc.atlassian.net/browse/ANSIENG-3696)
tested locally 
[ANSIENG-3696]: https://confluentinc.atlassian.net/browse/ANSIENG-3696?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-3696] | Fix kafka-storage command for cluster id starting with hyphen

roles/kafka_controller/tasks/health_check.yml
renaming internal var with lowercase letters instead of uppercase. The variable names having uppercase letters cause warnings on running galaxy-importer
=> [ANSIENG-3627] | renaming internal var with lowercase letters instead of uppercase

roles/common/tasks/configure_logredactor.yml
Removed jinja from when statements in add redactor in logger task.
Already fixed in 7.4.x and onwards. Missed to merge this one in 7.2.x & 7.3.x
Fixes # [(ANSIENG-3489)](https://confluentinc.atlassian.net/browse/ANSIENG-3489)
=> [ANSIENG-3489] | removed jinja from when in add redactor in logger

plugins/filter/filters.py
In python when raising error instead of passing multiple strings it should be passed some object. So passing it the ValueError object to fix lint error in galaxy-importer
Fixes # [(ANSIENG-3627)](https://confluentinc.atlassian.net/browse/ANSIENG-3627)
=> [ANSIENG-3627] | fix the raise error by using valueError instead of str

roles/kafka_controller/tasks/health_check.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_controller/templates/client.properties.j2
CP-Ansible relies on the undocumented confluent.use.controller.listener configuration to communicate directly with KRaft controllers. This configuration was never intended to be used by external clients. In CP 7.7, this undocumented configuration was removed, as was the ability to communicate with KRaft controllers by putting a controller address in --bootstrap-server instead use --bootstrap-controller when communicating directly with the controllers.
Fixes # [(issue)](https://confluentinc.atlassian.net/browse/ANSIENG-3079)
[semaphore tests for community and enterprise](https://semaphore.ci.confluent.io/workflows/1bb04d63-63a5-4374-8fd0-55ee504b45ad)
=> [ANSIENG-3079] | modified direct communication with controller using bootstrap-controller

tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.9.txt
Since jenkinsfile is renamed all the references to it in code should also be renamed.
=> [ANSIENG-3627] | renamed jenkinsfile in sanity ignores files

tests/sanity/ignore-2.16.txt
Added few discovery files in sanity tests ignores for ansible 9.
=> [ANSIENG-3627] | added sanity test ignores for discovery in ansible 9

roles/ssl/tasks/provided_keystore_and_truststore.yml
There should not be any jinja2 in when statements. Thus removing it
Fixes # [(ANSIENG-3489)](https://confluentinc.atlassian.net/browse/ANSIENG-3489)
Added debug statements to check values which are getting used [semaphore-run](https://semaphore.ci.confluent.io/jobs/08583afb-de35-4244-9cf1-f27eeb06ca1f)
=> [ANSIENG-3489] | removed jinja from when in provided keystore truststore

README.md, docs/VARIABLES.md, docs/hosts_example.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml, roles/variables/defaults/main.yml, roles/zookeeper/tasks/main.yml
At times it could be useful to copy a file to all managed nodes, today you will need to include an entry for each of the components making the inventory file too long for no reason. 
Adding all_components_copy_files will copy the list of files to all managed nodes
Validated against a AWS installed cluster.
=> Adding a single property to copy files to components all_components_copy_files

playbooks/validate_hosts.yml
Galaxy Importer doesnt allow this format of using jinja in environment. So modified it
Fixes [ANSIENG-3627](https://confluentinc.atlassian.net/browse/ANSIENG-3627)
Manually tested validate_hosts playbook on molecule scenario
[ANSIENG-3627]: https://confluentinc.atlassian.net/browse/ANSIENG-3627?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-3627] | Is not of type Object Error from galaxy-importer

molecule/oauth-rbac-mds-kerberos-debian/molecule.yml, molecule/oauth-rbac-plain-rhel8/molecule.yml, molecule/plain-rhel/molecule.yml, molecule/rbac-plain-provided-debian9/molecule.yml, molecule/rbac-plain-provided-debian9/prepare.yml, plugins/filter/filters.py, roles/ksql/tasks/main.yml, roles/ksql/tasks/rbac.yml, roles/ksql/tasks/register_cluster.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml, test_roles/confluent.test.oauth/defaults/main.yml
This PR adds ksql as OAuth client support. In ldap+oauth setup, ksql will act as ldap client. In oauth only setup, ksql will act as oauth client. However, ksql will not have authn/authz as server.
Along with this some fixes are added for oauth_groups_scope clients.
Fixes # [ANSIENG-3839](https://confluentinc.atlassian.net/browse/ANSIENG-3839)
tested locally on OAuth setup
[ANSIENG-3839]: https://confluentinc.atlassian.net/browse/ANSIENG-3839?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> KSQL as OAuth client

molecule/Dockerfile-oauth.j2, molecule/kafka-connect-replicator-mtls-scram-rhel/molecule.yml, molecule/oauth-rbac-mds-kerberos-debian/molecule.yml, molecule/oauth-rbac-plain-rhel8/molecule.yml, molecule/plain-rhel/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/rbac-plain-provided-debian9/molecule.yml
Enables https on keycloak server. Molecule scenarios can use it by defining the following variables
```
keycloak_oauth_server_port: 8443
keycloak_http_protocol: https
oauth_token_uri: https://oauth1:8443/realms/cp-ansible-realm/protocol/openid-connect/token
oauth_issuer_url: https://oauth1:8443/realms/cp-ansible-realm
oauth_jwks_uri: https://oauth1:8443/realms/cp-ansible-realm/protocol/openid-connect/certs
```
Fixes # [(ANSIENG-3383)](https://confluentinc.atlassian.net/browse/ANSIENG-3383)
=> [ANSIENG-3383] | Https in keycloak 

roles/variables/vars/main.yml
This PR is an extension of https://github.com/confluentinc/cp-ansible/pull/1686 to cover the case when SSO is enabled on non SSL cluster
Fixes # [ANSIENG-3860](https://confluentinc.atlassian.net/browse/ANSIENG-3860)
tested locally
[ANSIENG-3860]: https://confluentinc.atlassian.net/browse/ANSIENG-3860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-3860] | Add MDS truststore when sso idp cert provided

plugins/filter/filters.py, roles/common/tasks/idp_certs.yml, roles/kafka_broker/tasks/main.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Add IDP to truststore in C3 SSO in 7.5.x patch, same changes would be needed in 7.6.x 
Fixes # [ANSIENG-3860](https://confluentinc.atlassian.net/browse/ANSIENG-3860)
tested locally, it will be better tested when we create local keycloak idp server in 7.5 as well, similar to 7.7
[ANSIENG-3860]: https://confluentinc.atlassian.net/browse/ANSIENG-3860?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add IDP to truststore in C3 SSO

roles/common/tasks/debian.yml
Debian 10 has reached EOL and thus ftp.debian.org no longer works and we need to use archive.debian.org in etc/apt/source.list
Fixes # [(issue)](https://confluentinc.atlassian.net/browse/ANSIENG-3712)
=> [ANSIENG-3712] | moving from ftp.debian.org to archive.debian.org as debian10 reached eol

molecule/Dockerfile-rhel-base.j2, molecule/Dockerfile-rhel-java8.j2, molecule/Dockerfile-tar.j2, molecule/Dockerfile.j2, molecule/confluent-kafka-kerberos-customcerts-rhel/molecule.yml, molecule/cp-kafka-plain-rhel/molecule.yml, molecule/mtls-customcerts-rhel/molecule.yml, molecule/plaintext-rhel/molecule.yml, molecule/rbac-scram-custom-rhel/molecule.yml
Centos 7 has reached EOL and thus our tests which used it are failing. To fix we need to move from mirror.centos.org to vault.centos.org in yum.repos.d files
Fixes # [(issue)](https://confluentinc.atlassian.net/browse/ANSIENG-3880)
=> [ANSIENG-3880] | Fix centos7 Tests

molecule/Dockerfile-rhel-base.j2, molecule/Dockerfile-rhel-java8.j2, molecule/Dockerfile-tar.j2, molecule/Dockerfile.j2, molecule/confluent-kafka-kerberos-customcerts-rhel/molecule.yml, molecule/cp-kafka-plain-rhel/molecule.yml, molecule/mtls-customcerts-rhel/molecule.yml, molecule/plaintext-rhel/molecule.yml, molecule/rbac-scram-custom-rhel/molecule.yml
Centos 7 has reached EOL and thus our tests which used it ar failing. To fix we need to move from mirror.centos.org to vault.centos.org in yum.repos.d files
Fixes # [(issue)](https://confluentinc.atlassian.net/browse/ANSIENG-3880)
[semaphore](https://semaphore.ci.confluent.io/jobs/0af8811d-8076-40c1-abbc-f247acb1083b/summary)
=> [ANSIENG-3880] | Fix centos7 Tests 

roles/kafka_controller/tasks/health_check.yml
In CP 7.6 and older, CP-Ansible relies on the undocumented confluent.use.controller.listener configuration to communicate directly with KRaft controllers. This configuration was never intended to be used by external clients. In CP 7.7, this undocumented configuration was removed, as was the ability to communicate with KRaft controllers by putting a controller address in --bootstrap-server.
this caused issues during upgrade. We cannot directly move from --bootstrap-server to --bootstrap-controller as during rolling upgrade packages would be new but metadata version would be corresponding to older cp version and thus this will fail. Both need to be used in conjunction to address this.
Fixes # [(issue)](https://confluentinc.atlassian.net/browse/ANSIENG-4140) …
=> [ANSIENG-4140] | Fix Issue in Health check of controllers due to fixes for KIP-919

roles/common/tasks/confluent_cli.yml, roles/common/tasks/main.yml
Adding explicit owner and group using file module after unarchive as unarchive is not able to set owners correctly
Fixes # [(issue)](https://confluentinc.atlassian.net/browse/ANSIENG-4181)
[semaphore](https://semaphore.ci.confluent.io/jobs/201c8a90-2206-41d0-9a64-59560e6882b9)
=> Adding explicit owner and group using file module

molecule/oauth-rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/oauth-rbac-plain-provided-debian12/molecule.yml, roles/variables/vars/main.yml
The aim of this PR is For OAuth brownfield setup, the connectors present in ldap cluster should remain on ldap configs to avoid downtime. 
Fixes #[ ANSIENG-4168](https://confluentinc.atlassian.net/browse/ANSIENG-4168)
tested on oauth-rbac-plain-provided-debian12, more testing going on
=> making connector default to ldap in brownfield OAuth unless specified

molecule/rbac-mds-mtls-custom-rhel-fips/certificate-hosts, molecule/rbac-mds-mtls-custom-rhel-fips/prepare.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, roles/variables/vars/main.yml
- zookeeper to kraft migration would use metadata version to 3.7 instead of 3.6
- fixed minor issues in molecule scenarios for migration
=> Zookeeper to kraft migration would use metadata version to 3.7

test_roles/confluent.test/tasks/check_connector.yml
- Fixing check_connector file used during verify in molecule to allow unauthenticated connectors as well
- Fixes kerberos-rhel and archive-plain-rhel-fips verify
=> [ANSIENG-3465] | fixing check_connector to allow unauthenticated connectors as well

roles/kafka_broker/tasks/main.yml
In Copy IDP Cert to Node task the idp_cert_path variable comes from sso_idp_cert_path which is user facing variable. But the idp_cert_dest is hardcoded to sso_idp_cert.pem which means it goes to the home directory of target machine. Now in certain cases ansible-playbook’s user might not have permissions to write files to home directory where this task will fail with the error Destination . not writable.
To fix we move the target file to /tmp directory which is a directory where all users have write permissions.
Fixes # ([issue](https://confluentinc.atlassian.net/browse/ANSIENG-4213))
[semaphore](https://semaphore.ci.confluent.io/workflows/9dadb691-93e9-4e05-a379-13219bec6759?pipeline_id=9d3cdcb8-3579-4504-8d0c-9dda43153e1c)
=> [ANSIENG-4213] | Copy IDP Cert to /tmp instead of ~/ for 7.6

molecule/oauth-plain-rhel/verify.yml, molecule/scram-rhel/verify.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml
In Copy IDP Cert to Node task the idp_cert_path variable comes from oauth_idp_cert_path which is user facing variable. But the idp_cert_dest is hardcoded to oauth_idp_cert.pem which means it goes to the home directory of target machine. Now in certain cases ansible-playbook’s user might not have permissions to write files to home directory where this task will fail with the error Destination . not writable.
- To fix we move the target file to /tmp directory which is a directory where all users have write permissions.
- Also moved the control plane listener property check in the verify from oauth-plain-rhel to scram-rhel as the corresponding `kafka_broker_configure_control_plane_listener: true` was also earlier moved to scram-rhel scenario.
Fixes # …
=> [ANSIENG-4213] |  Copy IDP Cert to /tmp instead of ~/ for 7.7

molecule/archive-plain-rhel-fips/molecule.yml, molecule/archive-plain-rhel-fips/verify.yml, molecule/archive-scram-rhel/molecule.yml, molecule/archive-scram-rhel/verify.yml
This PR fixes the molecule tests failing in 7.6.x because of following reasons:
archive-plain-rhel-fips: Get Topics with UnderReplicatedPartitions
rbac-mds-mtls-custom-rhel-fips: Retrieve SSL public key hash from private key on Local Host
https://semaphore.ci.confluent.io/workflows/da60affa-295e-42fe-be01-fbb3afc28fae?pipeline_id=4c04824c-8913-490a-a40f-86ce43559edf
https://semaphore.ci.confluent.io/workflows/48e4616d-ec1f-4b22-8d52-b73c4d0f5902?pipeline_id=b1e6b556-5a7a-453a-b7b8-95d0a45631f2
=> [ANSIENG-4228] | fix molecule tests (#38)

roles/kafka_broker/tasks/rbac.yml, roles/kafka_controller/tasks/rbac.yml
super.users in controller should contain the mtls cert's principal. Adding that and refactoring the code to handle multiple principals coming from ldap/oauth/cert.
=> [ANSIENG-3807] | Fix controller super users by adding cert principal

roles/kafka_broker/tasks/main.yml, roles/kafka_controller/tasks/main.yml
This PR fixes the permission issue of directory file which was caused of permission change task running before storage command.
https://semaphore.ci.confluent.io/workflows/bf823595-d3a5-49ce-be22-a54f80b881cf?pipeline_id=214a07d1-3995-41fe-adef-65eab0aa36c1
=> [ANSIENG-3780] | permission issue for log directory fix

roles/variables/vars/main.yml
`confluent.metadata.server.ssl.endpoint.identification.algorithm: https` this doesnt work from cp side for rbac over mtls.
Thus we need to not add it whenever MDS has mTLS.
Fixes # https://confluent.slack.com/archives/C06E8NMUYDU/p1731426944275189
[rbac over mTLS ](https://semaphore.ci.confluent.io/workflows/452c4ee3-3fab-4ddc-922c-7f3cf110357a?pipeline_id=5aa03bbe-29e1-401d-adac-bea4547e1658) 
[ rbac ](https://semaphore.ci.confluent.io/workflows/b8dd5e5c-078d-4d3a-8df5-40878da93049?pipeline_id=280b598e-31e3-4ed7-a44f-a65c1b982ec9)
=> [ANSIENG-4293] | fixing endpoint identification algo

molecule/rbac-mds-mtls-custom-rhel-fips/certificate-hosts, molecule/rbac-mds-mtls-custom-rhel-fips/prepare.yml
This PR fixes rbac-mds-mtls-custom-rhel-fips test caused by mds-controller1-mig-key.pem being not available.
=> [ANSIENG-4310] | test fix

.semaphore/build_collection.sh
Ci checks assume python 3.8 and onwards are pre installed. This used to be the case earlier but since python 3.8 went EOL semaphore nodes dont come preinstalled with it.
Fixes # ([issue](https://confluentinc.atlassian.net/browse/ANSIENG-4328))
=> [ANSIENG-4238] | remove py 3.8 from ci checks as it is eol

molecule/oauth-rbac-mds-kerberos-debian/verify.yml, molecule/oauth-rbac-plain-rhel8/verify.yml, molecule/rbac-mds-kerberos-debian/verify.yml, molecule/rbac-mds-plain-custom-rhel-fips/verify.yml, molecule/rbac-mtls-rhel8/verify.yml, molecule/rbac-scram-custom-rhel-fips/verify.yml
Molecule tests which setup C3 with SSO are a bit flaky in the task Check status of Authenticate api
This task is present in verify.yml files. The reason for flakiness is C3 takes little more time to start when it has SSO. And verify.yml runs before C3 actually starts.
To fix this issue adding sleep of 1 minute before running the Check status of Authenticate api was good enough to make these tests pass. So instead of using sleep we added retries where it retries for 2 minutes until this authenticate status is okay.
Making this change will impact the following scenarios
- rbac-mtls-rhel8 (Very very flaky)
- rbac-mds-plain-custom-rhel-fips (little flaky)
- rbac-mds-kerberos-debian (little flaky)
- rbac-scram-custom-rhel-fips (little flaky)
- oauth-rbac-plain-rhel8 (little flaky)
- …
=> [ANSIENG-4314] | adding retries for verify task to authenticate to c3 via sso

molecule/archive-scram-rhel/verify.yml, molecule/kerberos-rhel/verify.yml, molecule/rbac-scram-custom-rhel-fips/verify.yml, molecule/scram-rhel/verify.yml, test_roles/confluent.test/tasks/check_subproperty.yml
In a couple of test cases we had a check to confirm the value of `sasl.enabled.mechanisms` is set to `GSSAPI,PLAIN` but it could also have been set to `PLAIN,GSSAPI`. so instead of doing a string matching of values we can parse the value and split by comma and make a list. Then compare items of list to ensure all the mechanisms which should be present are actually present.
This will help remove flakiness as at times this property would be set to  `GSSAPI,PLAIN` and at other times it would be `PLAIN,GSSAPI` both of which are same from cp point of view.
Semaphore link - [add here]
=> [ANSIENG-4314] | Adding check sub property role for testing comma seperated list of values

test_roles/confluent.test/tasks/check_subproperty.yml
properties file can be of the format `key=val` or `key = val` or even something like `key= val`. So artibitrary number of space before and after = should be handled in regex when capturing the list of property values.
[sem](https://semaphore.ci.confluent.io/workflows/218901b5-3f3f-415d-b3d6-3f953c59ea90/summary)
=> [scram-rhel] | fixing space before and after = sign in properties file

molecule/oauth-rbac-plain-rhel8/verify.yml, roles/variables/vars/main.yml
Ansible should not restrict adding cli sso config based on the cli installation method. It is possible that cli was installed manually and cp-ansible is used to enable SSO in it.
Fixes # [ANSIENG-4583](https://confluentinc.atlassian.net/browse/ANSIENG-4583)
tested locally. Also added a task in verify to validate that the config is getting added now
[ANSIENG-4583]: https://confluentinc.atlassian.net/browse/ANSIENG-4583?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-4583] | Remove confluent cli download dependency for cli SSO

docs/sample_inventories/ACLs.txt, docs/sample_inventories/mtlsACLs.txt, docs/sample_inventories/nonRBACtoRBACLdap.yml, docs/sample_inventories/nonRBACtoRBACOAuth.yml
This PR adds sample inventories to enable rbac in cp-ansible. Sample ACL commands are also added.
Fixes # [ANSIENG-4490](https://confluentinc.atlassian.net/browse/ANSIENG-4490)
tested locally
[ANSIENG-4490]: https://confluentinc.atlassian.net/browse/ANSIENG-4490?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-4490] Sample inventories for non RBAC to RBAC migration

VARIABLES.md, docs/VARIABLES.md, roles/variables/defaults/main.yml
Thread [Message from Neeraj Upreti in #ansible-oncall](https://confluent.slack.com/archives/CMTBL483Y/p1738251439412289) 
There are 4 replicator variables which should be defined in the inventory file but they don't have any mention in the vars.md file as there is no comment above them to explain what they do.
add comments to explain their use
kafka_connect_replicator_listener
kafka_connect_replicator_consumer_listener
kafka_connect_replicator_producer_listener
kafka_connect_replicator_monitoring_interceptor_listener
doc update
- [] This change requires a documentation update
no testing required.
=> Fix doc for replicator variable ansieng 4561

molecule/Dockerfile-ubuntu-archive.j2, molecule/Dockerfile-ubuntu-java8.j2, molecule/Dockerfile-ubuntu.j2, molecule/Dockerfile-ubuntu2004-archive.j2, molecule/Dockerfile-ubuntu2004.j2
```
throttle: 1
retries: 5
delay: 90
when:
``` …
=> [ANSIENG-4146] | fixing ubuntu test flakiness in adding openjdk repo in 7.1

molecule/Dockerfile-ubuntu-archive.j2, molecule/Dockerfile-ubuntu-java11.j2, molecule/Dockerfile-ubuntu-java8.j2, molecule/Dockerfile-ubuntu.j2, molecule/Dockerfile-ubuntu2004-archive.j2, molecule/Dockerfile-ubuntu2004-java11.j2, molecule/Dockerfile-ubuntu2004.j2
```
throttle: 1
retries: 5
delay: 90
when:
``` …
=> [ANSIENG-4146] | fixing ubuntu test flakiness in adding openjdk repo in 7.4

molecule/Dockerfile-ubuntu-archive.j2, molecule/Dockerfile-ubuntu-java11.j2, molecule/Dockerfile-ubuntu-java8.j2, molecule/Dockerfile-ubuntu.j2, molecule/Dockerfile-ubuntu2004-archive.j2, molecule/Dockerfile-ubuntu2004-java11.j2, molecule/Dockerfile-ubuntu2004.j2
```
throttle: 1
retries: 5
delay: 90
when:
``` …
=> [ANSIENG-4146] | fixing ubuntu test flakiness in adding openjdk repo in 7.5

molecule/Dockerfile-ubuntu-archive.j2, molecule/Dockerfile-ubuntu-java11.j2, molecule/Dockerfile-ubuntu-java8.j2, molecule/Dockerfile-ubuntu.j2, molecule/Dockerfile-ubuntu2004-archive.j2, molecule/Dockerfile-ubuntu2004-java11.j2
```
throttle: 1
retries: 5
delay: 90
when:
``` …
=> [ANSIENG-4146] | fixing ubuntu test flakiness in adding openjdk repo in 7.6

molecule/oauth-plain-rhel/verify.yml
Remove verify control plane listener from oauth-plain-rhel test where `kafka_broker_configure_control_plane_listener: true` was removed from molecule.yml earlier.
Failing test without this change https://semaphore.ci.confluent.io/workflows/cc1207c9-a379-4157-bb7c-93b3a5d0f24c/summary?report_id=1f827083-0472-3472-86b2-93e695256a2a&pipeline_id=c7dfa17b-83e8-47f2-892d-6bcdfe3a33ea
=> Remove verify control plane listener from oauth-plain-rhel test

roles/kafka_broker/tasks/main.yml, roles/kafka_controller/tasks/main.yml
This task tries to change owner and group of files which exist inside data dir. 
All those files are created by kafka user in zookeeper setups. 
2 files meta.properties and bootstrap.checkpoint are created by ansible_user which is typically root and different from kafka_broker_user.
Running this task for greenfield fresh setup would change the owner/grp of the above files to kafka_broker_user,kafka_broker_group which is correct behaviour.
But changing the user and owner using this ansible task while cluster upgrades doesnt do anything.
When I tried to change owner and group of data dir and kafka server process in a running cluster using kafka_broker_user & kafka_broker_group it wasnt able to start the cluster and also messed up logs. log files owner didnt change it simply changed the …
=> [ANSIENG-4200] | fixing race condition in changing file owner

molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/molecule.yml, molecule/rbac-mds-kerberos-mtls-custom-rhel/molecule.yml, molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, molecule/rbac-mds-mtls-custom-rhel/molecule.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mtls-provided-ubuntu/molecule.yml, molecule/rbac-mtls-rhel/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_broker/tasks/rbac.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_controller/tasks/rbac.yml, roles/variables/defaults/main.yml
During any kind of update to a KRaft cluster which has mTLS enabled we currently cant pass tags to run controller and broker separately and also need to give kraft and kafka super users in the custom properties of broker and controller.
Reason is during controller update phase, the super.users list is initially constructed with only the controllers' cert principals, after which the controllers are restarted. At this juncture, the broker - controller communication breaks as broker's cert principals are also needed in kraft controller super.users leading to cluster going down until we also update brokers. This breakdown is avoided by passing in super.users from custom_properties variables to kraft controller.
When we update brokers they go and fetch controller's cert principals and write to …
=> [ANSIENG-3858] Fix mTLS super.users in kraft upgrades

CHANGELOG.rst
=> 7.1 Changelog updated

molecule/Dockerfile-debian-java8.j2, molecule/Dockerfile-debian10.j2, molecule/Dockerfile-ubuntu-java11.j2, molecule/Dockerfile-ubuntu-java8.j2, molecule/Dockerfile-ubuntu.j2, roles/variables/defaults/main.yml
C3 is independent release from 8.0 and thus it will not be pacakged with cp. So when we install it via current configuration for cp repos via yum/apt it fails. 
Thus decoupling it from other components by removing it from package list of other components.
=> remove c3 package as dependency from other components package list

.semaphore/semaphore.yml
Update cp-ansible pipeline to use Ubuntu 24 agents instead of Ubuntu 20
=> [ANSIENG-4697] | Use ubuntu 24 agents in semaphore file

roles/variables/vars/main.yml
kafka_sasl_ldap enabled when  (auth_mode == 'ldap')
semaphore job: https://semaphore.ci.confluent.io/workflows/0cfeb735-98ab-4cdb-b9fb-b31d1031c903
=> [ANSIENG-4625] |  kafka_sasl_ldap enabled when auth_mode == 'ldap'

docs/hosts_example.yml
Replace ssl_mutual_auth_enabled by ssl_client_authentication in hosts_example.yml as ssl_mutual-auth_enabled is deprecated. This is already correctly reflected in VARIABLES.md and the filters.py. However, in the hosts_example.yml it is still reflecting the incorrect configuration in various places.
=> [ANSIENG-4681] | Replace deprecated parameter for mtls in hosts_example.yml

roles/control_center/defaults/main.yml, roles/kafka_broker/defaults/main.yml, roles/kafka_connect/defaults/main.yml, roles/kafka_connect_replicator/defaults/main.yml, roles/kafka_controller/defaults/main.yml, roles/kafka_rest/defaults/main.yml, roles/ksql/defaults/main.yml, roles/schema_registry/defaults/main.yml
After changes in ce-kafka, all endpoints used to configure OAuth need to be explicitly added in a system property by the name (https://github.com/confluentinc/ce-kafka/pull/19023 )
org.apache.kafka.sasl.oauthbearer.allowed.urls, this change needs to be done in all of the component run/startup scripts or nodes on which they are brought up.
This can be done in either of the 2 ways :- 
Explicitly setting the urls as a list in the above config.
org.apache.kafka.sasl.oauthbearer.allowed.urls=<idp_jwks_url>,<idp_token_url>
Allowing all endpoints :- 
org.apache.kafka.sasl.oauthbearer.allowed.urls=*
currently allowing all urls
will be visiting this change back.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list …
=> Ansieng 4729

molecule/mini-setup-ext-mds-mtls/credentials, molecule/mini-setup-ext-mds-mtls/molecule.yml, molecule/mini-setup-mtls/credentials, molecule/mini-setup-mtls/molecule.yml, molecule/mini-setup-mtls/prepare.yml, plugins/filter/filters.py, roles/common/tasks/config_validations.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/rbac.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Changing the C3 to kafka listener from SSL to SASL_SSL in case of SSO.
Using the newly introduced TokenCert Login Callback Handler
This is tested by merging all PRs for RBAC mtls Brownfield in a single branch and then running the tests on that branch
old after using new TokenCert Handler for SSO in C3
[kraft](https://semaphore.ci.confluent.io/workflows/8d1c71c1-5c98-4471-925a-6a4cd4b089ff?pipeline_id=0d2872e8-65e0-43d5-ba2e-aaa8cdea7518)
[zookeeper](https://semaphore.ci.confluent.io/workflows/0f7a803c-f890-453c-a851-595d1428050a?pipeline_id=290bbf79-49f1-4d33-bbab-5d6124e31e78)
new - after using new TokenCert Handler for SSO and non SSO in C3
[kraft](https://semaphore.ci.confluent.io/workflows/8bd417f8-bb01-474e-92da-c0bdfb7a24b8?pipeline_id=68ec584a-d5f9-40e0-a834-fd0c3ccf …
=> [ANSIENG-4742] | Fix c3 kafka listener

roles/common/tasks/idp_certs.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml
After adding Certs to truststore a restart should be triggered to load the new certs in MDS.
=> [ANSIENG-4993] | restart kafka trigger after adding oauth idp cert to truststore

roles/common/tasks/idp_certs.yml, roles/kafka_broker/tasks/main.yml
After adding SSO IDP cert to truststore Kafka restart should be triggered.
=> [ANSIENG-4993] | restart kafka trigger after adding sso cert to truststore

roles/common/tasks/secrets_protection.yml
Add no_log parameter to prevent the masterkey from being leaked in the ansible logs when using the secrets protection feature.
Related to this issue raised with Confluent Support: 269270
Fixes #269270 (MasterKey)
Tested on our deployments from the fork and confirmed that the masterkey doesn't appear in the ansible logs.
=> fix: add no_log to prevent the masterkey to be leak in the ansible logs
