roles/ksql/defaults/main.yml
Change ksql server port to 8088 @ybyzek this what you meant?
=> update ksql server default port to 8088

README.md
@framiere how's this look? resolves #4
=> add docs for setting up hosts.yml

roles/confluent.zookeeper/defaults/main.yml
@adamhutson addresses #33 if you can take a quick look
=> remove unnecessary LOG_DIR from ZooKeeper service

all.yml, plaintext/all.yml, roles/confluent.connect-distributed/defaults/main.yml, roles/confluent.control-center/defaults/main.yml, roles/confluent.control-center/templates/includes/base_control-center.properties.j2, roles/confluent.ksql/defaults/main.yml, roles/confluent.schema-registry/defaults/main.yml, sasl_ssl/all.yml, ssl/all.yml
Reverts confluentinc/cp-ansible#54
=> Revert "Integrate KSQL,Schema Registry,Connect and Control Center"

all.yml, plaintext/all.yml, roles/confluent.connect-distributed/defaults/main.yml, roles/confluent.control-center/defaults/main.yml, roles/confluent.control-center/templates/includes/base_control-center.properties.j2, roles/confluent.ksql/defaults/main.yml, roles/confluent.schema-registry/defaults/main.yml, sasl_ssl/all.yml, ssl/all.yml
Redo #54 but this time base 5.0.x
=> Redo PR 54

roles/confluent.common/defaults/main.yml
=> switched to 5.1 repos

README.md
Corrected the link in the README.md to point to the correct contributions.md.
n/a
- [X ] Bug fix (non-breaking change which fixes an issue)
Confirmed link works via browser.
n/a
- [X ] I have performed a self-review of my own code
- [X ] I have made corresponding changes to the documentation
=> Corrected link to Contribution documentation.

roles/confluent.kafka_connect/defaults/main.yml
confluent-kafka-connect service files are included in the confluent-kafka-2.12 package
Need to include that package in connect's list
=> connect needs confluent-kafka package

group_vars/all/shared_vars.yml
=> need correct version for 5.3.1

hosts_example.yml, roles/confluent.common/meta/main.yml, roles/confluent.common/tasks/main.yml, roles/confluent.control_center/meta/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/meta/main.yml, roles/confluent.kafka_broker/templates/override.conf.j2, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_connect/meta/main.yml, roles/confluent.kafka_connect/templates/override.conf.j2, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.kafka_rest/meta/main.yml, roles/confluent.kafka_rest/templates/override.conf.j2, roles/confluent.ksql/defaults/main.yml, roles/confluent.ksql/meta/main.yml, roles/confluent.ksql/templates/override.conf.j2, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.schema_registry/meta/main.yml, roles/confluent.schema_registry/templates/override.conf.j2, roles/confluent.variables/defaults/main.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/meta/main.yml, roles/confluent.zookeeper/templates/override.conf.j2
downloading jolokia + enabling is now configurable. help in cases where vms cant reach out to internet
tested with kerberos and plaintext with jolokia_enabled set to true and false
=> Jolokia disable

roles/confluent.variables/defaults/main.yml
=> Package version does not match the branch version

roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.ksql/defaults/main.yml, roles/confluent.schema_registry/defaults/main.yml
Included package for all components except zookeeper and control center
=> Missing confluent-security package

roles/confluent.variables/defaults/main.yml
Discovered incorrect kafka protocol getting set, turns out code needs some parentheses
Tested with a few variations of ssl and sasl settings
=> Bug in kafka protocol

roles/confluent.kafka_broker/templates/server.properties.j2
=> bug fix- if running sasl_plaintext

roles/confluent.control_center/templates/control-center_log4j.properties.j2, roles/confluent.ksql/templates/ksql-server_log4j.properties.j2, roles/confluent.zookeeper/templates/zookeeper_log4j.properties.j2
Corrected variable names in the log4j configuration for ksql.  Logging now working as expected.
Tested on AWS test cluster, with soak period to confirm changes take affect properly.
=> Corrected variable names for logging.

roles/confluent.variables/defaults/main.yml
=> Corrected version.

hosts_example.yml, roles/confluent.common/defaults/main.yml, roles/confluent.common/handlers/main.yml, roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/debian_jvm.yml, roles/confluent.common/tasks/main.yml, roles/confluent.common/tasks/ubuntu_jvm.yml, roles/confluent.variables/defaults/main.yml
=> Debian disconnected

roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_connect/templates/connect-distributed.properties.j2, roles/confluent.ssl/tasks/certificate_authority.yml
Corrects the properties in connect config
=> Correct connect configs

roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.ksql/defaults/main.yml
Variable name change for clarity
=> adding internal to the variable name for clarity

all.yml, filter_plugins/filters.py, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml
Discovered that the if statements in the filters were not functioning, not sure if it has to do with my version of ansible, but this will explicitly check if the boolean == True/False now.
I also changed import -> include in the ssl role. It logs less and works better with conditionals
=> Boolean in filters bug fix

hosts_example.yml
This is simply a documentation change. I did validate that setting the variables as documented in the hosts_example works!
=> quick docs change around log.dirs prop

roles/confluent.common/defaults/main.yml, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml
Nice feature to do health checks before moving on to next component should help with discovering issues on a component by component basis and give stronger guarantee that platform is healthy when playbook completes!
tested each component
=> Health checks

tasks/certificate_authority.yml
The `use_ssh_args: yes` parameter should be added to any synchronize commands (which uses rsync) to support running Ansible through a bastion host.
This pull request adds the parameter to the "Copy Generated SSL Files Back to Ansible Host" certificate authority task. Without it, the synchronize task fails when running Ansible through a bastion host.
This fixes the issue documented in #104 but for a different task than the one referenced in the issue.
Without the change, the "Copy Generated SSL Files Back to Ansible Host" task fails for a target behind a bastion host:
```
TASK [Copy Generated SSL Files Back to Ansible Host] *******************************************************************************************************************************************************
fatal: …
```
=> Use SSH args for CA task to support bastion host

hosts_example.yml
Provide documentation on how the broker.rack property can be included in a broker deployment.
I have deployed out to an AWS cluster.
=> Added documentation on setting the broker.rack property

roles/confluent.common/tasks/main.yml, roles/confluent.control_center/tasks/health_check.yml, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/health_check.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/health_check.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.kerberos/tasks/main.yml, roles/confluent.ksql/tasks/health_check.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/health_check.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
Validated that running playbooks with --check does not error out or show changed when shouldnt. There is still work to be done with the ssl role, but that is included in separate PR
Rerunning playbook with --check on and off, this is not removing/adding any functionality
=> improvements on idempotency

roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/templates/zookeeper.properties.j2
Simple change to put two hardcoded ports into variables
Tested zookeeper install and the variables worked, not a very big change
=> zookeeper ports into vars

roles/confluent.control_center/templates/control-center.properties.j2, roles/confluent.variables_handlers/defaults/main.yml
Simple change to make c3 listener hostname configurable
Ran the install, c3 config is as it was before the change
=> removing hardcoded c3 hostname

roles/confluent.common/defaults/main.yml
=> better variables around the repos

roles/confluent.control_center/tasks/main.yml
Fixes User/Group within Control Center for RocksDB
=> Fix User/Group for Control Center

hosts_example.yml, roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_connect/tasks/confluent_hub.yml, roles/confluent.kafka_connect/tasks/connectors.yml, roles/confluent.kafka_connect/tasks/main.yml
Allows for installing Kafka Connect Connectors from both supplied archives and from the Confluent Hub.
Test Lab Env
=> Connector Install Support

hosts_example.yml
Corrects line 337 in the hosts_example.yml to reflect the correct component name. 
No testing required, as it's a simple comment update.
=> Corrected line 337 to reflect the correct component name.

hosts_example.yml
Corrected the hosts_example.yml for naming mistake.
No active issue.
No testing required, as it's a comment.
=> Corrected component name for Control Center from Connect.

roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.control_center/molecule/rbac-custom-certs-1way-mds/molecule.yml, roles/confluent.control_center/molecule/rbac-kerberos-no-ssl/verify.yml, roles/confluent.control_center/tasks/health_check.yml, roles/confluent.control_center/templates/control-center.properties.j2, roles/confluent.kafka_connect/tasks/health_check.yml, roles/confluent.kafka_connect/templates/connect-distributed.properties.j2, roles/confluent.kafka_rest/tasks/health_check.yml, roles/confluent.ksql/tasks/health_check.yml, roles/confluent.schema_registry/tasks/health_check.yml
Combined the health check tasks
molecule scenario had incorrect file path to custom certs
=> Combined the health checks and fixed molecule scenario

roles/confluent.control_center/templates/control-center.properties.j2, roles/confluent.kafka_broker/templates/server.properties.j2, roles/confluent.kafka_connect/templates/connect-distributed.properties.j2, roles/confluent.kafka_rest/templates/kafka-rest.properties.j2, roles/confluent.ksql/templates/ksql-server.properties.j2, roles/confluent.schema_registry/templates/schema-registry.properties.j2
This PR simply reformats the .properties files to match the style convention already set, no properties should be added/lost
**Test Configuration**: All test scenarios must pass
=> Rbac reformat properties files

roles/confluent.control_center/molecule/default/molecule.yml, roles/confluent.control_center/molecule/rbac-custom-certs-1way-mds/molecule.yml, roles/confluent.control_center/molecule/rbac-kerberos-no-ssl/molecule.yml, roles/confluent.control_center/tasks/rbac.yml, roles/confluent.kafka_broker/tasks/rbac.yml, roles/confluent.kafka_broker/templates/server.properties.j2, roles/confluent.kafka_connect/tasks/rbac.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/rbac.yml, roles/confluent.schema_registry/tasks/rbac.yml, roles/confluent.variables_handlers/defaults/main.yml, tasks/rbac_setup.yml, templates/kafka_client.j2
Sets the fields of the component listener based off if rbac is enabled, customers should not know about the oauth sasl protocol
Also fixes a bug where if the client listener is not fully filled out it should take the defaults
**Test Configuration**: All three rbac test scenarios must pass
=> Rbac User experience is improved, dont have to fill in the component listener

hosts_example.yml, roles/confluent.control_center/molecule/default/molecule.yml, roles/confluent.control_center/molecule/rbac-custom-certs-1way-mds/molecule.yml, roles/confluent.control_center/molecule/rbac-kerberos-no-ssl/molecule.yml, roles/confluent.kafka_broker/templates/server.properties.j2, sample_inventories/rbac_kerberos_example.yml, sample_inventories/rbac_kerberos_tls_example.yml, sample_inventories/rbac_mtls_certificates_example.yml, sample_inventories/rbac_mtls_keystore_truststore_example.yml
Updated hosts_example.yml to reflect new vars for RBAC.
Added example inventories for rbac_kerberos.*
Corrected variable name related to principals.  
Will be test via Jenkins.
=> Doc update

hosts_example.yml, roles/confluent.control_center/molecule/default/molecule.yml, roles/confluent.control_center/molecule/rbac-kerberos-no-ssl/molecule.yml, roles/confluent.control_center/molecule/rbac-scram-custom-1way/certs/hosts, roles/confluent.control_center/molecule/rbac-scram-custom-1way/molecule.yml, roles/confluent.control_center/molecule/rbac-scram-custom-1way/prepare.yml, roles/confluent.control_center/molecule/rbac-scram-custom-1way/verify.yml, roles/confluent.kafka_broker/templates/server.properties.j2, sample_inventories/rbac_kerberos_custom_certs_example.yml, tasks/rbac_setup.yml
PR is cumulative of the following:
1. Updated LDAP configuration to use a single variable to allow complete customisation
2. Corrected a bug with Ubuntu whereby Zookeeper client was not being called correctly
3. Added LDAPS testing via molecule.
Has been tested using Molecule against CENTOS7.
=> Ldaps molecule test

roles/confluent.ksql/tasks/rbac.yml
After reviewing ksql rbac docs, ksql rolebindings need to be corrected. One is missing, one is unnecessary
Docs here: https://docs.confluent.io/current/security/rbac/ksql-rbac.html#assign-roles-for-starting-ksql-server
molecule scenarios must pass
=> adding in missing sr rolebinding and removing extraneous one

roles/confluent.control_center/defaults/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.test/molecule/plaintext-rhel/molecule.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.test/tasks/check_property.yml, roles/confluent.variables/defaults/main.yml
Missing dependent package, meaning some higher version packages get pulled even if you want a lower version
=> 53 packageversion hotfix

roles/confluent.control_center/defaults/main.yml, roles/confluent.kafka_broker/templates/server.properties.j2, roles/confluent.kafka_connect/templates/connect-distributed.properties.j2, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables_handlers/vars/main.yml
Multiple bug fixes in 54 branches:
- c3 can work with less than 3 brokers
- filter plugin called with arguments in incorrect order
- missing package in package lists
- incorrect connect property
- molecule test fixed
=> 5.4 Bug Fixes

hosts_example.yml, roles/confluent.common/defaults/main.yml, roles/confluent.common/tasks/main.yml
Allow customization of the download url for confluent cli
=> Disconnected confluent cli download

sample_inventories/rbac_kerberos_custom_certs_example.yml
Corrected ldap variable in sample inventory, for rest proxy password.
Removed extraneous comment.
Ran installation with Template on RHEL 7.6.
=> Corrected ldap user variable name, and removed extraneous comment.

CONTRIBUTING.md, HOW_TO_TEST.md
Have written documentation on how to test with Molecule framework.  Have added it as a requirement to the PR documentation.
Documentation update, no testing required.
=> Added details on how to run molecule tests.

hosts_example.yml, roles/confluent.ssl/defaults/main.yml, roles/confluent.ssl/tasks/custom_certs.yml
=> Allow to use remote ssl certs

roles/confluent.kafka_connect/templates/connect-distributed.properties.j2
Connect was missing SR ssl properties
Tested with the 55 molecule mtls scenarios, properties look good, and all services started
=> Connect missing sr ssl properties

hosts_example.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/templates/kafka_server_jaas.conf.j2, roles/confluent.kafka_broker/templates/server.properties.j2, roles/confluent.test/molecule/zookeeper-digest/.gitignore, roles/confluent.test/molecule/zookeeper-digest/molecule.yml, roles/confluent.test/molecule/zookeeper-digest/verify.yml, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml, roles/confluent.zookeeper/templates/zookeeper.properties.j2, roles/confluent.zookeeper/templates/zookeeper_jaas.conf.j2
Adds digest as a zookeeper_sasl_protocol
Follows the documentation here: https://docs.confluent.io/current/security/zk-security.html#sasl-with-digest-md5
Created a new molecule scenario
=> Zookeeper digest md5 sasl auth

hosts_example.yml, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.test/molecule/plaintext-rhel/molecule.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml, tasks/copy_files.yml
This pr allows on a component level to copy files onto hosts
Added unit tests to the plaintext-rhel scenario
Other scenarios should still function
=> Generic copy files from list

roles/confluent.kafka_broker/tasks/rbac.yml
Logic to combine super users was overwriting itself on each loop entry resulting in missing super users
=> RBAC Super Users list creation bugfix

all.yml, filter_plugins/filters.py, roles/confluent.kafka_rest/tasks/health_check.yml, roles/confluent.test/molecule/certs-create.sh, roles/confluent.test/molecule/customcerts-rhel/certificate-hosts, roles/confluent.test/molecule/customcerts-rhel/molecule.yml, roles/confluent.test/molecule/kerberos-customcerts-rhel/certificate-hosts, roles/confluent.test/molecule/mtls-custombundle-rhel/molecule.yml, roles/confluent.test/molecule/mtls-customcerts-rhel/certificate-hosts, roles/confluent.test/molecule/plain-customcerts-rhel/certificate-hosts, roles/confluent.test/molecule/rbac-mtls-provided-ubuntu/certificate-hosts, roles/confluent.test/molecule/rbac-mtls-rhel8/molecule.yml, roles/confluent.test/molecule/rbac-mtls-rhel8/prepare.yml, roles/confluent.test/molecule/rbac-mtls-rhel8/verify.yml, roles/confluent.test/molecule/rbac-scram-custom-rhel/certificate-hosts, roles/confluent.test/molecule/rbac-scram-provided-debian/certificate-hosts, roles/confluent.variables_handlers/defaults/main.yml, roles/confluent.variables_handlers/vars/main.yml
Rhel8 has strong requirements on ciphersuites when tls encryption is on
zookeeper_ssl_enabled now matches ssl_enabled
Also moved variables that we dont want overwritten into vars dir
Bug fix on rest proxy health check
Bug fix on some connect properties
Added rhel8 scenario
=> Add cipher suites for rhel8

roles/confluent.control_center/tasks/health_check.yml, roles/confluent.kafka_connect/tasks/health_check.yml, roles/confluent.kafka_rest/tasks/health_check.yml, roles/confluent.ksql/tasks/health_check.yml, roles/confluent.schema_registry/tasks/health_check.yml
When using proxy settings, localhost in health checks was resolving to wrong place, better to use hostname
All molecule scenarios must still pass
=> Update healthcheck to use hostname instead of localhost

filter_plugins/filters.py, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/tasks/set_principal.yml, roles/confluent.kafka_broker/templates/kafka_client.j2, roles/confluent.kafka_broker/templates/listener.j2, roles/confluent.test/molecule/rbac-mtls-rhel8/verify.yml, roles/confluent.test/molecule/scram-rhel/verify.yml, roles/confluent.test/molecule/zookeeper-digest/verify.yml, roles/confluent.test/molecule/zookeeper-kerberos/verify.yml, roles/confluent.test/molecule/zookeeper-mtls/verify.yml, roles/confluent.variables_handlers/vars/main.yml
Switches scram 256 to 512 to be more secure
also updated an outdated verify.yml with old tests in it
All scram scenarios should work as usual
=> scram 512 instead of 256

roles/confluent.test/molecule/plaintext-rhel/molecule.yml
Removing a molecule param testing out jenkins jobs created by prs
=> 53 - jenkins test

roles/confluent.kafka_broker/tasks/main.yml
Kafka service should be enabled, to allow for reboots
Molecule scenarios must pass
=> missing service enabled on kafka

roles/confluent.common/tasks/main.yml
Include a solution to the problem not just problem
Molecule scenario must pass
=> hash merge error message improvement

roles/confluent.test/molecule/rbac-kerberos-debian/molecule.yml
This PR adds a user to login to Control Center with for the rbac-kerberos-debian scenario in molecule.
This has been tested by running the rbac-kerberos-debian role and validating that login to C3 works as expected.
=> Updated to add user for Control Center login. 

roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables_handlers/defaults/main.yml
Update the package version variable
Jenkins test will validate
=> Update to 551 version

roles/confluent.test/molecule/plaintext-rhel/verify.yml
Minor typo fix to the verify.yml
Variables role does not have that tasks file
Jenkins run will test this
=> Typo fix in molecule verify.yml

upgrade_ksql.yml
Adding back ksqldb upgrade playbook. Has an assertion that starting version is not too low
Tracking official docs change, this can come while thats in progress
Ran upgrade
=> 551 upgrade ksqldb playbook

roles/confluent.kafka_broker/defaults/main.yml
RF for audit log topic defaults to 1, should be 3 if there are 3 brokers
Checked property set
=> Fix RF for audit log topic

roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml
Adding retries to two more tasks that have been noticed to error out randomly
Ran ubuntu/debian scenario
=> Adding retries to the add confluent apt repo task

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.ssl/tasks/main.yml, roles/confluent.ssl/tasks/self_signed_certs.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/tasks/main.yml
A few minor improvements:
- adding var to enable zk jolokia ssl
- moved many http protocol variables to vars dir bc they should not be customized
- cleaner implementation ok ssl file ownership, as well as change the CN in the self signed certs
Ran the mtls-ubuntu role, which tests the ssl role, jolokia w ssl
Also ran the rbac-mtls-rhel scenario which validates that the change in CN does not impact rbac
=> Miscellaneous 60 improvements

VARIABLES.md, roles/confluent.common/defaults/main.yml, roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.variables/defaults/main.yml
Now supporting 3 repo options: confluent (default/current), custom, none (new)
Validated the backwards compatibility logic by trying various variable options and debugging the variable
=> New variable for repo configuration, includes none as option

roles/confluent.kerberos/tasks/main.yml
Ups the kerberos keytab permissions on directory/file to 750/640
Ran a kerberos scenario
=> Keytab permission bugfix

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_broker/tasks/rbac.yml, roles/confluent.kafka_connect/tasks/confluent_hub.yml, roles/confluent.kafka_connect/tasks/connectors.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.kerberos/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.ssl/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
Sets permissions:
- on config directories: 750
- on config files: 640
- on executables: 755
- on ssl dir: 755
Ran rbac scenario
=> Standardize file and directory permissions

Jenkinsfile
Undoing this change - We're taking a different approach.
=> Remove nightly lookup

upgrade_kafka_broker.yml
For 5.5.x minor version upgrades, will need the variable set in this PR
Ran manually, debugged the var
=> Missing log version variable for 5.5.x upgrades

roles/confluent.control_center/templates/control-center.properties.j2
Removes mtls conditional around c3 truststore config. Need truststore configuration when tls encryption on
=> C3 truststore config bugfix

roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.test/molecule/custom-user-plaintext-rhel/molecule.yml, roles/confluent.test/molecule/custom-user-plaintext-rhel/verify.yml, roles/confluent.test/tasks/check_ownership.yml, roles/confluent.test/tasks/check_user.yml
Linting corrections from pint merge from 5.4.0 which did not have linting checks in place.
Tests as follows:
1. Linting check and correction
2. Ran plaintext-rhel scenario.
=> Linting corrections.

roles/confluent.variables_handlers/defaults/main.yml
=> Bump version to 5.5.2

roles/confluent.control_center/templates/control-center.properties.j2
Updated the Confluent Control Center TLS properties for interacting with Schema Registry.  
This has been tested with the plain-customcerts-rhel molecule scenario.
=> Updated properties for schema-registry TLS configuration for C3

hosts_example.yml
Adds clarity to the confluent_cli_download_enabled variable
Manually viewed file post change, this is a docs bug fix
=> Minor doc update

roles/confluent.kafka_connect/tasks/health_check.yml, roles/confluent.kafka_connect/templates/connect-distributed.properties.j2, roles/confluent.kafka_rest/tasks/health_check.yml, roles/confluent.kafka_rest/templates/kafka-rest.properties.j2, roles/confluent.ksql/tasks/health_check.yml, roles/confluent.ksql/templates/ksql-server.properties.j2, roles/confluent.schema_registry/tasks/health_check.yml, roles/confluent.schema_registry/templates/schema-registry.properties.j2
Correctly configures the ssl props for SR, ksqldb, RP, and connect
Adds mtls health checks
To validate each new health check ran:
- mtls-debian
- rbac-mtls-rhel
- plain-rhel
=> Enforce component mtls in 55 branches

tasks/certificate_authority.yml
Added tags to all ca tasks to make the tag work
```
ansible-playbook -i ~/.cache/molecule/confluent.test/mtls-java11-debian/inventory all.yml --tags=certificate_authority
```
=> certificate_authority tag bugfix

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/templates/server.properties.j2, roles/confluent.test/molecule/mtls-debian/molecule.yml, roles/confluent.test/molecule/mtls-debian/verify.yml, roles/confluent.test/molecule/rbac-mtls-provided-ubuntu/molecule.yml, roles/confluent.test/molecule/rbac-scram-custom-rhel/molecule.yml
- Minor update to permissions on c3's data dir
- Also corrected the properties to configure schema validation w tls encryption
- Updated ldap properties in scenarios for ssl config. Turns out processes were relying on the java args
Ran plaintext-rhel and jenkins will test rbac scenario
Added schema validation test to mtls-debian
=> C3 data dir permissions fix && Schema validation config fix

roles/confluent.test/molecule/confluent-kafka-kerberos-customcerts-rhel/.gitignore, roles/confluent.test/molecule/confluent-kafka-kerberos-customcerts-rhel/molecule.yml, roles/confluent.test/molecule/confluent-kafka-kerberos-customcerts-rhel/prepare.yml, roles/confluent.test/molecule/confluent-kafka-kerberos-customcerts-rhel/verify.yml, roles/confluent.test/molecule/rbac-scram-custom-rhel/molecule.yml, roles/confluent.test/molecule/rbac-scram-provided-debian/molecule.yml, roles/confluent.test/tasks/check_package.yml
Added new molecule scenario confluent-kafka-kerberos-customcerts-rhel to test usage of confluent-kafka instead of confluent-server.  Will be utilized in future upgrade testing scenarios.
Have updated the following scenarios to have 3 zookeeper instances instead of 1, to facilitate upgrade testing in the future:
rbac-scram-custom-rhel
rbac-scram-provided-debian
All scenarios have been run and validated via molecule verify.
**Test …
=> Upgrade scenario

roles/confluent.test/upgrade_testing/mtls-customcerts-rhel-540-current.sh, roles/confluent.test/upgrade_testing/mtls-debian-540-current.sh, roles/confluent.test/upgrade_testing/plaintext-rhel-upgrade-540-current.sh, roles/confluent.test/upgrade_testing/upgrade.sh
This PR adds scripts to automate upgrade testing from 5.4.0 to 5.5.0.
All scenarios have been run and validated to complete the upgrade successfully.
=> Added upgrade scenarios for testing upgrades from 5.4.0 to 5.5.0.

roles/confluent.common/tasks/redhat.yml
When using custom repo files, need to make sure yum clean all runs
Tested by customer
=> Yum clean all handler missing, causing upgrade errors

roles/confluent.test/molecule/cp-kafka-plain-rhel/molecule.yml, roles/confluent.test/molecule/cp-kafka-plain-rhel/verify.yml
Adds a scenario for upgrade testing
works in conjunction with an upgrade test in the 600 branch
This scenario does succeed
=> Colocated kafka/zk with cp-kafka scenario for upgrade testing

roles/confluent.ssl/tasks/provided_keystore_and_truststore.yml
Replaces try catch with fact finding task around keystore type
Ran the rbac-scram-provided-debian scenario with both pkcs12 and jks keystores
=> Remove ssl keytool try catch

Jenkinsfile
Python packages added to jenkins agent image, this stage not needed
Jenkins run will test this
=> jenkinsfile remove python package install

roles/confluent.kafka_broker/tasks/rbac_rolebindings.yml
Fixes url for mds for multi rbac deployment
Ran multi rbac test
=> MDS Url bugfix

sample_inventories/ccloud.yml
Adds a sample inventory file, showing how to connect to confluent cloud kafka and schema registry
Copied working inventory and removed sensitive info
=> CCloud sample inventory

HOW_TO_TEST.md
Updating pip install due to deprecation of docker driver
https://github.com/ansible-community/molecule/pull/2811
Fixes #502
=> Updated Prerequisites for the test section

roles/confluent.ksql/templates/ksql-server.properties.j2
Minor syntax correction in ksql-server.properties, change : to =.
Validated with CI integration.
=> Corrected : to = in properties.

roles/confluent.variables/vars/main.yml
Missed quotation marks in merging
yamllint ran
=> Fixed missing quotes bug

roles/confluent.variables/vars/main.yml
Replaces hardcoded string with proper variable
Ran rbac scenario
=> Fix hardcoded variable

roles/confluent.variables/vars/main.yml
Simple property add to enable tracking of cp-ansible usage
TODO validation
=> Add property for tracking of cp-ansible usage

roles/confluent.zookeeper/templates/zookeeper.properties.j2
On fips enabled hosts need these properties for zk tls to work
Properties validated by customer
=> Missing zk fips properties

roles/confluent.variables_handlers/defaults/main.yml
Simple variable change representing the 5.5.3 cp release
rbac-scram-custom-rhel
=> updating for 553 release

roles/confluent.common/handlers/main.yml, roles/confluent.common/tasks/redhat.yml, tasks/upgrade_component.yml, upgrade_kafka_broker.yml, upgrade_ksql.yml, upgrade_zookeeper.yml
Duplicates the work in https://github.com/confluentinc/cp-ansible/pull/511
But for the 600 branches
=> 600 update cache bug

roles/confluent.test/molecule/plaintext-basic-rhel/molecule.yml, roles/confluent.test/molecule/plaintext-rhel/molecule.yml
Test validates basic auth custom configuration on connect
updated a molecule scenario
=> Basic auth molecule scenario working for connect

roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.test/molecule/archive-scram-rhel/molecule.yml
Path to binary invalid for scram install
Updated a scenario to test, also rbac-scram-custom-rhel will test non archive scram
=> Archive scram Bugfix

VARIABLES.md, control_center.yml, kafka_broker.yml, kafka_connect.yml, kafka_rest.yml, ksql.yml, roles/confluent.variables/defaults/main.yml, zookeeper.yml
=> Rename reconfiguration variables

roles/confluent.kafka_broker/tasks/ordered_restart.yml, tasks/create_ordered_kafka_groups.yml
=> Jolokia Basic Auth added for Get ActiveControllerCount Handler

roles/confluent.common/tasks/debian.yml
This PR allow to support Debian 10 Buster.
Tested with Azure VM Debian 10 Buster.
- [ X I have performed a self-review of my own code
=> Feature : Support debian buster

VARIABLES.md, roles/confluent.common/tasks/main.yml, roles/confluent.test/molecule/archive-scram-rhel/molecule.yml, roles/confluent.test/molecule/archive-scram-rhel/prepare.yml, roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
Adds two new variables `archive_owner` and `archive_group`
Updated a test scenario
=> Set Ownership of the archive dir

all.yml
Small typo fix
automated jenkins job should validate
=> Typo fix in kafka connect spelling

roles/confluent.common/tasks/main.yml
Small bugfix that will resolve jenkins failures. Will get merged up
Jenkins run will test
=> Retries should be on the get_url task not shell

roles/confluent.common/tasks/main.yml, tasks/certificate_authority.yml
Now that tasks run on the controller, need to make sure those tasks do not try to switch to root. Future work is to be more specific around which tasks require become: true/false. Before this PR this is the error message observed:
```
TASK [Register if CA Key Exists on Ansible Controller] *********************************************************************************************************
Friday 29 January 2021  12:43:09 -0800 (0:00:00.186)       0:00:00.223 ********
fatal: [ip-172-31-43-134.us-west-2.compute.internal -> localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
Adds retries to the confluent cli download task. Will resolve failures like: …
=> Bug fix around local tasks attempting to become root

VARIABLES.md, roles/confluent.test/molecule/mtls-java11-rhel/molecule.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
- Adds missing capability to disable SR validation - most likely want to backport this
- Updates a test bc fips has known bug
=> 61x Disable Schema Validation flag

upgrade_kafka_broker.yml, upgrade_kafka_connect.yml, upgrade_kafka_rest.yml, upgrade_ksql.yml, upgrade_schema_registry.yml
- Updates upgrade playbook with correct path to handlers
- Adds logic for kafka 2.7 protocol version
- Reads in server.properties to see if admin api is already enabled or not, updates the disabling logic accordingly
- For other upgrade playbooks adds case insensitivity to the MTLS check, found some properties could be set to True
=> Kafka upgrade playbook bugfixes

roles/confluent.kafka_broker/tasks/main.yml
Minor bugfix to make sure scram users are created using ZK Acls
Ran zookeeper-digest scenario
rbac-scram-custom-rhel will test non acl scenario
=> Scram user creation with ZK ACLs

roles/confluent.kafka_broker/templates/kafka_server_log4j.properties.j2
Adds whats in the out of the box log4j properties to our template
Ran plain-rhel scenario and manually validated the log4j properties
=> ANSI-701 Kafka's log4j should match what is shipped with our packages

roles/confluent.kafka_connect/files/kafka_connect.yml
Corrects a comment in connect's prometheus config
Non functional change, jenkins job is enough
=> MINOR: fix example line of kafka connect jmx rule

VARIABLES.md, roles/confluent.variables/defaults/main.yml
Changes deployment strategy default to parallel which is more backwards compatible with how it worked in previous versions
Ran provisioning playbook a few times
=> ANSI-700 Updated the default deployment strategy to parallel

roles/confluent.common/defaults/main.yml
Use releasever variable instead of hardcoding for rhel7
Fixes # (https://github.com/confluentinc/cp-ansible/issues/558)
jenkins job will test it
=> To support rhel8, use the releasever yum var

roles/confluent.ksql/tasks/rbac.yml, roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/Dockerfile-ubuntu.j2, roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.test/molecule/confluent-kafka-kerberos-customcerts-rhel/verify.yml, roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml, roles/confluent.test/molecule/plain-erp-tls-rhel/verify.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
Simple version update for the 6.0.2 release
Ran all 40 molecule scenarios successfully
=> Update package version variable for release

HOW_TO_TEST.md
The PR added a line break between 2 commands. 
nit.
=> New line break added in HOW_TO_TEST.md 

HOW_TO_TEST.md
This PR outline the ability to use Molecule as a container.
=> adding Container option for Molecule

upgrade_kafka_broker_log_format.yml
Fix wrong variable name. Should be in accordance with upgrade documentation
Fixes #584 
Verified  running playbook in check mode according to the upgrade documentation.
=> fix #584: Variable name should match input variable in documentation

upgrade_kafka_broker.yml
Minor PR to remove a redundant task convered by the previous task. Probably introduced by merging https://github.com/confluentinc/cp-ansible/commit/ed39a56 from the `6.0.2-post` branch up?
=> fix: Remove redundant task introduced by merge commit 6cac39e

sample_inventories/ccloud.yml
Minor typo fix in sample inventory
Fixes # (https://github.com/confluentinc/cp-ansible/issues/600)
Sample inv, manually reviewed
=> Typo fix on c3 properties in sample ccloud inventory

roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/archive-scram-rhel/molecule.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.test/molecule/provided-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Updated 6.1.x branch for 6.1.1 release
Some bug fixes
Updates to tests
Ran all molecule scenarios successfully
=> Update 6.1.x branch for 611 release

control_center.yml, kafka_connect.yml, kafka_connect_replicator.yml, kafka_rest.yml, ksql.yml, roles/confluent.variables/vars/main.yml
Adds missing basic auth properties for schema validation when rbac is enabled
Corrects some task name typoss
jenkins job
=> ANSI-763 Missing basic auth props for schema validation

roles/confluent.kafka_broker/files/kafka.yml, roles/confluent.kafka_connect/files/kafka_connect.yml, roles/confluent.ksql/files/ksql.yml, roles/confluent.zookeeper/files/zookeeper.yml
This change includes updates to the jmx-exporter configurations performed on the jmx-monitoring-stacks by the team. The one big complaint was the Broker metrics scrapes were very different and were not dashboarding properly. Hence, a big difference in the Broker configs. Others are minor fixes and addons to sync cp-ansible with jmx-monitoring-stacks (current state)
=> Bug fix and updates to JMX-exporter Scrape configs

CONTRIBUTING.md, DEVELOPMENT_GUIDE.md, README.md
Dev guide for contributors, some edits to other markdown files.
Reflects current standards. This document will grow with the repo!
Need to review the markdown file on my branch
=> Added a dev guide for contributors

tasks/upgrade_component.yml, upgrade_control_center.yml, upgrade_kafka_broker.yml, upgrade_kafka_connect.yml, upgrade_kafka_rest.yml, upgrade_ksql.yml, upgrade_schema_registry.yml, upgrade_zookeeper.yml
When setting mode, we must also set owner and group or else the ownership is set to root
Running thru upgrade with customer
=> 61x upgrade ownership bugfix

.gitignore
This is just a minor convenience addition to .gitignore for contributors using IntelliJ IDEA - as I do.
=> Add IntelliJ IDEA module files (*.iml) to .gitignore

roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables_handlers/defaults/main.yml
Updates the package version to latest patch
Jenkins will validate
=> 5.5.4 Release

sample_inventories/kafka_connect_replicator.yml
This PR adds an example inventory file for how to configure Kafka Connect Replicator.
This has been validated using molecule test scenarios and reformatted to reflect a standard ansible inventory.  Specifically its pulled from the kafka-connect-replicator-plain-kerberos-rhel scenario.
=> Initial add of kafka connect replicator sample inventory file.

roles/confluent.common/tasks/host_validations.yml, roles/confluent.common/tasks/main.yml, roles/confluent.common/vars/main.yml
Improved the error messages for host validations
Improved the gather facts efficiency by removing loop
- [] New feature (non-breaking change which adds functionality)
=> Host validations- improved error messages, added sudo check

roles/confluent.test/molecule/custom-user-plaintext-rhel/verify.yml
Minor bugfix to this scernio `custom-user-plaintext-rhel` 's verify tasks
custom-user-plaintext-rhel now succeeds
=> 62x molecule test bugfix

VARIABLES.md, roles/confluent.common/tasks/rbac_setup.yml, roles/confluent.common/tasks/secrets_protection.yml, roles/confluent.control_center/defaults/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.ksql/defaults/main.yml, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.ssl/defaults/main.yml, roles/confluent.ssl/tasks/create_keystore_and_truststore.yml, roles/confluent.ssl/tasks/create_keystores_from_certs.yml, roles/confluent.ssl/tasks/custom_certs.yml, roles/confluent.ssl/tasks/export_certs_from_keystore_and_truststore.yml, roles/confluent.ssl/tasks/import_ca_chain.yml, roles/confluent.ssl/tasks/self_signed_certs.yml, roles/confluent.test/molecule/mtls-customcerts-rhel/molecule.yml, roles/confluent.test/molecule/mtls-customcerts-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml, tasks/certificate_authority.yml
Created the `ssl_file_directory` variable for making the directory to put all ssl files into
Updated the `mtls-customcerts-rhel` scenario to test out updating of the ssl_file_dir variable, both with/without trailing /
=> Configurable ssl file directory

VARIABLES.md, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Documents the variable `confluent_package_version` and no longer need to set confluent_repo_version, it is built from the package version variable
Jenkins job confirms this logic
=> Document confluent_package_version

roles/confluent.test/molecule/Dockerfile-debian.j2, roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/Dockerfile-ubuntu.j2, roles/confluent.test/molecule/Dockerfile.j2, roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
Updates the `confluent_package_version` variable for latest release
Updates test code for 620 release as well
Ran all molecule scenarios
=> 6.2.0 Release

VARIABLES.md, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.test/molecule/zookeeper-digest/molecule.yml, roles/confluent.test/molecule/zookeeper-mtls/molecule.yml, roles/confluent.test/molecule/zookeeper-mtls/verify.yml, roles/confluent.test/tasks/check_property.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Adds a variable for zk chroot: `zookeeper_chroot`
Must update the sasl scram creation bash commands with this variable
Fixes # (https://github.com/confluentinc/cp-ansible/issues/691)
update zookeeper-mtls
=> Zookeeper chroot capability

roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
Changing package version variable for latest 6.1.2 release
Successfully ran the test suite
=> 612 Package Version update

roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables_handlers/defaults/main.yml
Up'd the version to 5.5.5
Jenkins job will validate
=> 555 Package version change

roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
Updates the package version for the 6.0.3 release
Jenkins will test
=> 6.0.3 Package Version update

all.yml
In order to support the move to collections, need to make sure all paths are relative:
https://docs.ansible.com/ansible/latest/dev_guide/migrating_roles.html#migrating-other-role-plugins-to-a-collection
Jenkins job will test
=> For playbook imports, use relative paths

roles/confluent.variables/vars/main.yml
Updated Rest Proxy monitoring interceptor from `confluent.monitoring.interceptor.bootstrap.servers` to `client.confluent.monitoring.interceptor.bootstrap.servers`
Allows correct monitoring of Rest Proxy.
Validate running molecule scenario rbac-kerberos-debian.
=> Updated Rest Proxy monitoring interceptor to use the "client." prefix

roles/confluent.common/defaults/main.yml
Updated RedHat packaging to reflect official Confluent documentation found here: https://docs.confluent.io/platform/current/installation/installing_cp/rhel-centos.html#get-the-software
Validated by running molecule scenario cp-kafka-plain-rhel
Single cluster no security.  Validated that correct packages are installed via yum.
[root@kafka-broker1 /]# yum list installed|grep confluent
confluent-ce-kafka-http-server.noarch      6.1.2-1                    @Confluent
confluent-common.noarch                    6.1.2-1                    @Confluent
confluent-kafka.noarch                     6.1.2-1                    @Confluent
confluent-kafka-rest.noarch                6.1.2-1                    @Confluent
confluent-metadata-service.noarch …
=> Updated redhat packaging.

Jenkinsfile
Using new jenkins image with ansible 2.11 and latest molecule
Jenkins job will validate this new image, same tests should pass as before
=> Update jenkins image

VARIABLES.md, roles/confluent.variables/defaults/main.yml, tasks/certificate_authority.yml
This update allows an end user to have finer grain control over updating the pem files used for token generation when RBAC is enabled.
Previously pem files were updated when the CA was updated, there was no way to update both items independently.
This was validated using rbac-mtls-rhel scenario.  The scenario was initially run to setup a healthy cluster.  We then added additional variables and re-ran the scenario, updating it, to validate that all use cases were supported.
Tested with rbac-mtls-rhel scenario by adding the following vars:
Just Creating new CA:
var: regenrate_ca: true 
TASK [Create Certificate Authority] ********************************************
[33mchanged: [zookeeper1][0m
TASK [Create MDS Private key] …
=> Update to allow regeneration of token pem files

roles/confluent.kafka_connect_replicator/tasks/main.yml, sample_inventories/kafka_connect_replicator.yml
Updated replicator example file to include vars block as well as corrected indentation.  Also corrected a permissions problem in replicator on systemd overrides.
Validated against kafka-connect-replicator-mtls-scram-rhel scenario.
=> Corrected replicator example to include vars.

roles/confluent.variables/vars/main.yml
Missing ksql logging RF property added
Manually validated
=> Adding RF property for when ksql logging enabled

DEVELOPMENT_GUIDE.md, HOW_TO_TEST.md
```
mkdir -p ansible_collections/confluent/platform
git clone https://github.com/confluentinc/cp-ansible.git ansible_collections/confluent/platform
```
Relates to # (https://github.com/confluentinc/cp-ansible/issues/613)
Just a docs update, needs a read thru by reviewer
=> Collections Dev Guide Update

molecule/kafka-connect-replicator-plain-kerberos-rhel/prepare.yml
This fixes an unresolved merge conflict after merging 6.2.x up to 7.0.x.
Ran ` yamllint -c .yamllint -f colored .` locally.
=> Fix unresolved merge conflict

VARIABLES.md, doc.py
Role names lost the `confluent.` in them, breaking the script
Running the script and reviewing the outputted files is the test
=> Corrected documentation script

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
This PR updates the SystemD service files to be owned by the root user as per security best practices.
This change has been validate using the mtls-customcerts-rhel scenario.
=> Changed ownership of systemD files to root.

roles/confluent.kafka_broker/tasks/main.yml
Updated restart call on kafka broker due to merge conflict.
Validated with rbac-scram-custom-rhel scenario.
=> Corrected restart of kafka broker, due to merge conflict.

VARIABLES.md, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_consumer.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_monitoring.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_producer.yml
This PR updates replicator playbooks to run in --check mode.
Validated with kafka-connect-replicator-mtls-scram-rhel in check mode.
=> Replicator check mode

molecule/Dockerfile-debian10-archive.j2, molecule/Dockerfile-debian10.j2, molecule/archive-plain-debian10/molecule.yml, molecule/archive-plain-debian10/verify.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/.gitignore, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/certificate-hosts, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/converge.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/prepare.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/topic_data_creation.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/verify.yml, roles/common/tasks/host_validations.yml
This PR adds two additional molecule scenarios to validate that Debian 10 works on the 7.0 release.
The following scenarios have been added:
archive-plain-debian10
rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10
archive-plain-debian10: Installs the complete Confluent Platform via archive on Debian 10.
rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10: Installs two clusters, and stands up replicator between them and replicates data.
=> WIP - Molecule Scenarios to test Debian10 support.

molecule/Dockerfile-ubuntu2004-archive.j2, molecule/Dockerfile-ubuntu2004.j2, molecule/archive-plain-ubuntu2004/molecule.yml, molecule/archive-plain-ubuntu2004/verify.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/.gitignore, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/certificate-hosts, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/converge.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/prepare.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/topic_data_creation.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/verify.yml, roles/common/tasks/host_validations.yml
This PR adds support and testing for Ubuntu2004 on CP-Ansible 7.0.0.
Have added the following two scenarios:
rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004
archive-plain-ubuntu2004
=> WIP - Ubuntu 20 support

test_scripts/confluent-kafka-kerberos-customcerts-rhel-upgrade-550-current.sh, test_scripts/cp-kafka-plain-rhel-upgrade-550-current.sh, test_scripts/minor-release-plaintext-rhel-upgrade-540-54x.sh, test_scripts/minor-release-rbac-scram-custom-rhel-upgrade-550-55x.sh, test_scripts/minor-release-rbac-scram-custom-rhel-upgrade-600-60x.sh, test_scripts/minor-release-rbac-scram-custom-rhel-upgrade-610-61x.sh, test_scripts/minor-release-rbac-scram-custom-rhel-upgrade-620-62x.sh, test_scripts/mtls-customcerts-rhel-540-current.sh, test_scripts/mtls-debian-540-current.sh, test_scripts/plaintext-rhel-upgrade-540-current.sh, test_scripts/rbac-scram-custom-rhel-upgrade-550-current.sh, test_scripts/rbac-scram-provided-debian-upgrade-550-current.sh, test_scripts/upgrade.sh
Updated upgrade scenarios with new variables and logic to handle 6.2.0 release and later, which no longer includes upgrade playbooks.
Upgrade scenarios can now set variables as to which method to use, depending on the versions being upgraded from/to.
This has been validated by running the following scenario:
minor-release-rbac-scram-custom-rhel-upgrade-620-62x.sh
=> Updated scripts with new vars and logic

roles/common/tasks/host_validations.yml, roles/common/tasks/main.yml
This PR adds additional host validations:
1. Checks that a supported version of ansible installed
2. Checks that the /tmp directory is available on all hosts
This has been validated by running the following scenarios:
rbac-mtls-rhel8
mtls-java8-ubuntu
=> Added additional host validations

.bumpversion.cfg, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables_handlers/defaults/main.yml
=> Bump Version: 5.4.3 → 5.4.5

.bumpversion.cfg, roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
=> Bump Version: 6.0.3 → 6.0.4

.bumpversion.cfg, roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> Bump Version: 6.1.2 → 6.1.3

.bumpversion.cfg, roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> Bump Version: 6.2.0 → 6.2.1

.bumpversion.cfg, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables_handlers/defaults/main.yml
=> Bump Version: 5.5.5 → 5.5.6

roles/confluent.test/molecule/mtls-ubuntu-acl/molecule.yml, roles/confluent.test/molecule/mtls-ubuntu-acl/verify.yml
Include a molecule scenario to test and showcase how to use cp-ansible for ACL configuration.
=> feat: Add molecule scenario for mtls with ACL for authorization

.config/molecule/config.yml
With the latest molecule version 3.5.1, `molecule test -s plain-rhel` was erroring out with:
```
Could not find or access '/home/centos/repos/ansible_collections/confluent/platform/molecule/confluent.platform.all' on the Ansible Controller.
```
molecule 3.3.0 was working, but the simple solution is to add ANSIBLE_COLLECTIONS_PATH env var to molecule configs, and now things are working with 3.5.1
Tested with:
```
% molecule --version
molecule 3.5.1 using python 3.9
ansible:2.11.5
delegated:3.5.1 from molecule
docker:1.0.2 from molecule_docker requiring collections: community.docker>=1.8.0
% ansible --version
ansible [core 2.11.5]
config file = None
configured module search path = ['/Users/dbove/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location …
```
=> Add ANSIBLE_COLLECTIONS_PATH env var to molecule config

.bumpversion.cfg, VARIABLES.md, galaxy.yml, molecule/Dockerfile-debian.j2, molecule/Dockerfile-debian10-archive.j2, molecule/Dockerfile-debian10.j2, molecule/Dockerfile-tar.j2, molecule/Dockerfile-ubuntu.j2, molecule/Dockerfile-ubuntu2004.j2, molecule/Dockerfile.j2, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Prepares cp-ansible for the CP 7.0.0 Release.
This change also updates bump2version's config to update renamed files that contain variables used to target a certain version-install of CP.
=> build: Prepare for CP 7.0.0 Release

molecule/kafka-connect-replicator-plain-kerberos-rhel/molecule.yml
1. Update sasl_protocol  
```
mds_broker_listener:
sasl_protocol: none
```
2. Added truststoe and keystore password
```
kafka_connect_replicator_truststore_storepass: confluenttruststorepass
kafka_connect_replicator_keystore_storepass: confluentkeystorestorepass
```
Fixes #ANSING928
`molecule --debug converge -s kafka-connect-replicator-plain-kerberos-rhel`
```
mds-kafka-broker1          : ok=70   changed=0    unreachable=0    failed=0    skipped=60   rescued=0    ignored=0
mds-kafka-broker2          : ok=63   changed=0    unreachable=0    failed=0    skipped=42   rescued=0    ignored=0
mds-kafka-broker3          : ok=63   changed=0    unreachable=0    failed=0    skipped=42   rescued=0    ignored=0 …
```
=> Fix test failure - kafka-connect-replicator-plain-kerberos-rhel

roles/kafka_broker/tasks/dynamic_groups.yml
=> double pipes need fixing

roles/zookeeper/tasks/dynamic_groups.yml
=> Backslash hotfix

README.md
Updated the references in README.md to other files in this repo to refer to this branch rather than the 6.0.x branch.
I refreshed my browser and checked that when I clicked on the links it went to the correct branch in the confluentinc repo
=> Updated README.md references to refer to THIS branch.

README.md
Links in this file were referring to files in differnt branches which
caused me to miss varialbes in the new branch. Fixing those refernces.
=> Updated README.md to ensure links go to the same branch.

.gitignore, roles/confluent.variables/defaults/main.yml
There is a breaking change in Confluent CLI v2. This change breaks the secret protection across the branches. More details can be found [here](https://docs.confluent.io/confluent-cli/current/migrate.html#breaking-changes-for-confluent-cli)
We also have a guideline for CLI interoperability [here](https://docs.confluent.io/platform/current/installation/versions-interoperability.html#confluent-cli) Based on this all the CP from 6.x.y to 7.x.y should be compatible to 1.43.0
This change would unblock users to use secret protection and rbac features on the existing versions. 
Executed scenario (archive-scram-rhel) - 
```
TASK [confluent.kafka_broker : Create Secrets Protection Directory] ************
ok: [kafka-broker1]
TASK [confluent.kafka_broker : Copy security.properties …
```
=> Use fixed version of cli

roles/confluent.test/molecule/multi-ksql-connect-rhel/molecule.yml, roles/confluent.test/molecule/multi-ksql-connect-rhel/verify.yml
Update the connector name in scenario `multi-ksql-connect-rhel` to `VerifiableSinkConnector`
`molecule --debug converge -s multi-ksql-connect-rhel`
Local docker environment
=> Fix Test connector plugin

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.kafka_rest/tasks/restart.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
Add tag for health check task for each component. This would help to run a regular health check for all components. 
The health check will still be controlled by each component based on the variable <component>_health_checks_enabled
This would address the PR https://github.com/confluentinc/cp-ansible/pull/792 and  https://github.com/confluentinc/cp-ansible/pull/683
```
molecule converge -s plaintext-rhel -- --skip-tags package --tags health_check
```
```
control-center1            : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0
kafka-broker1              : ok=1    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0 …
```
=> Add health check tag for all component 

roles/confluent.kafka_broker/tasks/set_principal.yml
This PR resolves a merge conflict that resulted in a new error handling task not being merged.
=> Correction to merge conflict that saw the removal of error validation check.

roles/confluent.common/tasks/redhat.yml
Add proxy to redhat yum repository configuration file
To enable Proxy Settings for Yum configuration on a specifique repo like "confluent" we need to add the proxy configuration to the redhat yum repository delivered by this playbook.
Even with proxy_env settings enabled it's impossible to run yum install, we need to fix this task and add the proxy config on the redhat yum repo config
before setting proxy
```yml
- name: Add Confluent Dist Yum Repo
yum_repository:
name: Confluent.dist
file: confluent
description: "Confluent repository (dist)"
baseurl: "{{confluent_common_repository_redhat_dist_baseurl}}"
gpgcheck: "{{confluent_common_repository_redhat_dist_gpgcheck}}"
gpgkey: "{{confluent_common_repository_redhat_dist_gpgkey}}"
enabled: …
```
=> Add proxy to redhat repository

molecule/Dockerfile-debian-java8.j2, molecule/Dockerfile-rhel-java8.j2, molecule/Dockerfile-ubuntu-java8.j2, molecule/mtls-java8-debian/molecule.yml, molecule/mtls-java8-rhel/molecule.yml, molecule/mtls-java8-ubuntu/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml
1. A few scenario was supposed to use java8, however those were using
java 11
2. Most of the failing RHEL scenario was directly using the geerlingguy images
3. A few configuration update in molecule scenarios
Fixes # ([7.0.1 testing](https://confluentinc.atlassian.net/browse/ANSIENG-959))
Verified the results on local environment
Local docker environment
=> Test Fix: Update molecule scenarios to use correct java/os

roles/confluent.kafka_broker/tasks/set_principal.yml
There is an unwanted debug message in the file. Removing the same in this commit
verified the scenario `rbac-kerberos-debian` locally.
=> Remove unwanted debug message

.bumpversion.cfg, .gitignore, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables_handlers/defaults/main.yml
Update versions to consume CP release 5.5.7
Verified with staging binary url
=> 5.5.7 release : Bump versions

.bumpversion.cfg, .gitignore, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables_handlers/defaults/main.yml
Update versions to consume CP release 5.4.6 
Verified with staging binary url
=> 5.4.6 release : Bump versions

.bumpversion.cfg, VARIABLES.md, hosts_example.yml, roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.kafka_broker/tasks/set_principal.yml, roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.test/molecule/confluent-kafka-kerberos-customcerts-rhel/verify.yml, roles/confluent.test/molecule/custom-user-plaintext-rhel/verify.yml, roles/confluent.test/molecule/multi-ksql-connect-rhel/verify.yml, roles/confluent.test/molecule/rbac-mtls-rhel/verify.yml, tasks/certificate_authority.yml
Fixes issues related to following Scenarios
- archive-scram-rhel (Verify's version check was not linked with bumpversion)
- confluent-kafka-kerberos-customcerts-rhel (Verify was looking for a hardcoded verison check for package, which was not needed)
- custom-user-plaintext-rhel (Expecting a OS based heck, gather_facts required)
- multi-ksql-connect-rhel (kafka-connect3 was ssl enabled, verify should use https)
- rbac-mtls-rhel (Verify was missing certs to connect to the server)
- mtls-java11-ubuntu (added apt update and apt install gnupg2)
- mtls-java11-debian (added apt update and apt install gnupg2)
Tested following scenarios
- archive-scram-rhel
- Test result: Successful Molecule Converge and verify
- confluent-kafka-kerberos-customcerts-rhel
- Test result: Successful …
=> 6.0.5 verify fixes

roles/kafka_broker/tasks/set_principal.yml
Update the kafka broker listener name. 
Local scenario run
`molecule test -s rbac-scram-custom-rhel`
Docker environment.
=> Fix kafka listener name

.bumpversion.cfg, roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
Bump version to 6.0.5
Verified with scenarios running against staging url
Docker based environment
=> Bump Version: 6.0.4 → 6.0.5

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Bump Version: 6.1.3 → 6.1.4
This PR will enable the 6.1.4 patch release of cp-ansible. 
All scenarios has been verified with
=> Bump Version: 6.1.3 → 6.1.4

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/Dockerfile-tar.j2, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Bump Version: 6.2.1 → 6.2.2
This PR will enable the 6.2.2 patch release of cp-ansible.
All scenarios has been verified with
#Test Configuration:
=> Bump Version: 6.2.1 → 6.2.2 

.bumpversion.cfg, VARIABLES.md, galaxy.yml, molecule/Dockerfile-tar.j2, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Bump Version:7.0.0 → 7.0.1
This PR will enable the 7.0.1 patch release of cp-ansible.
All scenarios has been verified with
=> Bump Version: 7.0.0 → 7.0.1

roles/confluent.test/molecule/Dockerfile-debian.j2, roles/confluent.test/molecule/Dockerfile-ubuntu.j2, roles/confluent.test/molecule/Dockerfile.j2
Fixes the installation versions used in the yum install in all Dockerfiles.
As part of release readiness for patch 5.5.7
=> Fix install version in Dockerfiles

.bumpversion.cfg, roles/confluent.test/molecule/Dockerfile-debian.j2, roles/confluent.test/molecule/Dockerfile-ubuntu.j2, roles/confluent.test/molecule/Dockerfile.j2
This fixes the versions in Dockerfiles and updates bumpversion.cfg
=> Fix versions in Dockerfiles and bumpversion.cfg

health_check.yml
Similar to `fetch_logs.yml`, this `health_check.yml` playbook allow users to run health checks on demand to validate CP is running properly. 
=> Add playbook to health check on demand

playbooks/health_check.yml, roles/common/tasks/redhat.yml, roles/common/templates/confluent.repo.j2, roles/common/vars/main.yml
This is a merge PR from 6.0.x to 7.0.x. Which adds https://github.com/confluentinc/cp-ansible/pull/834  and https://github.com/confluentinc/cp-ansible/pull/792 
1. it resolves the merge conflict for roles/common/tasks/redhat.yml
2. Added client URL for 7.0.x branch
Local execution of 
` molecule --debug converge -s rbac-scram-custom-rhel`
Docker based environment
=> fix: fully manage yum confluent.repo file

roles/confluent.kafka_connect/tasks/rbac.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_consumer.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_producer.yml
This PR fixes a few formatting issue for rbac_replicator task
Fixes # (ANSIENG-998)
```
TASK [confluent.kafka_connect_replicator : Configure RBAC on Replicator configuration] ***
included: /Work/repos/ansible_collections/confluent/platform/roles/confluent.kafka_connect_replicator/tasks/rbac_replicator.yml for kafka-connect-replicator1
TASK [confluent.kafka_connect_replicator : Create SSL Certificate Directory] ***
--- before
+++ after
@@ -1,4 +1,4 @@
{
"path": "/var/ssl/private/kafka_connect_replicator",
-    "state": "absent"
+    "state": "directory"
}
changed: [kafka-connect-replicator1]
TASK [confluent.kafka_connect_replicator : Copy in MDS Public Pem File] ********
changed: [kafka-connect-replicator1]
TASK [confluent.kafka_connect_replicator : Grant Confluent Replicator User …
```
=> Fix formatting issue

sample_inventories/client_listener_for_ldap_users.yml
Sample inventory for auth of clients using LDAP
Derived from the inventory put together at a client site.
=> sample inventory for authenticating clients using LDAP

tasks/certificate_authority.yml
The task APT is failing for Debian as its not able to find the variable `ansible_os_family`. This PR adds task to Gather OS facts before running the apt update. 
```
TASK [Register if CA Cert Exists on Ansible Controller] ************************
ok: [zookeeper1 -> localhost]
TASK [Apt update] **************************************************************
fatal: [zookeeper1]: FAILED! => {"msg": "The conditional check 'ansible_os_family == \"Debian\"' failed. The error was: error while evaluating conditional (ansible_os_family == \"Debian\"): 'ansible_os_family' is undefined\n\nThe error appears to be in '/Users/neerajsharma/Work/repos/ansible_collections/confluent/platform/playbooks/tasks/certificate_authority.yml': line 25, column 3, but may\nbe elsewhere in the file depending on the …
```
=> Fix apt update failure

molecule/archive-plain-debian10/molecule.yml, molecule/archive-plain-ubuntu/verify.yml, molecule/archive-plain-ubuntu2004/molecule.yml, molecule/archive-plain-ubuntu2004/verify.yml, molecule/mtls-java8-debian/molecule.yml, molecule/mtls-java8-rhel/molecule.yml, molecule/mtls-java8-ubuntu/molecule.yml, molecule/mtls-ubuntu/verify.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/verify.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/verify.yml, molecule/zookeeper-kerberos-rhel/verify.yml, molecule_doc.py, molecule_scenarios.md
This PR updates the molecule documentation script to point to the correct paths on post 7.0 branches, as the project structure has changed.
It also corrects/adds some additional documentation to a few of the scenarios specific to post 7.0 release.
This has been validated by running pythong molecule_doc.py and validating that molecule_scenarios.md was correctly updated.
=> Updated molecule documentation script to point to correct path.

sample_inventories/ccloud_self_managed_schema_registry.yml
This is primarily a doc change.
=> (docs): Add ccloud without SR example

molecule/Dockerfile-debian-java8.j2, molecule/Dockerfile-debian.j2, molecule/Dockerfile-debian10-archive.j2, molecule/Dockerfile-debian10.j2, molecule/Dockerfile-ubuntu-java8.j2, molecule/Dockerfile-ubuntu.j2, molecule/Dockerfile-ubuntu2004.j2, molecule/Dockerfile.j2, roles/variables/defaults/main.yml
Schema registry plugins was packaged into CP 7.0+. This PR is to install confluent-schema-registry-plugins in docker file to make that available. Similar to https://github.com/confluentinc/schema-registry-images/pull/53.
=> Adding schema-registry-plugins in docker files

roles/confluent.ssl/tasks/export_certs_from_keystore_and_truststore.yml
https://confluentinc.atlassian.net/browse/ANSIENG-1036
=> Standardise case of keytool type when exporting certs

roles/confluent.ssl/tasks/export_certs_from_keystore_and_truststore.yml
=> ANSIENG-1036

sample_inventories/client_listener_for_ldap_users.yml
This fixes invalid yaml syntax, probably introduced in https://github.com/confluentinc/cp-ansible/pull/761. It is making CI for another PR fail.
=> Fix invalid yaml

molecule/mtls-java8-ubuntu/molecule.yml
Add test coverage for Ubuntu20. This is covered in supported Operating System [list](https://docs.confluent.io/platform/7.0.0/installation/system-requirements.html#software) for 7.0.0 onwards
` molecule --debug converge -s mtls-java8-ubuntu`
Local docker setup
```
control-center1            : ok=68   changed=29   unreachable=0    failed=0    skipped=35   rescued=0    ignored=0
kafka-broker1              : ok=73   changed=34   unreachable=0    failed=0    skipped=43   rescued=0    ignored=0
kafka-broker2              : ok=73   changed=34   unreachable=0    failed=0    skipped=40   rescued=0    ignored=0
kafka-broker3              : ok=73   changed=34   unreachable=0 …
```
=> Add test for Ubuntu20

molecule/certificates.yml, molecule/certs-create.sh, roles/common/tasks/host_validations.yml, roles/common/tasks/main.yml
This PR adds an additional host check which validates that custom certificates match properly before deploying the platform.  It only runs when custom certs are enabled.
This PR also make a few minor changes to SSL generation scripts, cosmetic cleanup.
ANSIENG-1029
This has been validated by running the mtls-customcerts-rhel scenario and validating that the certificates match:
`TASK [confluent.platform.common : Retrieve SSL key hash] ***********************
changed: [kafka-broker3 -> localhost]
changed: [kafka-rest1 -> localhost]
changed: [schema-registry1 -> localhost]
changed: [kafka-broker2 -> localhost]
changed: [kafka-connect1 -> localhost]
changed: [ksql1 -> localhost]
changed: [zookeeper1 -> localhost]
changed: [control-center1 -> localhost]
changed: [kafka-broker1 …
=> Validate SSL Keys and Certs before installation.

molecule/rbac-mtls-rhel8/molecule.yml, molecule/rbac-mtls-rhel8/verify.yml
This PR sets the correct docker file for rbac-mtls-rhel8 scenario.  It uses the base image with java 11.  It also updates the verification to not check the ldap server for kafka clients as they are not installed in this host which is expected behaviour.
ANSIENG-1066
The rbac-mtls-rhel8 scenario has been run and now completes successfully.  The verification check also passes.
`PLAY RECAP *********************************************************************
control-center1            : ok=85   changed=35   unreachable=0    failed=0    skipped=54   rescued=0    ignored=0
kafka-broker1              : ok=104  changed=41   unreachable=0    failed=0    skipped=68   rescued=0    ignored=0
kafka-broker2              : ok=94   changed=41   unreachable=0    failed=0    skipped=53 …
=> Corrected the docker image being used by the scenario to base image

roles/ssl/tasks/custom_certs.yml, roles/ssl/tasks/self_signed_certs.yml
Reverts confluentinc/cp-ansible#934
Reverting the changes to unblock team. Once we get dependencies issues addressed we will relook at this change
=> Revert "Improve internal handling of SSL certificates"

ansible.cfg, roles/common/tasks/main.yml
This PR makes cp-ansible 7.0 branch work with older ansible version > 2.9
- Ran a test equivalent to molecule scenario `mtls-java8-rhel` i.e. with RHEL, java8 with MTLS enabled.
=> Adding support for ansible 2.9

molecule/archive-plain-rhel/verify.yml
We have disables fips on archive-plain-rhel scenario with commit https://github.com/confluentinc/cp-ansible/commit/0be567a31bfb3bd7099cac70fbd4bc0d4bf98d3d, while a test in verify still. looks for fips-related properties to exist, which was causing the molecule verify command to fail.
Have removed that test itself as it does not make sense for this scenario anymore.
`molecule verify -s archive-plain-rhel`
```
PLAY RECAP ****************************************************************************************************************************************************************
control-center1 : ok=7 changed=0 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0
kafka-broker1 : ok=9 changed=0 unreachable=0 failed=0 skipped=0 rescued=0 ignored=0
kafka-connect1 : ok=7 …
```
=> Removing fips specific check as we have already disabled fips for JDK11

molecule/Dockerfile-debian-java8.j2, molecule/Dockerfile-debian.j2, molecule/Dockerfile-debian10-archive.j2, molecule/Dockerfile-debian10.j2, molecule/Dockerfile-tar.j2, molecule/Dockerfile-ubuntu-java8.j2, molecule/Dockerfile-ubuntu.j2, molecule/Dockerfile-ubuntu2004.j2, molecule/Dockerfile.j2
Extension of https://github.com/confluentinc/cp-ansible/pull/918 for 7.0.x/7.1.x
Tested as part of 918
=> Read packages/version from env vars - 7.0.x

roles/confluent.test/molecule/rbac-mtls-rhel/verify.yml
This corrects the rbac-mtls-rhel scenario to use the correct password when validating connector status.
ANSIENG-1100
Have successfully run full validation of rbac-mtls-rhel scenario:
```
control-center1            : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker1              : ok=16   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker2              : ok=16   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker3              : ok=16   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-connect1             : ok=14   changed=4 …
```
=> 62x rbac mtls rhel

molecule/multi-ksql-connect-rhel/verify.yml
Add certs and key to ssl enabled connect during verify
By running the same scenario `multi-ksql-rhel`
=> add certs and key to ssl enabled connect during verify

roles/confluent.test/molecule/multi-ksql-connect-rhel/verify.yml
fix issues with provided cert and secrets enabled
By running the same scenario `multi-ksql-rhel`
=> fix issues with provided cert and secrets enabled

roles/confluent.test/molecule/archive-community-plaintext-rhel/molecule.yml
In the given scenario, the package path is hardcoded in the molecule.yml file. 
For our test infra, we switch these urls to package binaries for testing. This PR will add support to read from env var and default to the original value otherwise. 
Fixes # (ANSIENG-1107)
Tested the given scenario locally with molecule test -s ..
=> Pick package from env variables for archive-community-plaintext-rhel

roles/variables/defaults/main.yml
Zookeeper pre-upgrade test failing due to extra slash in the prefix.
Executed upgrade flow.
Upgrade from 6.2.1 -> 7.1
=> fixed prefix causing the upgrade run to fail

roles/confluent.test/molecule/rbac-mtls-rhel/verify.yml
Fixing typo in password
Running the scenario 'rbac-mtls-rhel' in branch 6.1.x
converge -> succesful
verify -> sucessful
- RBAC Enabled
- Mutual TLs enabled
=> Fixing typo in password

roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_consumer.yml
This PR fixes a typo and adds missing quotes. 
Fixes # (issue 937)
=> Fix typo and missing quotes around scope for rbac_replicator_consumer.yml

molecule/mtls-custombundle-rhel/molecule.yml, molecule/mtls-custombundle-rhel/verify.yml, molecule_scenarios.md, roles/kafka_broker/tasks/health_check.yml
This PR updates the mtls_custombundle_rhel scenario to no longer use secrets protection, as secrets protection now requires RBAC in the 7.1.x release.
Additionally, the scenario has been updated to use the correct docker compose files and JAVA 8 in order to use FIPS.
Have also modified health checks to limit when they run when FIPS is enabled.  This is due to incompatible cipher suites when making URL checks.
ANSIENG-1109
Scenario has been run with full validation:
control-center1            : ok=131  changed=60   unreachable=0    failed=0    skipped=81   rescued=0    ignored=0
kafka-broker1              : ok=84   changed=41   unreachable=0    failed=0    skipped=58   rescued=0    ignored=0 …
=> 71x_mtls_custombundle_rhel update.

roles/confluent.test/molecule/archive-scram-rhel/verify.yml
This PR updates the verification step on the archive-scram-rhel scenario to use the correct version for the latest version of connect for this branch.
ANSIENG-1194
=> Updated version in verification step to reflect latest connect version on archive_scram_rhel scenario.

roles/confluent.kafka_broker/tasks/health_check.yml
Updated health checks for ERP to be skipped when FIPS is enabled as python doesn't have the correct cipher suite for this to complete successfully.
ANSIENG-1193
Scenario has completed successfully and full verification has completed successfully:
control-center1            : ok=6    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker1              : ok=12   changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker2              : ok=12   changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker3              : ok=12   changed=0    unreachable=0    failed=0    skipped=0    rescued=0 …
=> Updated health checks to skip ERP check when FIPS enabled.

roles/confluent.variables/vars/main.yml
This is duplicate of https://github.com/confluentinc/cp-ansible/pull/961/ which targets the impacted dev branch.
=> C3 basic auth property fix

roles/confluent.test/molecule/kafka-connect-replicator-mtls-scram-rhel/verify.yml, roles/confluent.test/molecule/kafka-connect-replicator-plain-kerberos-rhel/verify.yml
Modified verification of replicator consumption by adding delay to make sure cluster has replicated messages when running on cloud infrastructure.
ANSIENG-1198
Validated with the scenario kafka_connect_replicator_mtls_scram_rhel
PLAY [Kafka Connect Replicator Validate Consumption and Production between clusters] ***
TASK [Pause for 20 seconds to allow replication to occur across clusters.] *****
Pausing for 20 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [kafka-broker1]
TASK [Consume Records from destination cluster] ********************************
changed: [kafka-broker1]
PLAY [Verify - Kafka Connect Replicator Configuration] *************************
TASK [confluent.test : Find Property in File] **********************************
ok: …
=> Replicator verification delay.

molecule/Dockerfile-rhel-java8.j2
Typo in dockerfile was the reason. for java8 failures in test.
=> Fixing typo in dockerfile

molecule/kafka-connect-replicator-plain-kerberos-rhel/molecule.yml, molecule/multi-ksql-connect-rhel/verify.yml, molecule/rbac-mtls-rhel/molecule.yml, molecule/rbac-mtls-rhel/verify.yml
Disable secrets protections check as secret protection as already disabled Disable secrets protections check as secret protection as already di…
Successfully run verify for `rbac-mtls-rhel`
```
control-center1            : ok=4    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker1              : ok=14   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker2              : ok=14   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-broker3              : ok=14   changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0
kafka-connect1             : ok=14   changed=4 …
```
=> Disable secrets protections check in scenario

roles/confluent.test/molecule/archive-scram-rhel/verify.yml
This PR updates the verification step on the archive-scram-rhel scenario to use the correct version for the latest version of connect for this branch.
=> Update connect version in verify.yml for latest patch

roles/confluent.test/molecule/mtls-custombundle-rhel/molecule.yml, roles/confluent.test/molecule/plaintext-basic-rhel/molecule.yml, roles/confluent.test/molecule/plaintext-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-kerberos-debian/molecule.yml, roles/confluent.test/molecule/rbac-mds-kerberos-mtls-custom-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-mtls-custom-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-plain-custom-rhel/molecule.yml, roles/confluent.test/molecule/rbac-mds-scram-custom-rhel/molecule.yml
Reverts confluentinc/cp-ansible#981
=> Revert "Remove hardcoded path in molecule files 60x"

roles/confluent.kafka_broker/tasks/health_check.yml
Related to https://github.com/confluentinc/cp-ansible/pull/967 to fix similar issues on 60x
=> Skip some health checks if fips enabled

molecule/archive-scram-rhel/verify.yml, molecule/rbac-mtls-rhel/molecule.yml, roles/common/tasks/host_validations.yml, roles/common/tasks/main.yml, roles/kafka_broker/tasks/secrets_protection.yml, roles/kafka_broker/tasks/set_principal.yml
yamllint was having issues with inconsistent linting in representing lists. Have fixed the inconsistency. 
```
cp-ansible on  fix-linting-issues [$] on ☁️  (us-west-2) on ☁️  apandey@confluent.io took 4s
✦ ❯ yamllint -c .yamllint -f colored .                                                                                                   /8.1s
```
=> Fixing yamllint issues

roles/confluent.ksql/tasks/main.yml, roles/confluent.ksql/tasks/register_cluster.yml, sample_inventories/rbac_mutiple_ksql.yml
yamllint related issues fix.
`yamllint -c .yamllint -f colored .`
No new issue detected.
=> Fixing issues related to yamllint

.bumpversion.cfg, README.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
Bumping the version for patch 6.0.6 (ignore the branch name)
Tests ran with the binaries of the given patch were successful.
=> Bumpversion 6.0.6

.bumpversion.cfg, README.md, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Bumped the version for 6.1.5 patch
All tests were passing with the binaries of given patch.
=> Bumpversion 6.1.5

roles/confluent.ksql/tasks/register_cluster.yml
Update rbac flag for ksql cluster registration
[Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
https://jenkins.confluent.io/job/cp-ansible-on-demand/168/
=> Fix variable error in PR 991

.bumpversion.cfg, README.md, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
bumping the patch version for patch 6.2.3
All tests with the patched binaries were running successful.
=> Bumpversion 6.2.3

.bumpversion.cfg, README.md, VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Bumped up patch version
All tests passed with the given patch binaries.
=> Bumpversion 7.0.2

roles/ksql/tasks/register_cluster.yml
Copy of #1005 which somehow didn't propagate to all downstream branches. 
=> Add quotes to fix the condition when registering ksql cluster

.bumpversion.cfg, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Bumpversion for minor release. 
=> Bumpversion for minor release 7.1.0

roles/control_center/tasks/rbac.yml, roles/kafka_broker/tasks/rbac_rolebindings.yml, roles/kafka_connect/tasks/rbac.yml, roles/kafka_connect_replicator/tasks/rbac_replicator.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_consumer.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_monitoring.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_producer.yml, roles/kafka_rest/tasks/rbac.yml, roles/ksql/tasks/rbac.yml, roles/schema_registry/tasks/rbac.yml
Sometimes MDS takes a little bit of time to settle; this adds retries to various API calls that may be made while it's still settling.  Note that the MDS healthcheck doesn't appear to be sufficient.
Tested in a customer environment.
=> (chore) cp-ansible: add retries to all RBAC rolebinding creation (7.0.x)

roles/ksql/tasks/register_cluster.yml
Add list filter to map. This change is to support Ansible 2.9
` molecule --debug converge -s plain-rhel`
Local docker environment
=> Add list filter to support Ansible 2.9

roles/variables/defaults/main.yml
Update package version on master to point to latest released cp version. 
=> Update confluent package version on master

.bumpversion.cfg, docs/VARIABLES.md, galaxy.yml, roles/variables/vars/main.yml
=> Fix version on 7.2.x

playbooks/fetch_logs.yml
https://github.com/confluentinc/cp-ansible/pull/1025
=> Copy of #1025

roles/common/tasks/host_validations.yml
This PR is a bugfix of borked memory host validations, that are currently based on facts that includes disk-cache use, which is obviously wrong. This is also noted in an old Ansible issue: https://github.com/ansible/ansible/issues/8035. But not fixed, to not break compatibility in Ansible, I'll guess.
Also patches the error message to report the detected free memory, to make the error message more user friendly.
NB: Intentionally targeted the 7.1.1 release branch, since I think this something that is going to annoy a lot of users. And we would prefer to use the release branch.
Without this change, our pipelines are failing with the following error message:
````
fatal: [REDACTED]: FAILED! => changed=false 
assertion: ansible_memfree_mb > 2000|float
evaluated_to: false
msg: …
```
=> Fix borked memory host validations (includes disk-cache use)

VARIABLES.md, roles/confluent.common/tasks/main.yml, roles/confluent.ssl/tasks/create_keystores_from_certs.yml, roles/confluent.ssl/tasks/import_ca_chain.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> make trailing slashes in user input archive_base_path consistent

roles/confluent.ssl/tasks/create_keystores_from_certs.yml, roles/confluent.ssl/tasks/import_ca_chain.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Fixing issues which occurred due to unpredictable behavior of path_join filter.
It doesn't properly merges path if second element of the path consist of a number or special character.
archive-plain-rhel (fips_enabled true)
archive-scram-rhel
rbac-scram-custom-rhel
mtls-customcerts-rhel
=> Trailing slash archive base path

docs/hosts_example.yml
Added an example for `kafka_broker_log_dir` to differentiate from `log.dirs` broker custom variable.
No code changes
=> Added example for kafka_broker_log_dir

roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Fixing few extra tests that were failing.
`archive-**`
`plaintext-basic-rhel`
=> 6.2.x pint

docs/VARIABLES.md, roles/common/tasks/main.yml, roles/kafka_broker/tasks/dynamic_groups.yml, roles/ssl/tasks/create_keystores_from_certs.yml, roles/ssl/tasks/import_ca_chain.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml, roles/zookeeper/tasks/dynamic_groups.yml
Pint merge from 7.0.x to 7.1.x
Running all the tests via on-demand jobs.
test results are pending.
=> 7.1.x pint

roles/confluent.kafka_broker/tasks/rbac_rolebindings.yml
pint merge from 6.0.x to 6.1.x
https://jenkins.confluent.io/job/cp-ansible-on-demand/318/
1 test failing was due to debian repo. It's passing locally now.
=> 6.1.x pint2

Jenkinsfile
As the name suggests
Tested on cp-ansible-internal
To be more sure, 
Will need to test one dummy PR from within org and one from community after this is merged.
=> Add yamllint check to Jenkinsfile

roles/confluent.ssl/tasks/create_keystores_from_certs.yml, roles/confluent.ssl/tasks/import_ca_chain.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Changed path_join to community.general.path_join for ansible 2.9 support
Running all tests on all scenarios.
=> path_join to community.general.path_join for ansible 2.9 support

molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/prepare.yml, roles/common/tasks/rbac_setup.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml, roles/ssl/tasks/main.yml, roles/zookeeper/tasks/main.yml
Before applying yamllint checks in the CI job, we need to resolve yamllint failures in all branches. 
All branches except for 7.2.x are healthy (as per the rules we use in yamllint config)
By running yamllint
=> FIx yamllint checks

molecule/broker-scale-up/converge.yml, molecule/broker-scale-up/molecule.yml, molecule/broker-scale-up/prepare.yml, molecule/broker-scale-up/verify.yml
New scenario for brokers scale up.
By running newly created molecule scenario and verify.
=> New scenario for kafka broker scale up

Jenkinsfile
Pint merge issue. cd roles/confluent.test only required before 7.0.x in jenkinsfile.
=> pint merge issue

molecule/archive-plain-debian/molecule.yml, playbooks/all.yml
Latest run on #ansible-eng failing due to yamllint failures. Fixing those. Will be fixed for 7.1.x, 7.2.x, and master too. 
Failing test - https://jenkins.confluent.io/job/confluentinc/job/cp-ansible/job/7.1.x/323/
Restoring archive-plain-debian to its old self. 
Ran yamllint . check locally. 
=> fix yamllint and merge issues

roles/confluent.variables/vars/main.yml
=> redundant declaration of FQCN

roles/confluent.variables/defaults/main.yml
=> Fixing merge conflicts

plugins/filter/filters.py
Remaining ones after merging the PR on 7.1.x
Thinking of adding ansible-test sanity to Jenkinsfile after this change. 
Locally with galaxy importer and ansible-test sanity
=> fix sanity test

roles/confluent.variables/vars/main.yml
=> Multiple paste of community.general

roles/confluent.test/molecule/archive-plain-debian/molecule.yml
=> removed extra lines unused

molecule/ksql-scale-up/molecule.yml, molecule/ksql-scale-up/verify.yml
Issues with KSQL scale up scenario were fixed in this PR.
$molecule test -s ksql-scale-up
===========================================================================================PLAY RECAP *********************************************************************
localhost                  : ok=23   changed=3    unreachable=0    failed=0    skipped=9    rescued=0    ignored=0
INFO     Pruning extra files from scenario ephemeral directory
[ec2-user@ip-172-31-33-199 platform]$ echo $?
0
https://twitter.com/QuantaMagazine/status/1536763902184378374?t=T9GHVGQww2IOz1vuZiLMXg&s=08https://jenkins.confluent.io/j …
=> Fixed issues related to KSQL scale up

molecule/ksql-scale-up/converge.yml
[Jenkins run](https://jenkins.confluent.io/job/cp-ansible-on-demand/380/)
`KSQL-SCALE-UP` scenario.
=> Fixed issues related to KSQL scale up verify

docs/VARIABLES.md, roles/variables/defaults/main.yml
Update the Confluent CLI which gets packaged with Confluent Platform 7.2.0
Molecule scenario 
=> Update Confluent CLI for 7.2.0

.bumpversion.cfg, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Bumped the version for patch 7.1.2
https://jenkins.confluent.io/job/cp-ansible-on-demand/392/console
All Molecule tests
=> Bumped the version for patch 7.1.2

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml
Bumped the version for 6.0.7 patch
https://jenkins.confluent.io/job/cp-ansible-on-demand/394/
All Molecule Tests
=> Bumpversion 6.0.7

.bumpversion.cfg, VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Bumped the version for patch 7.0.4
https://jenkins.confluent.io/job/cp-ansible-on-demand/399/
All Molecule tests
=> Bumped the version for patch 7.0.4

VARIABLES.md, hosts_example.yml, molecule/archive-plain-rhel/molecule.yml, molecule/archive-plain-rhel/verify.yml, molecule/cp-kafka-plain-rhel/molecule.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Fixes # (ANSIENG-1393)
Locally.
And on-demand run 400.
=> Add support for providing custom broker client properties

plugins/filter/filters.py
=> Add line for pep8 check

.bumpversion.cfg, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Bump to 7.2.1

.bumpversion.cfg, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Bump to 7.1.3

.bumpversion.cfg, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Bump to 7.0.5

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> Bump Version: 6.2.5 → 6.2.6

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/archive-scram-rhel/verify.yml, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> Bump Version: 6.1.6 → 6.1.7

.bumpversion.cfg, roles/confluent.variables/defaults/main.yml
=> Bump Version: 6.0.8 → 6.0.9

roles/confluent.variables_handlers/defaults/main.yml, tasks/backup_restore_test.yml, tasks/reinstall_and_restart_components.yml, tasks/reinstall_components.yml, tasks/upgrade_component.yml, upgrade_zookeeper.yml
Made changes for backup directory location and schema-registry plugins.
Fixes #
https://confluentinc.atlassian.net/browse/QEC-7880
=> Change backup directory location from /tmp

docs/HOW_TO_TEST.md
systemd issues with latest docker versions when running molecule tests. Mention supported versions. 
=> Mention docker version requirement

roles/confluent.test/molecule/mtls-java11-rhel/verify.yml, roles/confluent.test/molecule/mtls-java11-ubuntu/verify.yml
This PR aims to resolve test failures seen in mtls-java11-ubuntu and mtls-java11-rhel on branch 6.0.x
Fixes # [ANSIENG-1594](https://confluentinc.atlassian.net/browse/ANSIENG-1594) [ANSIENG-1574](https://confluentinc.atlassian.net/browse/ANSIENG-1574)
I tested both the scenarios locally, as well as on all mtls scenarios in cp-ansible-on-demand. Here is the result [Test Report](https://jenkins.confluent.io/job/cp-ansible-on-demand/417/)
=> Resolve mtls-java11-ubuntu and mtls-java11-rhel Test Failure in 6.0.x

galaxy.yml
Need a fix in the released branches, available on galaxy but not on ansible automation platform. 
To resolve error message, `ERROR! Galaxy import process failed: Invalid collection metadata. At least one tag required from tag list: application, cloud, database, infrastructure, linux, monitoring, networking, security, storage, tools, windows (Code: UNKNOWN)`, a new tag is req
On certify job
=> Add tag required by Automation Hub

CHANGELOG.rst
To satisfy requirements of automation hub upload.
=> Create CHANGELOG.rst file

CHANGELOG.rst
To satisfy requirements of automation hub upload.
=> Add changelog.rst file on 7.1.3-post

CHANGELOG.rst
To satisfy requirements of automation hub upload.
=> Add Changelog.rst file

docs/sample_inventories/single_dev_node.yml
- [ I guess ] New feature (non-breaking change which adds functionality)
Deployed several single node development systems.
Sample inventory file with notes. :-)
- [ x ] My code follows the style guidelines of this project
- [ x ] I have performed a self-review of my own code
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ - ] I have made corresponding changes to the documentation
- [ - ] My changes generate no new warnings
- [ - ] I have added tests that prove my fix is effective or that my feature works
- [ x ] Any dependent changes have been …
=> Single Dev Node with Notes

discovery/main.py, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/service.py, discovery/system/system.py, discovery/utils/inventory.py
=> Fix inventory issue

discovery/service/kafka_broker.py, discovery/utils/inventory.py
=> Fix multile node issue

discovery/service/config/control_center.yml, discovery/service/config/kafka_broker.yml, discovery/service/config/kafka_connect.yml, discovery/service/config/kafka_rest.yml, discovery/service/config/ksql.yml, discovery/service/config/schema_registry.yml, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/service.py
=> Map rbac properties for ansible takeover

discovery/README.md, discovery/service/kafka_broker.py, discovery/system/system.py, discovery/utils/utils.py
=> Add readme and ssh support

docs/VARIABLES.md, docs/sample_inventories/kafka_connect_replicator_rbac.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/molecule.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
I just deployed replicator with rbac and i saw some typo kakfa is wrong on some params so i changes it.
=> Fix typo kakfa to kafka

discovery/README.md, discovery/service/config/kafka_broker.yml, discovery/service/config/kafka_connect.yml, discovery/service/config/schema_registry.yml, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/service.py, discovery/service/zookeeper.py, discovery/system/system.py, discovery/utils/utils.py, docs/DEVELOPMENT_GUIDE.md
=> Fix ssh issue and add keystore alias

discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/zookeeper.py
=> Build ca_cert_alias property

VARIABLES.md, hosts_example.yml, roles/confluent.variables/defaults/main.yml
Same as pull request-  https://github.com/confluentinc/cp-ansible/pull/1078 - Rebased to 6.2.x
=> Allow creation of keystore and truststore ... PR-1078 Rebased to 6.2.x

discovery/README.md, discovery/service/connect.py, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_replicator.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/service.py, discovery/service/zookeeper.py, discovery/utils/utils.py
=> Update readme and log level

roles/confluent.test/molecule/archive-scram-rhel/verify.yml
This PR would resolve test failure on archive-scram-rhel for 6.1.x
Fixes # [ANSIENG-1643](https://confluentinc.atlassian.net/browse/ANSIENG-1643)
It has been tested on this jenkins job [Test Result](https://jenkins.confluent.io/job/cp-ansible-on-demand/487/)
=> Fix release version for archive-scram-rhel

roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml
Extension of https://github.com/confluentinc/cp-ansible/pull/1144
Not tested
=> Skip restart message based on restart var

roles/common/tasks/main.yml
cp-ansible 7.2 onwards, we don't support ansible 2.9
Also, we don't support 2.13 due to some issues. 
Locally
=> Update ansible version check

roles/common/tasks/main.yml
Validate >=2.11 and <2.13 which will include all 2.11.x and 2.12.y
=> Fix ansible version compare

discovery/main.py, discovery/service/config/control_center.yml, discovery/service/config/kafka_rest.yml, discovery/service/config/ksql.yml, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_replicator.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/service.py, discovery/service/zookeeper.py, discovery/system/system.py, discovery/utils/constants.py, discovery/utils/inventory.py, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Fix JVM and RBAC issues

.bumpversion.cfg, roles/confluent.variables/defaults/main.yml
Bumped the patch version to 6.0.10
https://jenkins.confluent.io/job/cp-ansible-on-demand/529/
=> Bumped the patch version to 6.0.10

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> 6.1.8 bumpversion

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Bumped the version for 6.2.7 patch
=> bumpversion for 6.2.7 patch

.bumpversion.cfg, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Bumped version for 7.0.6 patch release.
=> bumpversion for 7.0.6 patch

.bumpversion.cfg, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> bumpversion for 7.1.4 patch

discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_replicator.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/zookeeper.py
=> Change ssl logic for pre72, fix inheritance based on from_version

discovery/service/__init__.py, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_replicator.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/zookeeper.py
=> Fix inheritance based on version

discovery/service/control_center.py, discovery/service/ksql.py, discovery/service/service.py
=> Get rocksdb path for ksql, c3

discovery/service/config/control_center.yml, discovery/service/config/kafka_broker.yml, discovery/service/config/kafka_connect.yml, discovery/service/config/kafka_rest.yml, discovery/service/config/ksql.yml, discovery/service/config/schema_registry.yml, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/service.py
=> Map telemetry properties - takeover

CHANGELOG.rst
=> 7.0.x updated changelog.rst

CHANGELOG.rst
=> 7.2.x changelog

CHANGELOG.rst
=> 7.1.x updated changelog.rst

roles/confluent.common/tasks/confluent_cli.yml, roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/confluent_hub.yml, roles/confluent.kafka_connect/tasks/connect_plugins.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/health_check.yml, roles/confluent.zookeeper/tasks/main.yml, tasks/upgrade_component.yml, upgrade_zookeeper.yml
This PR aims to add retries to installation tasks to resolve connectivity issues.
Fixes # [ANSIENG-1748](https://confluentinc.atlassian.net/browse/ANSIENG-1748)  , [ANSIENG-1721](https://confluentinc.atlassian.net/browse/ANSIENG-1721)
Tested on jenkins job [here](https://jenkins.confluent.io/job/cp-ansible-on-demand/538/)
=> Add Retries to Installation tasks

discovery/README.md, discovery/utils/utils.py
=> Fix verbosity level

discovery/main.py, discovery/system/system.py, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Add archive property details

discovery/service/kafka_broker.py, discovery/service/service.py
=> Map audit log properties

discovery/service/kafka_broker.py
=> Improve logic for fips and mds_super_user

roles/confluent.test/molecule/kerberos.yml, roles/confluent.test/molecule/ldap.yml
This'll allow us to skip these roles or explicitly run these 
These test roles are used in our molecule tests. 
This'll also temporarily resolve the issue with ldap test role (which is not idempotent, multiple run causes failures)
Locally
=> Add tags to test roles

discovery/service/config/kafka_broker.yml, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/service.py, discovery/service/zookeeper.py
=> Map all logging props, fix minor issues, try fixing merge conflicts caused due to self.group 

roles/confluent.common/tasks/fetch_logs.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_consumer.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_monitoring.yml, roles/confluent.kafka_connect_replicator/tasks/rbac_replicator_producer.yml, tasks/certificate_authority.yml
Extension of #1204 (To be merged after pint merge of #1204)
This PR makes the same change at few other additional places.
=> Ext of #1204 - Set ansible_become to false for localhost

discovery/service/kafka_broker.py, discovery/utils/constants.py, discovery/utils/inventory.py, discovery/utils/utils.py
Sanitise to
Typecast all integers correctly (convert from string to int)
Aggregate duplicate props across all groups
=> Sanitise inventory dict

discovery/service/kafka_broker.py, discovery/utils/inventory.py
=> Separate rbac and mds props build for broker

roles/ssl/tasks/custom_certs.yml, roles/ssl/tasks/self_signed_certs.yml
Reverts confluentinc/cp-ansible#1202
=> Revert "Reimplement #934 - Improve internal handling of SSL certificates"

docs/sample_inventories/fips.yml
https://github.com/confluentinc/cp-ansible/issues/863
As requested in GH issue
Lint checks only
=> Add sample inventory for fips config

roles/variables/vars/main.yml
Fix schema registry url when SR host is not provided
Fixes # (issue) https://confluentinc.atlassian.net/browse/ANSIENG-1764
https://jenkins.confluent.io/job/cp-ansible-on-demand/671/
=> Fix schema registry url when SR host is not provided

roles/variables/vars/main.yml
After pint merging this - https://github.com/confluentinc/cp-ansible/pull/1217
We need to fix the filter (using fqn) since 7x+ uses collections.
https://jenkins.confluent.io/job/cp-ansible-on-demand/662/
=> Resolve filter correctly

roles/variables/vars/main.yml
Reverts confluentinc/cp-ansible#1221
=> Revert "Fix schema registry url when SR host is not provided"

.bumpversion.cfg, CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Changes for 7.3 minor release

roles/common/tasks/config_validations.yml
We are attempting to upgrade to CP 7.3.0 (cp-ansible 7.3.0-post branch), and experience a few issues. Last in line is:
````
TASK [confluent.platform.common : get key hash] ********************************
fatal: [REDACTED]: FAILED! => 
msg: |-
The task includes an option with an undefined variable. The error was: 'key_hash_remote' is undefined
The error appears to be in '/home/ansible/.ansible/collections/ansible_collections/confluent/platform/roles/common/tasks/config_validations.yml': line 88, column 3, but may
be elsewhere in the file depending on the exact syntax problem.
The offending line appears to be:
- name: get key hash
^ here
````
This seem to happen because we skip some non-working validations, at least in our environment, using Ansible tags:
````
ANSIBLE_SKIP_TAGS: …
```
=> fix: add missing tags on new tasks

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
This PR makes the retries of installation tasks added in https://github.com/confluentinc/cp-ansible/pull/1181 "smarter", so that check mode is supported against a system that will be upgraded/downgraded when running in non check mode.
In our env, running in check mode, this never ends:
````
TASK [confluent.platform.zookeeper : Install the Zookeeper Packages] ***********
FAILED - RETRYING: [REDACTED]: Install the Zookeeper Packages (5 retries left).
FAILED - RETRYING: [REDACTED]: Install the Zookeeper Packages (4 retries left).
FAILED - RETRYING: [REDACTED]: Install the Zookeeper Packages (3 retries left).
FAILED - RETRYING: [REDACTED]: Install the Zookeeper Packages (2 retries left).
FAILED - RETRYING: [REDACTED]: Install the Zookeeper Packages (1 retries left).
failed: [REDACTED] …
```
=> fix: no point retrying installation tasks in check mode

roles/confluent.common/tasks/debian.yml, roles/confluent.common/tasks/redhat.yml, roles/confluent.common/tasks/ubuntu.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/confluent_hub.yml, roles/confluent.kafka_connect/tasks/connect_plugins.yml, roles/confluent.kafka_connect/tasks/main.yml
This PR is raised to resolve the issue pointed in the comment [1231](https://github.com/confluentinc/cp-ansible/pull/1231#issuecomment-1307347756)
Fixes # [1231](https://github.com/confluentinc/cp-ansible/pull/1231)
Runs successfully in check mode as well as without check mode locally
=> Add condition to pass installations in check mode

galaxy.yml
For hotfix artefact - 7.3 release
Precedence of versions will be decided as per https://semver.org/#spec-item-11
=> Change collection version for galaxy/AAH

docs/TAGS.md, docs/VARIABLES.md, galaxy.yml, meta/runtime.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/verify.yml, molecule/rbac-plain-provided-debian/molecule.yml, molecule/rbac-plain-provided-debian/verify.yml, roles/common/tasks/config_validations.yml, roles/common/tasks/debian.yml, roles/common/tasks/main.yml, roles/common/tasks/redhat.yml, roles/common/tasks/ubuntu.yml, roles/common/vars/main.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/confluent_hub.yml, roles/kafka_connect/tasks/connect_plugins.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml, roles/zookeeper/tasks/main.yml
To be merged as a single commit.
https://jenkins.confluent.io/job/cp-ansible-on-demand/713/
https://jenkins.confluent.io/job/cp-ansible-on-demand/712/
=> Fix breaking changes on 7.3.0-post

galaxy.yml
As per communication from automation hub team, we'll need to re-upload 7.3.0 on ansible automation hub
=> Change ver to reupload on automation hub

CHANGELOG.rst, galaxy.yml, roles/variables/vars/main.yml
Bumping for hotfix - 7.3.1-post (will still install CP 7.3.0)
=> hotfix bump

roles/ssl/tasks/custom_certs.yml, roles/ssl/tasks/self_signed_certs.yml
Now that we have ground work in place - installing pip and cryptography pip packages on managed nodes, Let’s make another attempt to use community.crypto ansible module. 
https://confluentinc.atlassian.net/browse/ANSIENG-1918
on-demand job for crypto branch (on top 7.2.x) - 
https://jenkins.confluent.io/job/cp-ansible-on-demand/773/
https://jenkins.confluent.io/job/cp-ansible-on-demand/771/
on-demand job for crypto-73x branch (on top 7.3.x) - https://jenkins.confluent.io/job/cp-ansible-on-demand/747/ (all passed 🟢 )
tried running and spinning up cp-env with above changes, did not see any failures
=> Reimplement #934 - Improve internal handling of SSL certificates

roles/common/tasks/main.yml
Since we have separated host and config validations, we want to skip these host validations in case of upgrades (deployment strategy rolling) because of false negative validations.
Tested locally
=> Skip host validation for rolling deployment/upgrade

playbooks/all.yml, playbooks/fetch_logs.yml, playbooks/health_check.yml, playbooks/kafka_broker.yml, playbooks/kafka_controller.yml, playbooks/restart.yml, roles/kafka_broker/tasks/health_check.yml, roles/kafka_broker/tasks/main.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
This PR aims to provide a basic running kraft scenario in CP. PLAINTEXT scenarios and FIPS scenarios are able to run successfully with kraft in the current state. eg, to run plaintext-basic-rhel with kraft based cluster
`molecule --env-file molecule/kraft.yml converge -s plaintext-basic-rhel
`
Fixes # [1856](https://confluentinc.atlassian.net/browse/ANSIENG-1856) [1875](https://confluentinc.atlassian.net/browse/ANSIENG-1875) [1878](https://confluentinc.atlassian.net/browse/ANSIENG-1878) [1881](https://confluentinc.atlassian.net/browse/ANSIENG-1881)
Tested locally on plaintext and mtls scenarios
It passes all the molecule scenarios in zookeeper mode [results](https://jenkins.confluent.io/job/cp-ansible-on-demand/784/), [results](https://jenkins.confluent.io/job/cp-ansible-on-demand/785/) …
=> MVP for kraft in cp-ansible

molecule/archive-scram-rhel/molecule.yml, molecule/kafka-connect-replicator-mtls-scram-rhel/molecule.yml, molecule/mtls-ubuntu-acl/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/molecule.yml, molecule/rbac-kerberos-debian/molecule.yml, molecule/rbac-mds-kerberos-debian/molecule.yml, molecule/rbac-mds-kerberos-mtls-custom-rhel/molecule.yml, molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, molecule/rbac-mds-mtls-custom-rhel/molecule.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mds-plain-custom-rhel/molecule.yml, molecule/rbac-mds-scram-custom-rhel/molecule.yml, molecule/rbac-mtls-provided-ubuntu/molecule.yml, molecule/rbac-mtls-rhel/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml, molecule/rbac-plain-provided-debian/molecule.yml, molecule/rbac-scram-custom-rhel/molecule.yml, molecule/scram-rhel/molecule.yml
This PR aims to comment out controller from rbac, scram and ucl scenarios since it is not supported for now
tested on jenkins [here](https://jenkins.confluent.io/job/cp-ansible-on-demand/850/)
=> Remove controller from rbac, scram and ucl scenarios

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
Remove unnecessary loop while installing CP packages (as we provide list of packages to yum/apt)
Fixes # (issue) https://confluentinc.atlassian.net/browse/ANSIENG-1961
https://jenkins.confluent.io/job/cp-ansible-on-demand/865/ 🟢 
=> Remove unnecessary loop while installing CP packages

docs/TAGS.md
Added documentation for cp_package tag.
https://confluentinc.atlassian.net/browse/ANSIENG-1960
=> Documentation for cp_package tag

roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect_replicator/tasks/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/tasks/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/tasks/main.yml
Introduce new tag cp_package for installing/ upgrading confluent packages.
Installing kafka component packages tasks will have additional tag: cp_package
Fixes # (issue) https://confluentinc.atlassian.net/browse/ANSIENG-1960
=> Introduce new tag cp_package for confluent packages

roles/common/tasks/config_validations.yml
Validating whether Certs and Key matches: This method is independent of SSL key algorithm
https://github.com/confluentinc/cp-ansible/issues/1013 
=> Validating whether Certs and Key matches

molecule/broker-scale-up/converge.yml, molecule/broker-scale-up/verify.yml, roles/kafka_broker/tasks/dynamic_groups.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_controller/defaults/main.yml, roles/kafka_controller/tasks/main.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Changes to support running controller and broker on same Node

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> 6.2.8 patch release

.bumpversion.cfg, CHANGELOG.rst, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
PR for patch release 7.0.7 -
Version Bumpup
Updated changelog
=> 7.0.7 patch release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
PR for patch release 7.2.3 -
- Version Bumpup
- Updated changelog
=> 7.2.3 patch release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/DEVELOPMENT_GUIDE.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
PR for patch release 7.3.2 -
confluent_package_version bumped from 7.3.0 → 7.3.1
Updated changelog, variables
=> 7.3.2 patch release

.bumpversion.cfg, roles/confluent.variables/defaults/main.yml
=> 6.0.11 patch release

molecule/archive-community-plaintext-rhel/molecule.yml, playbooks/kafka_controller.yml, roles/kafka_controller/tasks/main.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> different systemd location in tarball and controller.quorum.voters fix

VARIABLES.md, roles/confluent.common/tasks/update_log4j.yml, roles/confluent.control_center/defaults/main.yml, roles/confluent.control_center/tasks/main.yml, roles/confluent.kafka_broker/defaults/main.yml, roles/confluent.kafka_broker/tasks/main.yml, roles/confluent.kafka_connect/defaults/main.yml, roles/confluent.kafka_connect/tasks/main.yml, roles/confluent.kafka_connect_replicator/defaults/main.yml, roles/confluent.kafka_connect_replicator/templates/kafka-connect-replicator-log4j.properties.j2, roles/confluent.kafka_rest/defaults/main.yml, roles/confluent.kafka_rest/tasks/main.yml, roles/confluent.ksql/defaults/main.yml, roles/confluent.ksql/templates/ksql-server_log4j.properties.j2, roles/confluent.schema_registry/defaults/main.yml, roles/confluent.schema_registry/tasks/main.yml, roles/confluent.zookeeper/defaults/main.yml, roles/confluent.zookeeper/templates/zookeeper_log4j.properties.j2
Backporting to post branches (for a very specific requirement - not a precedence)
To be merged with ours strategy
Tested locally by changing root logger def of all components. 
=> Add custom root logger for components

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> 6.1.9 patch release

discovery/manager/manager.py, discovery/service/config/control_center.yml, discovery/service/config/kafka_broker.yml, discovery/service/config/kafka_connect.yml, discovery/service/config/kafka_rest.yml, discovery/service/config/ksql.yml, discovery/service/config/schema_registry.yml, discovery/service/config/zookeeper.yml, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/service.py, discovery/service/zookeeper.py
=> discover kerberos properties

molecule/kerberos-rhel/verify.yml, molecule/kraft.yml, molecule/mtls-debian/verify.yml, molecule/mtls-ubuntu-acl/molecule.yml, molecule/mtls-ubuntu-acl/verify.yml, molecule/mtls-ubuntu/verify.yml, molecule/plain-rhel/verify.yml
=> add kraft acl support in broker

molecule/cp-kafka-plain-rhel/verify.yml
=> rectify hostname in cp-kafka-plain-rhel verify.yml

discovery/manager/manager.py, discovery/service/__init__.py, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_replicator.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/service/schema_registry.py, discovery/service/service.py, discovery/service/zookeeper.py, discovery/system/system.py, discovery/utils/constants.py, discovery/utils/utils.py
=> Fix lint, parsing issues, add error handling

molecule/plaintext-rhel-customrepo/molecule.yml, molecule/plaintext-rhel-customrepo/prepare.yml
Fix failing test - https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.3.x/36/testReport/molecule.plaintext-rhel-customrepo.molecule/yml/test/
https://jenkins.confluent.io/job/cp-ansible-on-demand/940/
=> Fix failing test

discovery/utils/utils.py
=> Support passing output file as command line arg

molecule/rbac-kerberos-debian/molecule.yml
For given scenario, some pint issues remained.
Fixing zkp/controller principal name
=> Fix zkp/controller principal name

roles/kafka_controller/tasks/health_check.yml
As above
https://jenkins.confluent.io/job/cp-ansible-on-demand/981/
=> Fix health check for controller with custom kerberos client config file

molecule/ksql-scale-up/molecule.yml, molecule/plain-rhel/verify.yml
Fix failing tests reported by weekly test job
https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.1.x/143/
https://jenkins.confluent.io/job/cp-ansible-on-demand/1003/
=> Fix failing tests reported by weekly test job

playbooks/tasks/certificate_authority.yml, roles/common/tasks/confluent_cli.yml, roles/common/tasks/main.yml, roles/common/tasks/masterkey.yml, roles/common/tasks/secrets_protection.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/dynamic_groups.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_broker/tasks/rbac.yml, roles/kafka_broker/tasks/secrets_protection.yml, roles/kafka_connect/tasks/confluent_hub.yml, roles/kafka_connect/tasks/connect_plugins.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect_replicator/tasks/rbac_replicator.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_consumer.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_monitoring.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_producer.yml, roles/kerberos/tasks/main.yml, roles/ssl/tasks/import_ca_chain.yml, roles/ssl/tasks/main.yml, roles/ssl/tasks/manage_keystore_and_truststore.yml, roles/ssl/tasks/provided_keystore_and_truststore.yml
Some of the tasks requiring root permissions had missing privileged tag, fixed that.
https://confluentinc.atlassian.net/browse/ANSIENG-2027
https://jenkins.confluent.io/job/cp-ansible-on-demand/1004/
=> ANSIENG-2027 Add privileged tag to tasks requiring root permissions

playbooks/nuke.yml
A new playbook to delete everything, for development scenarios.
By running nuke.yml
=> Adding new playbook to delete/purge everything installed by cp-ansible

playbooks/nuke.yml
Fixed linting issues reported by latest 7.4.x build
17:23:00  + python3 -m yamllint .
17:23:08  ./playbooks/nuke.yml
17:23:08    3:17      error    truthy value should be one of [false, true]  (truthy)
17:23:08    23:20     error    truthy value should be one of [false, true]  (truthy)
17:23:08    127:22    error    truthy value should be one of [false, true]  (truthy)
17:23:08    236:24    error    truthy value should be one of [false, true]  (truthy)
Ran yamllint on local, no issues reported.
=> Fix linting issues

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/DEVELOPMENT_GUIDE.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
We introduced two bumpversion configs from 7.3.x onwards, however we missed pint merging this to later branches. Fixing the same.
=> Fix bumpversion configs

discovery/service/control_center.py, discovery/service/schema_registry.py, discovery/utils/utils.py
As above
Locally with docker-molecule, soak cluster
=> Minor fixes/enhancement for discovery

roles/variables/vars/main.yml
=> Fix metrics reporter bootstrap server in Controller

roles/kafka_broker/tasks/register_cluster.yml, roles/kafka_connect/tasks/register_cluster.yml, roles/kafka_connect_replicator/tasks/register_cluster.yml, roles/ksql/tasks/register_cluster.yml, roles/schema_registry/tasks/register_cluster.yml
=> Add retries to register cluster task

.bumpversion.cfg, roles/confluent.variables/defaults/main.yml
=> 6.0.12 patch release

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> 6.1.10 patch release

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> 6.2.9 patch release

.bumpversion.cfg, CHANGELOG.rst, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.0.8 patch release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.1.6 patch release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.2.4 patch release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.3.3 patch release

VARIABLES.md, molecule/multi-ksql-connect-rhel/molecule.yml, plugins/modules/kafka_connectors.py, roles/kafka_connect/defaults/main.yml, roles/kafka_connect/tasks/deploy_connectors.yml, test_roles/confluent.test/tasks/check_connector.yml
Introduce timeout while deploying connector.
https://confluentinc.atlassian.net/browse/RCCA-11106
https://jenkins.confluent.io/job/cp-ansible-on-demand/1178/
=> Introduce timeout while deploying connector

upgrade_zookeeper.yml
This PR aims to fix zookeeper upgrades on CP 6.1.x
Fixes # [ANSIENG-2144](https://confluentinc.atlassian.net/browse/ANSIENG-2144)
tested locally
[ANSIENG-2144]: https://confluentinc.atlassian.net/browse/ANSIENG-2144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Fix zookeeper upgrade for 6.1.x

molecule/Dockerfile-rhel9-java11.j2, molecule/Dockerfile-rhel9-java17.j2, molecule/Dockerfile-rhel9-tar.j2, molecule/archive-plain-rhel/molecule.yml, molecule/mtls-java11-rhel/molecule.yml, molecule/plain-rhel/molecule.yml
Tweaked couple of existing molecule scenarios to test CP installation on RHEL9 OS. 
Note: 
- We are using redhat/ubi9-minimal docker as the base image to simulate RHEL9
- This PR contains the hack/ workaround to fix sha256 signature issue of rpm packages, which we agreed to fix in upcoming CP 7.5 release (we'll remove this temp change then).
- [] Bug fix (non-breaking change which fixes an issue)
https://jenkins.confluent.io/job/cp-ansible-on-demand/1232/
=> Molecule tests for RHEL9 support

roles/kafka_connect/tasks/health_check.yml, roles/kafka_connect_replicator/tasks/health_check.yml, roles/kafka_rest/tasks/health_check.yml, roles/ksql/tasks/health_check.yml, roles/schema_registry/tasks/health_check.yml
Fixes all failing mtls molecule tests
All mtls molecule tests passing
https://jenkins.confluent.io/job/cp-ansible-on-demand/1239/
=> Fix mTLS healthcheck 

roles/common/tasks/rbac_setup.yml
Increase number of retries on Rest proxy call
Fixes #inc-rcca-11539-ansible-rolling-deployment-strategy-fails-with-a-401
=> Increase retries for Rest Proxy

.bumpversion.cfg, roles/confluent.variables/defaults/main.yml
https://jenkins.confluent.io/job/cp-ansible-weekly/job/6.0.x/124/
=> 6.0.13 patch release

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
https://jenkins.confluent.io/job/cp-ansible-weekly/job/6.1.x/120/
=> 6.1.11 patch release

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
https://jenkins.confluent.io/job/cp-ansible-weekly/job/6.2.x/119/
=> 6.2.10 patch release

.bumpversion.cfg, CHANGELOG.rst, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.0.x/128/
=> 7.0.9 patch release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.1.x/157/
https://jenkins.confluent.io/job/cp-ansible-on-demand/1257/
=> 7.1.7 patch release

docs/sample_inventories/non_root_deployment.yml, playbooks/tasks/certificate_authority.yml, roles/common/tasks/confluent_cli.yml, roles/common/tasks/main.yml, roles/common/tasks/masterkey.yml, roles/common/tasks/secrets_protection.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/dynamic_groups.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_broker/tasks/rbac.yml, roles/kafka_connect/tasks/confluent_hub.yml, roles/kafka_connect/tasks/connect_plugins.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect_replicator/tasks/rbac_replicator.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_consumer.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_monitoring.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_producer.yml, roles/kafka_rest/tasks/main.yml, roles/kerberos/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml, roles/ssl/tasks/import_ca_chain.yml, roles/ssl/tasks/main.yml, roles/ssl/tasks/manage_keystore_and_truststore.yml, roles/ssl/tasks/provided_keystore_and_truststore.yml, roles/zookeeper/tasks/main.yml
- We have removed privileged tag from multiple tasks
- Customer should update the filesystem paths to those that are within their control to avoid permission errors (Added sample inventory for reference)
https://jenkins.confluent.io/job/cp-ansible-on-demand/1255/
=> Fix non-root deployments

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
https://jenkins.confluent.io/job/cp-ansible-on-demand/1261/
https://jenkins.confluent.io/job/cp-ansible-on-demand/1262/
=> 7.3.4 patch release

molecule/plain-rhel/molecule.yml, molecule/plain-rhel/prepare.yml, molecule/plain-rhel/verify.yml, roles/kafka_connect/tasks/connect_plugins.yml
- Fixed issue while installing kafka connect plugins downloaded locally on ansible controller
- Added test to verify and assert installed local plugin
https://jenkins.confluent.io/job/cp-ansible-on-demand/1268/ 
=> Fix kafka connect local plugins installation

discovery/README.md, discovery/manager/manager.py, discovery/service/control_center.py, discovery/service/kafka_connect.py, discovery/service/service.py, discovery/utils/inventory.py, discovery/utils/utils.py
This change adds capability to discover multiple workers in the connect cluster. 
This has been tested with Molecule scenario `multi-ksql-connect-rhel`. The original and generated inventory file gente
=> Discovery - Support for multiple connect workers

VARIABLES.md, roles/common/tasks/rbac_setup.yml, roles/control_center/tasks/rbac.yml, roles/kafka_broker/tasks/health_check.yml, roles/kafka_broker/tasks/rbac_rolebindings.yml, roles/kafka_broker/tasks/register_cluster.yml, roles/kafka_connect/tasks/rbac.yml, roles/kafka_connect/tasks/register_cluster.yml, roles/kafka_rest/tasks/rbac.yml, roles/ksql/tasks/rbac.yml, roles/ksql/tasks/register_cluster.yml, roles/schema_registry/tasks/rbac.yml, roles/schema_registry/tasks/register_cluster.yml, roles/variables/defaults/main.yml
This PR aims to parametrize the number of retries for MDS API requests. 
Fixes # [ANSIENG-2336](https://confluentinc.atlassian.net/browse/ANSIENG-2336)
Tested locally on RBAC scenarios
[ANSIENG-2336]: https://confluentinc.atlassian.net/browse/ANSIENG-2336?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Parametrize the number of retries for MDS API requests

molecule/plain-rhel/molecule.yml, molecule/plain-rhel/verify.yml, roles/kafka_broker/templates/client.properties.j2
merges [1428](https://github.com/confluentinc/cp-ansible/pull/1428) to CP-ansible 7.0.x
Fixes # [ANSIENG-2459](https://confluentinc.atlassian.net/browse/ANSIENG-2459)
tested locally
[ANSIENG-2459]: https://confluentinc.atlassian.net/browse/ANSIENG-2459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove timeout configs from client properties

roles/kafka_controller/templates/client.properties.j2
Extends [1429](https://github.com/confluentinc/cp-ansible/pull/1429) for Kraft controllers
Fixes # [ANSIENG-2459](https://confluentinc.atlassian.net/browse/ANSIENG-2459)
locally
[ANSIENG-2459]: https://confluentinc.atlassian.net/browse/ANSIENG-2459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Remove timeout configs for Kafka controller client

discovery/README.md, docs/VARIABLES.md, roles/variables/defaults/main.yml
fixes some minor issues in documentations. No code change.
Fixes # [ANSIENG-2481](https://confluentinc.atlassian.net/browse/ANSIENG-2481)
[ANSIENG-2481]: https://confluentinc.atlassian.net/browse/ANSIENG-2481?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update discovery doc and fix VARIABLES.md for Kraft

.bumpversion.cfg, roles/confluent.variables/defaults/main.yml
PR for patch release of version 6.0.14
Fixes # [ANSIENG-2462](https://confluentinc.atlassian.net/browse/ANSIENG-2462)
tested in jenkins runs 
[ANSIENG-2462]: https://confluentinc.atlassian.net/browse/ANSIENG-2462?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump CP 6.0 version

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
release CP Ansible 6.1.12 patch
Fixes # [ANSIENG-2464](https://confluentinc.atlassian.net/browse/ANSIENG-2464)
tested on jenkins
[ANSIENG-2464]: https://confluentinc.atlassian.net/browse/ANSIENG-2464?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump CP 6.1 version

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
release CP ansible 6.2.11 patch
Fixes # [ANSIENG-2465](https://confluentinc.atlassian.net/browse/ANSIENG-2465)
jenkins
- [] If required, I have ensured the changes can be discovered by cp-ansible discovery codebase
[ANSIENG-2465]: https://confluentinc.atlassian.net/browse/ANSIENG-2465?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump CP 6.2 version

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
release CP 7.1.8 patch 
Fixes [ANSIENG-2469](https://confluentinc.atlassian.net/browse/ANSIENG-2469)
jenkins tests
[ANSIENG-2469]: https://confluentinc.atlassian.net/browse/ANSIENG-2469?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump CP 7.1 version

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
release CP 7.2.6 patch
Fixes # [ANSIENG-2467](https://confluentinc.atlassian.net/browse/ANSIENG-2467)
jenkins tests
[ANSIENG-2467]: https://confluentinc.atlassian.net/browse/ANSIENG-2467?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump CP 7.2 version

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
release CP 7.3.4 (CP-Ansible 7.3.5) patch
Fixes # [ANSIENG-2468](https://confluentinc.atlassian.net/browse/ANSIENG-2468)
jenkins
[ANSIENG-2468]: https://confluentinc.atlassian.net/browse/ANSIENG-2468?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump CP 7.3 version

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
release CP 7.4.1 patch
Fixes # [ANSIENG-2463](https://confluentinc.atlassian.net/browse/ANSIENG-2463)
jenkins
[ANSIENG-2463]: https://confluentinc.atlassian.net/browse/ANSIENG-2463?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump CP 7.4 version

docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, molecule/mtls-custombundle-rhel-fips/molecule.yml, molecule/mtls-custombundle-rhel-fips/verify.yml, roles/kafka_broker/defaults/main.yml, roles/kafka_controller/defaults/main.yml, roles/variables/defaults/main.yml
Fixes # [ANSIENG-2523](https://confluentinc.atlassian.net/browse/ANSIENG-2523)
tested locally
[ANSIENG-2523]: https://confluentinc.atlassian.net/browse/ANSIENG-2523?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add test for FIPS on RHEL 7

.github/CODEOWNERS
update codeowner to ansible-team.
=> Update codeowner for cp-ansible

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
PR for 7.5.0 minor release
Fixes # (ANSIENG-2420)[https://confluentinc.atlassian.net/browse/ANSIENG-2420]
(Jenkins7.5.x-kraft)[https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.5.x-kraft/5/]
(Jenkins7.5.x)[https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.5.x/6/]
=> 7.5.0 minor release

molecule/Dockerfile-rhel9-java8.j2, molecule/ksql-scale-up/molecule.yml
Modified a preexisting molecule scenario to add test for java 8 on Rhel 9. Installs java using package manager.
Fixes # [ANSIENG-2527](https://confluentinc.atlassian.net/browse/ANSIENG-2527)
Jenkins test 1720
[ANSIENG-2527]: https://confluentinc.atlassian.net/browse/ANSIENG-2527?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Molecule test java8 on RHEL9

discovery/README.md, discovery/service/control_center.py, discovery/service/kafka_broker.py, discovery/service/kafka_connect.py, discovery/service/kafka_rest.py, discovery/service/ksql.py, discovery/utils/utils.py
bug fixes in discovery
Fixes # [ANSIENG-2483](https://confluentinc.atlassian.net/browse/ANSIENG-2483) [ANSIENG-2534](https://confluentinc.atlassian.net/browse/ANSIENG-2534)
tested locally
[ANSIENG-2483]: https://confluentinc.atlassian.net/browse/ANSIENG-2483?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANSIENG-2534]: https://confluentinc.atlassian.net/browse/ANSIENG-2534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Collect listener properties in Discovery

molecule/mtls-ubuntu-acl/molecule.yml
[1461](https://github.com/confluentinc/cp-ansible/pull/1461) for Kraft mode
tested locally
=> add ACL  authorizer for Kraft

docs/VARIABLES.md, roles/variables/defaults/main.yml
=> Update doc for Kafka Controller rest proxy

.bumpversion.cfg, roles/confluent.variables/defaults/main.yml
=> Patch Release for 6.0.15

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> Patch Release for 6.1.13

.bumpversion.cfg, VARIABLES.md, molecule_scenarios.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> Patch Release for 6.2.12

.bumpversion.cfg, CHANGELOG.rst, MOLECULE_SCENARIOS.md, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch Release for 7.0.11

.bumpversion.cfg, CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch Release for 7.1.9

.bumpversion.cfg, CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch Release for 7.2.7

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch Release for 7.3.6

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch Release for 7.4.2

docs/sample_inventories/migration_sample.yml
update in sample inventory file to ZK to kraft migration
=> Update ZK to Kraft migration sample inventory

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> Patch Release for 6.1.14

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> Patch Release for 6.2.13

.bumpversion.cfg, CHANGELOG.rst, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch Release for 7.0.12

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch Release for 7.1.10

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
CP-Ansible 7.5.2 patch release
Fixes # [ANSIENG-2759](https://confluentinc.atlassian.net/browse/ANSIENG-2759)
weekly jobs
[ANSIENG-2759]: https://confluentinc.atlassian.net/browse/ANSIENG-2759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Bump CP 7.5 version

roles/confluent.kafka_broker/tasks/rbac.yml
fixes https://github.com/confluentinc/cp-ansible/pull/1514 for merge issues
Fixes # [2857](https://confluentinc.atlassian.net/jira/software/c/projects/ANSIENG/boards/1886?selectedIssue=ANSIENG-2857)
=> Improve error handling when RBAC cluster has no auth

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
patch release for CP 6.1.15
Fixes # [ANSIENG-2980](https://confluentinc.atlassian.net/browse/ANSIENG-2980)
[jenkins job](https://jenkins.confluent.io/job/cp-ansible-weekly/job/6.1.x/)
[ANSIENG-2980]: https://confluentinc.atlassian.net/browse/ANSIENG-2980?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2980] | Bump 6.1 version

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
Patch release of CP 6.2.14
Fixes # [ANSIENG-2982](https://confluentinc.atlassian.net/browse/ANSIENG-2982)
[jenkins job](https://jenkins.confluent.io/job/cp-ansible-weekly/job/6.2.x/140/)
[ANSIENG-2982]: https://confluentinc.atlassian.net/browse/ANSIENG-2982?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2982] | Bump 6.2 version

.bumpversion.cfg, CHANGELOG.rst, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
patch release of CP 7.0.13
Fixes # [ANSIENG-2983](https://confluentinc.atlassian.net/browse/ANSIENG-2983)
[jenkins job](https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.0.x/)
[ANSIENG-2983]: https://confluentinc.atlassian.net/browse/ANSIENG-2983?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2983] | Bump 7.0 version

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
patch release of CP 7.1.11
Fixes # [ANSIENG-2984](https://confluentinc.atlassian.net/browse/ANSIENG-2984)
[jenkins job](https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.1.x/)
[ANSIENG-2984]: https://confluentinc.atlassian.net/browse/ANSIENG-2984?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2984] | Bump 7.1 version

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
patch release of CP 7.2.9
Fixes # [ANSIENG-2981](https://confluentinc.atlassian.net/browse/ANSIENG-2981)
[jenkins job](https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.2.x/)
[ANSIENG-2981]: https://confluentinc.atlassian.net/browse/ANSIENG-2981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2981] | Bump 7.2 version

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
patch release of CP 7.3.7
Fixes # [ANSIENG-2985](https://confluentinc.atlassian.net/browse/ANSIENG-2985)
[jenkins job](https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.3.x/)
[ANSIENG-2985]: https://confluentinc.atlassian.net/browse/ANSIENG-2985?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2985] | Bump 7.3 version 

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
patch release of CP 7.4.4
Fixes # [ANSIENG-2986](https://confluentinc.atlassian.net/browse/ANSIENG-2986)
[jenkins job](https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.4.x/)
[jenkins job kraft](https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.4.x-kraft/)
[ANSIENG-2986]: https://confluentinc.atlassian.net/browse/ANSIENG-2986?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2986] | Bump 7.4 version

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
patch release of CP 7.5.3
Fixes # [ANSIENG-2987](https://confluentinc.atlassian.net/browse/ANSIENG-2987)
[jenkins job](https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.5.x/)
[jenkins job kraft](https://jenkins.confluent.io/job/cp-ansible-weekly/job/7.5.x-kraft/)
[ANSIENG-2987]: https://confluentinc.atlassian.net/browse/ANSIENG-2987?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2987] | Bump 7.5 version

roles/kafka_controller/tasks/health_check.yml, roles/variables/vars/main.yml
Remove temporary config from Kraft for migration
Fixes # [ANSIENG-2739](https://confluentinc.atlassian.net/browse/ANSIENG-2739)
tested on jenkins
[ANSIENG-2739]: https://confluentinc.atlassian.net/browse/ANSIENG-2739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2739]  | Remove temporary config from Kraft for migration

docs/MOLECULE_SCENARIOS.md, molecule/rbac-mtls-rhel-fips/molecule.yml
modified a molecule scenario to test Colocated Kraft Controller and Broker with RBAC
Fixes # [ANSIENG-3153](https://confluentinc.atlassian.net/browse/ANSIENG-3153)
tested locally
[ANSIENG-3153]: https://confluentinc.atlassian.net/browse/ANSIENG-3153?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-3153]  | Add test scenario for Colocated Kraft Controller and Broker with RBAC

playbooks/migration_precheck.yml
This PR aims to Remove slicing from confluent_package_version for RC build. The slicing for needed for our internal tests on nightly builds, it's not needed on RC or packages.
Fixes # [ANSIENG-2739](https://confluentinc.atlassian.net/browse/ANSIENG-2739)
tested locally
[ANSIENG-2739]: https://confluentinc.atlassian.net/browse/ANSIENG-2739?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [ANSIENG-2739] | Remove slicing from confluent_package_version for RC build

molecule/archive-plain-rhel-fips/verify.yml
fixes scenario archive-plain-rhel-fips
tested locally
=> [fix-connector] | Fix minor bug in deploying Connector

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
PR for minor release 7.6
Fixes [ANSIENG-2573](https://confluentinc.atlassian.net/browse/ANSIENG-2573)
Tested using jenkins on demand for the scenarios ->
- amd + zk
- amd + kraft
- arm + zk
- arm + kraft
- in place upgrade
[ANSIENG-2573]: https://confluentinc.atlassian.net/browse/ANSIENG-2573?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> 7.6 release ANSIENG-2573

CHANGELOG.rst, molecule/archive-plain-rhel-fips/verify.yml, molecule/broker-scale-up/verify.yml, molecule/rbac-mtls-rhel-fips/verify.yml, roles/common/tasks/configure_logredactor.yml
Minor changes in changelog.rst
Modifed verify files to remove jinja usage in when and that statements
=> 7.6.0 release minor changes in changelog.rst ANSIENG-2573

tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt
=> Fix sanity tests for 7.6.x

roles/kafka_connect/tasks/deploy_connectors.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect/tasks/register_cluster.yml, roles/ksql/tasks/main.yml, roles/ksql/tasks/register_cluster.yml
Minor extension of https://github.com/confluentinc/cp-ansible/pull/1564
=> Fix colocated Connect in Kraft mode

docs/VARIABLES.md, roles/variables/defaults/main.yml
Updated confluent cli version to 3.48.0
Fixes # [(3321)](https://confluentinc.atlassian.net/browse/ANSIENG-3321)
=> [ANSIENG-3321] | updated cli version from 3.2.1 to 3.48.0

docs/VARIABLES.md, roles/variables/defaults/main.yml
PR to update the confluent cli version to latest. The version has been picked from [here](https://github.com/confluentinc/packaging/blob/7.4.x/settings.sh#L253)
Fixes [ANSIENG-3532](https://confluentinc.atlassian.net/browse/ANSIENG-3532)
[ANSIENG-3532]: https://confluentinc.atlassian.net/browse/ANSIENG-3532?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Update cli version to latest

.bumpversion.cfg, VARIABLES.md, roles/confluent.test/molecule/plaintext-rhel/verify.yml, roles/confluent.variables/defaults/main.yml, roles/confluent.variables/vars/main.yml
=> 6.2.x patch release

.bumpversion.cfg, CHANGELOG.rst, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.0.x patch release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.1.x patch release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.2.x patch release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.3.x patch release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.4.x patch release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.5.x patch release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.6.x patch release

meta/runtime.yml, roles/common/meta/main.yml, roles/control_center/meta/main.yml, roles/kafka_broker/meta/main.yml, roles/kafka_connect/meta/main.yml, roles/kafka_connect_replicator/meta/main.yml, roles/kafka_rest/meta/main.yml, roles/kerberos/meta/main.yml, roles/ksql/meta/main.yml, roles/schema_registry/meta/main.yml, roles/ssl/meta/main.yml, roles/variables/meta/main.yml, roles/zookeeper/meta/main.yml
Added patch version to meta/runtime.yml & updated min ansible version in role's meta/main.yml
=> [ANSIENG-3627] Second round fix73 

roles/kafka_controller/meta/main.yml, roles/kafka_controller/tasks/main.yml
Added role description for kafka_controller
=>  [ANSIENG-3627] Second round fix7.4 to propogate

playbooks/nuke.yml
Added nuke.yml playbook to master
=> re-added nuke to master

meta/runtime.yml, roles/common/meta/main.yml, roles/control_center/meta/main.yml, roles/kafka_broker/meta/main.yml, roles/kafka_connect/meta/main.yml, roles/kafka_connect_replicator/meta/main.yml, roles/kafka_controller/meta/main.yml, roles/kafka_rest/meta/main.yml, roles/kerberos/meta/main.yml, roles/ksql/meta/main.yml, roles/schema_registry/meta/main.yml, roles/ssl/meta/main.yml, roles/variables/meta/main.yml, roles/zookeeper/meta/main.yml
Added patch version to meta/runtime.yml & updated min ansible version in role's meta/main.yml
=> [ANSIENG-3627] | updated min ansible version in runtime & meta

tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.9.txt
Removes pylint checks on few files of discovery
Fixes # [(ANSIENG-3627)](https://confluentinc.atlassian.net/browse/ANSIENG-3627)
=> [ANSIENG-3627] | added few ignores for discovery

tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.9.txt
Removes pylint checks on few files of discovery
Fixes # [(ANSIENG-3627)](https://confluentinc.atlassian.net/browse/ANSIENG-3627)
=> [ANSIENG-3627] | added few ignores in sanity tests for discovery

molecule/oauth-rbac-plain-rhel8/molecule.yml, plugins/filter/filters.py, roles/kafka_broker/tasks/health_check.yml, roles/kafka_controller/tasks/get_meta_properties.yml, roles/variables/vars/main.yml
Fixes # [ANSIENG-3534](https://confluentinc.atlassian.net/browse/ANSIENG-3534)
[ANSIENG-3534]: https://confluentinc.atlassian.net/browse/ANSIENG-3534?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add OAuth in Kraft Controller

roles/kafka_broker/tasks/rbac.yml, roles/kafka_controller/tasks/rbac.yml, roles/variables/vars/main.yml
=> OAuth in Kraft

molecule/oauth-rbac-mds-kerberos-debian/molecule.yml, molecule/oauth-rbac-plain-rhel8/molecule.yml, molecule/plain-rhel/molecule.yml, roles/variables/vars/main.yml
=> Update molecule tests for OAuth in C3

test_roles/confluent.test.kerberos/tasks/main.yml
Jira Link: https://confluentinc.atlassian.net/browse/ANSIENG-3703
Changes in syntax to accommodate ansible version 9.
[Semaphore Run](https://semaphore.ci.confluent.io/jobs/f423d005-7cf8-4392-8951-3024640f16ce/summary?report_id=4ae71336-e44b-39bf-b9d2-752e234818a5) with ALL scenarios for 7.7.x.
The failed test were run on 7.6.x branch. [Semaphore Run](https://semaphore.ci.confluent.io/workflows/aeba9c0b-1655-4586-a7ab-167c28f71bd6?pipeline_id=12eb7a8f-9d2c-4fd5-9000-1c8736f74a9c). Some tests failed due to debain related issue. Others passed.
=> [ANSIENG-3703]|Enable Ansible 9

roles/control_center/tasks/rbac.yml, roles/kafka_connect/tasks/health_check.yml, roles/kafka_connect/tasks/rbac.yml, roles/kafka_rest/tasks/health_check.yml
Added no logs to all tasks where authorization token is getting used
=> [oauth-dev] | added no log for all tasks involving authorization token

roles/ssl/tasks/idp_certs.yml, roles/ssl/tasks/main.yml, roles/variables/defaults/main.yml
https://confluentinc.atlassian.net/browse/ANSIENG-3319
(https://confluentinc.atlassian.net/browse/ANSIENG-3469)
=> Import IDP certificate to kafka truststore

molecule/kafka-connect-replicator-mtls-scram-rhel/molecule.yml, molecule/kafka-connect-replicator-mtls-scram-rhel/prepare.yml, molecule/kafka-connect-replicator-mtls-scram-rhel/verify.yml, molecule/plain-rhel/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/prepare.yml, plugins/modules/kafka_connectors.py, roles/common/tasks/rbac_setup.yml, roles/kafka_broker/tasks/health_check.yml, roles/kafka_connect/tasks/deploy_connectors.yml, roles/kafka_connect/tasks/health_check.yml, roles/kafka_connect/tasks/rbac_connectors.yml, roles/kafka_connect_replicator/tasks/health_check.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/kafka_connect_replicator/tasks/rbac_replicator.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_consumer.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_monitoring.yml, roles/kafka_connect_replicator/tasks/rbac_replicator_producer.yml, roles/kafka_connect_replicator/tasks/register_cluster.yml, roles/kafka_rest/tasks/health_check.yml, roles/schema_registry/tasks/health_check.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml, test_roles/confluent.test.oauth/defaults/main.yml
Changes for OAuth in connectors and connect replicator. This involves oauth server enabling on connect replicator and oauth client config for connectors. 
[semaphore](https://semaphore.ci.confluent.io/workflows/e4145333-cecf-408d-9978-6c8e9b827a94?pipeline_id=05cf6333-f277-4748-8d36-0b4c758a0fa5)
[oauth on replicator cluster without rbac](https://semaphore.ci.confluent.io/workflows/85d907c0-05cc-4666-b306-10b54e09a770?pipeline_id=efd288d6-a2f9-4c6b-b49a-3e12adfa17d2)
=> Changes for OAuth in connectors and connect replicator

docs/sample_inventories/oauth_brownfield.yml, docs/sample_inventories/oauth_greenfield.yml
=> Add sample inventory files for OAuth setup

.ansible-lint
=> [ANSIENG-3627] | added lint ignore for command apt

tests/sanity/ignore-2.16.txt
These changes are needed for ansible 9 python 12
=> [ANSIENG-3627] |  Add sanity ignores 75 discovery 

docs/sample_inventories/oauth_brownfield.yml, docs/sample_inventories/oauth_greenfield.yml, plugins/modules/kafka_connectors.py
Added no_log in token field in kafka_connectors.py fileto avoid leaking idp tokens. 
Some minor lint fixes
=> [ANSIENG-3627] | no log in token in connectors and minor lint fixes

tests/sanity/ignore-2.16.txt
Removing extra ignore from sanity tests
=> [ANSIENG-3627] | remove one ignore from 7.5.x sanity tests for ansi 9

.semaphore/build_collection.sh, .semaphore/sanity_tests.sh, .semaphore/semaphore.yml, service.yml
Adding semaphore ci pipeline for basic sanity checks on Pull Requests
=> Adding CI system for running lint and sanity checks

.semaphore/semaphore.yml
Changed the branch to run pipeline tests on to be merged branch instead of master
=> Changed the branch to run pipeline tests on to-be-merged branch instead of master

docs/doc.py
Using doc.py we update VARIABLES.md file by checking variables in defaults of each role. This file missed the kafka_controller role and thus we missed adding kafka controller variables to VARIABLES.md file. 
Fixes # [(ANSIENG-3803)](https://confluentinc.atlassian.net/browse/ANSIENG-3803)
=> [ANSIENG-3803] | added controller role in doc.py to add its vars to variables.md

.ansible-lint, .semaphore/build_collection.sh, .semaphore/sanity_tests.sh, .semaphore/semaphore.yml, tests/sanity/ignore-2.16.txt
Adding semaphore ci for ansible sanity checks and galaxy importer checks
Tests run on ->
- ansible 9, python 3.12
- ansible 9, python3.11
- ansible 9, python3.10
Fixes # [(ANSIENG-2381)](https://confluentinc.atlassian.net/browse/ANSIENG-2381)
=> [ANSIENG-2381] | adding semaphore ci to 7.7.x

docs/VARIABLES.md
=> Update variables.md file with OAuth variables

plugins/filter/filters.py
=> [bug-fix] | minor bug fix

roles/common/tasks/config_validations.yml
=> [oauth-fips] | Add validation for fips+oauth

.semaphore/build_collection.sh, .semaphore/sanity_tests.sh, .semaphore/semaphore.yml
Adding semaphore ci code to run sanity and lint checks
Fixes # [(issue)](https://confluentinc.atlassian.net/browse/ANSIENG-2381)
Works in 7.7.x already. Added the same code to 7.0.x
=> [ANSIENG-2381] | Adding semaphore ci code to run sanity and lint checks

.ansible-lint, tests/sanity/ignore-2.16.txt
Adding ansible lint ignores and sanity ignores for semaphore pipeline code
=> [ANSIENG-2381] | adding ansible lint ignores and sanity ignores for semaphore pipeline code

molecule/migration_converge.yml, molecule/migration_rbac_converge.yml
pass kraft_migration as var in molecule, the support has been added in latest ansible versions
=> [mig-jon] | Fix passing kraft_migration var for tests

README.md
=> ANSIENG-4165 | Update readme

README.md
=> ANSIENG-4165 Update readme 7.1.x 

roles/kafka_controller/tasks/main.yml
=> [ANSIENG-4164] | added cp_package in kafka controller

meta/runtime.yml, roles/common/meta/main.yml, roles/control_center/meta/main.yml, roles/kafka_broker/meta/main.yml, roles/kafka_connect/meta/main.yml, roles/kafka_connect_replicator/meta/main.yml, roles/kafka_controller/meta/main.yml, roles/kafka_rest/meta/main.yml, roles/kerberos/meta/main.yml, roles/ksql/meta/main.yml, roles/schema_registry/meta/main.yml, roles/ssl/meta/main.yml, roles/variables/meta/main.yml, roles/zookeeper/meta/main.yml
=> [version-upgrade] | updating the min ansible version

README.md
=> [upd-71] | update readme

.bumpversion.cfg, CHANGELOG.rst, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Version Bump for 7.0.x Patch Release
=> Version Bump for 7.0.x Patch Release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Version Bump for 7.1.x Patch Release
=> Version Bump for 7.1.x Patch Release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Version Bump for 7.2.x Patch Release
=> Version Bump for 7.2.x Patch Release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Version Bump for 7.3.x Patch Release
=> Version Bump for 7.3.x Patch Release

roles/variables/vars/main.yml
fix kraft listener by adding 2 new properties added for using custom certs for sso in c3
=> fix kraft listener by adding 2 new properties

molecule/plaintext-rhel-customrepo/verify.yml
Fixing verify for plaintext-rhel-customrepo
=> Fixing verify for plaintext-rhel-customrepo

meta/runtime.yml, roles/common/meta/main.yml, roles/control_center/meta/main.yml, roles/kafka_broker/meta/main.yml, roles/kafka_connect/meta/main.yml, roles/kafka_connect_replicator/meta/main.yml, roles/kafka_controller/meta/main.yml, roles/kafka_rest/meta/main.yml, roles/kerberos/meta/main.yml, roles/ksql/meta/main.yml, roles/schema_registry/meta/main.yml, roles/ssl/meta/main.yml, roles/variables/meta/main.yml, roles/zookeeper/meta/main.yml
Bump minimum supported ansible version
=> Bump minimum supported ansible version

docs/VARIABLES.md, docs/sample_inventories/oauth_brownfield.yml, docs/sample_inventories/oauth_greenfield.yml, molecule/oauth-kafka-connect-replicator-mtls-rhel/molecule.yml, molecule/oauth-mtls-java11-debian/molecule.yml, molecule/oauth-mtls-ubuntu-acl/molecule.yml, molecule/oauth-plain-rhel/molecule.yml, molecule/oauth-rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/oauth-rbac-mds-kerberos-debian/molecule.yml, molecule/oauth-rbac-mds-scram-custom-rhel/molecule.yml, molecule/oauth-rbac-mtls-provided-ubuntu/molecule.yml, molecule/oauth-rbac-plain-provided-debian12/molecule.yml, molecule/oauth-rbac-plain-rhel8/molecule.yml, plugins/filter/filters.py, roles/common/tasks/rbac_setup.yml, roles/kafka_broker/tasks/health_check.yml, roles/kafka_broker/tasks/rbac.yml, roles/kafka_connect/tasks/rbac_connectors.yml, roles/kafka_controller/tasks/rbac.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
- Modified superuser variables for clientid, password and principal, 
- Updated docs to clarify oauth_user should be client id
=> [ANSIENG-4185] | Modified superuser variables for clientid, password and principal

molecule/broker-scale-up/converge.yml, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.9.txt
Fix jinja usage in assert that statement
=> Fix jinja usage in assert that statement

docs/sample_inventories/oauth_brownfield.yml, docs/sample_inventories/oauth_greenfield_non_rbac.yml
- Added a new sample inventory for non rbac oauth
- Fixed an old sample inventory by removing oauth_enabled
=> [fix-docs] | added new non rbac oauth sample inventory

molecule/oauth-rbac-plain-rhel8/verify.yml
Verify fixed for oauth-rbac-plain-rhel8
=> Verify fixed for oauth-rbac-plain-rhel8

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Version Bumps and changelog updated
=> Minor 7.7.0 release

molecule/oauth-plain-rhel/molecule.yml, molecule/scram-rhel/molecule.yml, roles/common/tasks/config_validations.yml
remove kafka_broker_configure_control_plane_listener from kraft migration tests
[semaphore test](https://semaphore.ci.confluent.io/workflows/6e50fa61-8817-46ff-986d-5a375fad7518?pipeline_id=5d9f05fc-3084-40c0-a60c-a8bc97058a14)
=>  Fix Control plane listener test

roles/variables/vars/main.yml
=> [7.7.x] | fix sanity checks

roles/variables/vars/main.yml
Fixes sanity checks by removing trailing spaces
=> Fix sanity checks

.ansible-lint, playbooks/nuke.yml
Fixed sanity checks in master before cutting 7.8.x by removing nuke and service.yml files from ansible lint checks
=> Sanity fixes in master

docs/MOLECULE_SCENARIOS.md, molecule/ksql-scale-up/molecule.yml, molecule/mtls-java11-rhel-fips/molecule.yml, molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, molecule/zookeeper-mtls-rhel/molecule.yml
This PR adds support for Alma Linux 8 and 9.
[Kraft + AMD](https://semaphore.ci.confluent.io/workflows/4a47d6b7-59ac-4dfd-8389-c6548eb532ec?pipeline_id=b66ae694-84a8-4f9f-9c83-5c368128ce69)
[ZK + ARM](https://semaphore.ci.confluent.io/workflows/7d4dfcb1-15b7-4d46-8830-a3b410ace985?pipeline_id=88d4e61a-3d05-4da6-9247-1fefe3b2f34c)
=> ANSIENG-4179 CP Ansible Support for Alma Linux 8 and 9

docs/CONTRIBUTING.md, githooks/README.md, githooks/install-githooks.sh, githooks/prepare-commit-msg, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.9.txt
This PR adds prepare-commit-msg hook to the repository.
[ANSIENG-2966]: https://confluentinc.atlassian.net/browse/ANSIENG-2966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANSIENG-2966]: https://confluentinc.atlassian.net/browse/ANSIENG-2966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANSIENG-2966]: https://confluentinc.atlassian.net/browse/ANSIENG-2966?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANSIENG-2966]: …
=> ANSIENG-2966 | add prepare-commit-msg hook (#13)

roles/variables/defaults/main.yml
This PR updates the confluent cli version.
[ZK](https://semaphore.ci.confluent.io/workflows/e62a7618-e564-4d33-92f0-ce7bca0e3d5e?pipeline_id=69c99192-e519-4d36-91c9-b12888b5c103)
[Kraft](https://semaphore.ci.confluent.io/workflows/ca9a0a25-53df-4c5e-95db-ef4db8e37d6e?pipeline_id=28011b16-e685-4dc3-91e3-6e6e0a0f09aa)
[Migration](https://semaphore.ci.confluent.io/workflows/04cde0cc-e203-443e-af41-4a74c266165a?pipeline_id=e04eca60-464f-4d12-8439-4b4a3078db49)
=> [ANSIENG-4220] | updated cli version (#26)

roles/variables/defaults/main.yml
This PR updates the confluent cli version.
[ZK](https://semaphore.ci.confluent.io/workflows/207ad981-248c-439b-bec6-f59396a16a26?pipeline_id=7c4dbc86-fcdf-4e41-ab21-a76855e63413)
[Kraft](https://semaphore.ci.confluent.io/workflows/b9d90658-3272-46ae-89c8-eba822ca1c00?pipeline_id=fcfd8401-4b8f-40f0-843b-5afdaee431eb)
=> [ANSIENG-4221] | updated cli version (#27)

roles/variables/defaults/main.yml
This PR updates the confluent cli version.
[ZK](https://semaphore.ci.confluent.io/workflows/c6e379ec-e343-41fc-89dd-d0095f4775b1?pipeline_id=bb9c201d-1317-410c-a9f2-85207dea8b20)
[Kraft](https://semaphore.ci.confluent.io/workflows/80b0239b-ae6e-46f0-b799-ad51b33384a6?pipeline_id=45b4372e-a242-40d9-a2d1-0bfb22c6db2a)
=> [ANSIENG-4222] | updated cli version (#28)

roles/variables/defaults/main.yml
This PR updates the confluent cli version.
[ZK](https://semaphore.ci.confluent.io/workflows/b2724083-139d-4f12-bad1-251994d9886d?pipeline_id=2a11607c-ca8b-4fc7-b6c1-778e79f8261b)
[Kraft](https://semaphore.ci.confluent.io/workflows/941e5a12-e570-4e52-a042-1ff040538d64?pipeline_id=058d2ad6-6ea9-4b9d-9774-2841f26ff8f3)
[Migration](https://semaphore.ci.confluent.io/workflows/beb75c72-8e74-4f79-bbf6-de2b9fea6a08?pipeline_id=6f1b40c0-4125-42b0-9e72-70962dea30cc)
=> [ANSIENG-4219] | updated cli version (#29)

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch 7.1 release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch 7.2 release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch 7.3 release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch 7.4 release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch 7.5 release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch 7.6 release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch 7.7 release

.bumpversion.cfg, CHANGELOG.rst, VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch 7.0 release

molecule/broker-scale-up/converge.yml
This PR fixes jinja template issue in molecule tests.
[Test Job](https://semaphore.ci.confluent.io/workflows/dbcc5fb2-fc4d-40a7-b641-a6b8c0152ae3?pipeline_id=62b1e0ef-f8dc-47ed-b28e-0d26d84075fa)
=> [ANSIENG-4228] | fix jinja issue (#37)

molecule/archive-plain-rhel-fips/molecule.yml, molecule/archive-plain-rhel-fips/verify.yml, molecule/archive-scram-rhel/molecule.yml, molecule/archive-scram-rhel/verify.yml
* [ANSIENG-4228] | fix molecule tests (#38)
* Fix 7.6.x molecule tests ansieng 4228 (#39)
* [ANSIENG-4228] | fix molecule tests
* [ANSIENG-4228] | fix verify
[ANSIENG-4228]: https://confluentinc.atlassian.net/browse/ANSIENG-4228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[ANSIENG-4228]: https://confluentinc.atlassian.net/browse/ANSIENG-4228?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU …
=> Pint merge issues ansieng 4228 (#54)

README.md
This PR adds Kraft Controller in readme.
NA
=> [ANSIENG-4176] | add Kraft Controller (#40)

roles/variables/defaults/main.yml
=> Update cli version

roles/variables/vars/main.yml
Update the inter broker protocol version to fix zk to kraft migration for 7.8 RC
=> Update the inter broker protocol version

plugins/modules/kafka_connectors.py
- Adding try catch to improve error handling in connectors
- Increasing timeout
Fixes # [(issue](https://confluentinc.atlassian.net/browse/ANSIENG-2374))
https://semaphore.ci.confluent.io/jobs/8988e611-75e3-45a9-ae54-60ead3a2af30/summary?report_id=4ae71336-e44b-39bf-b9d2-752e234818a5
=> [ANSIENG-2374] | Improve error handling in connectors

plugins/modules/kafka_connectors.py
- Adding try catch to improve error handling in connectors
- Increasing timeout
Fixes # [(issue](https://confluentinc.atlassian.net/browse/ANSIENG-2374))
=> [ANSIENG-2374] | improve error handling in connectors 71

molecule/archive-community-plaintext-rhel/molecule.yml
=> [ANSIENG-4309] | test fix

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> ANSIENG-4280 | Patch 7.6 release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> ANSIENG-4281 | Patch 7.5 release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> ANSIENG-4282 | Patch 7.4 release

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> ANSIENG-4283 | Patch 7.3 release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> ANSIENG-4284 | Patch 7.2 release

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> ANSIENG-4285 | Patch 7.1 release

roles/variables/vars/main.yml
This PR fixes the bug in oauthbearer.groups.claim.name value for kafka_connect.
[Job Link](https://semaphore.ci.confluent.io/workflows/e153da24-c075-47a0-abd6-a82879bee728?pipeline_id=b2843e2f-d25c-40ce-8154-0e828914610b)
=> [ANSIENG-4318] | bug fix

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> ANSIENG-3835 | Patch 7.7 release

docs/VARIABLES.md, roles/variables/defaults/main.yml
=> [md-update] | updating variables.md

.gitignore, CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/sample_inventories/rbac-over-mtls-centralized-mds, molecule/mini-setup-ext-mds-mtls/molecule.yml, molecule/mini-setup-ldap-mtls/molecule.yml, molecule/mini-setup-mtls/molecule.yml, molecule/mini-setup-oauth-mtls/molecule.yml, molecule/mini-setup-out-ldap-in-mtls/molecule.yml, molecule/mini-setup-out-oauth-in-mtls/molecule.yml
=> Update sample inventory files 7.8 to have centralized MDS as well

molecule/archive-scram-rhel/molecule.yml
This PR adds test for enabling secret protection for scram.
[Job Link](https://semaphore.ci.confluent.io/workflows/252c17ff-8eef-4b60-83ed-473e9aad8204?pipeline_id=cd0cb66a-348e-41c9-a357-7a4de59795c0
)
=> [ANSIENG-4331] | add test

.semaphore/build_collection.sh, .semaphore/sanity_tests.sh
Installing python 3.8 in semaphore blocks as it is no longer pre installed.
Fixes # [(issue)](https://confluentinc.atlassian.net/browse/ANSIENG-4328)
=> [ANSIENG-4238] | installing py 3.8 to avoid test failures

roles/variables/vars/main.yml
=> [ANSIENG-4334] | update version

roles/variables/defaults/main.yml
Update CLI version to match the current version in 7.8.
=> Bump CLI version to 4.7.0 for 7.9.x

roles/kafka_controller/tasks/get_meta_properties.yml
This PR fixes the bug while adding scram credentials in case multiple scram protocols are present. 
https://semaphore.ci.confluent.io/workflows/de248f69-e9b9-43d8-a0d9-f846317a1793?pipeline_id=31e975d0-b7f2-4b2f-b975-544b39c0c60f
=> [ANSIENG-4444] | fix scram credentials

molecule/broker-scale-up/converge.yml, molecule/broker-scale-up/verify.yml
fixing broker scale up by by converting type of broker cnt to string
[semaphore](https://semaphore.ci.confluent.io/workflows/d1f60808-fd31-4fe6-8348-c2663299f651/summary)
=> [up-test] | fixing broker scale up by by converting type of broker cnt to string

roles/common/defaults/main.yml, roles/kafka_broker/templates/kafka.yml.j2, roles/kafka_connect/files/kafka_connect.yml, roles/kafka_controller/templates/kafka.yml.j2, roles/kafka_rest/files/kafka_rest.yml, roles/ksql/files/ksql.yml, roles/schema_registry/files/schema_registry.yml, roles/zookeeper/files/zookeeper.yml
Upgrade jmxexporter version in cp-ansible to the latest along with removal of deprecated configs. https://confluentinc.atlassian.net/browse/ANSIENG-4260
https://github.com/prometheus/jmx_exporter/tree/release-1.0.1/docs
https://github.com/prometheus/jmx_exporter/tree/release-0.17.2
Upgrade jmxexporter version in cp-ansible to 1.0.1
- [✅ ] Bug fix (non-breaking change which fixes an issue)
https://semaphore.ci.confluent.io/workflows/03912630-566c-4d11-9769-9501e92381a5
With KRAFT mode enabled: https://semaphore.ci.confluent.io/workflows/dd7bfbae-b4d9-457a-ad4c-31169a525ef4
- [ ✅] My code follows the style guidelines of this project
- [ ✅] My changes generate no new warnings
=> [ANSIENG-4260] | jmxexporter version upgrade to 1.0.1

docs/MOLECULE_SCENARIOS.md, molecule/archive-plain-ubuntu/molecule.yml, molecule/mtls-java8-ubuntu/molecule.yml, molecule/mtls-ubuntu/molecule.yml, molecule/oauth-mtls-ubuntu-acl/molecule.yml, molecule/oauth-rbac-mtls-provided-ubuntu/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu/molecule.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml
Reverting molecule tests for ubuntu2404 as they are failing due to dependency on Ubuntu 2404 package availability. these changes will be reverted once ubuntu 2404 packages are available.
(https://semaphore.ci.confluent.io/workflows/ab618234-79a6-4e23-ba0f-1af0d7113752)
=> [ANSIENG-4626] | Reverting molecule tests for ubuntu2404

docs/sample_inventories/oauth_greenfield.yml
=> [ANSIENG-4506] | add ksql oauth

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Minor 7.9 release

molecule/rbac-mds-kerberos-debian/verify.yml, molecule/rbac-mds-plain-custom-rhel-fips/verify.yml, molecule/rbac-mtls-rhel8/verify.yml, molecule/rbac-scram-custom-rhel-fips/verify.yml
Adding retries to remove flakiness in c3 status check task in verify
=> [ANSIENG-4314] | fixing flakiness in c3 status check api

docs/sample_inventories/nonRBACtoRBACLdap.yml, roles/common/tasks/ubuntu.yml, roles/ksql/tasks/health_check.yml, roles/variables/defaults/main.yml
=> [ANSIENG-4506] | sanity checks fix

docs/sample_inventories/nonRBACtoRBACLdap.yml, roles/common/tasks/ubuntu.yml, roles/ksql/tasks/health_check.yml, roles/variables/defaults/main.yml
=> Sanity fix ansieng 4506

molecule/Dockerfile-ubuntu-archive.j2, molecule/Dockerfile-ubuntu-java8.j2, molecule/Dockerfile-ubuntu.j2, molecule/Dockerfile-ubuntu2004-archive.j2, molecule/Dockerfile-ubuntu2004.j2
```
throttle: 1
retries: 5
delay: 90
when:
``` …
=> [ANSIENG-4146] | fixing ubuntu test flakiness in adding openjdk repo in 7.2

playbooks/migration_precheck.yml
Added tag to to be skipped for nightly builds
Semophore job run:(https://semaphore.ci.confluent.io/workflows/b92764a7-d61a-44ad-9617-654ff2094d15?pipeline_id=bbc294dd-3b43-409a-a025-cba35c3a3ad0)
=> Migration run weekly biweekly ansieng 4193

roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml, roles/zookeeper/tasks/main.yml
Changing from 640 → 750 and including the x bit for Systemd override directory
=> [ANSIENG-3434] | Systemd override file permissions 640 → 750

molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/molecule.yml, molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, molecule/rbac-mds-mtls-custom-rhel-fips/molecule.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mtls-provided-ubuntu/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_broker/tasks/rbac.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_controller/tasks/rbac.yml, roles/variables/defaults/main.yml
Pint merge wasnt able to propagate the changes downstream due to merge conflicts. Resolved those
=> Resolving Pint Merge conflicts when merging 7.5.x to 7.6.x

molecule/oauth-rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/oauth-rbac-mtls-provided-ubuntu/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu/molecule.yml, molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, molecule/rbac-mds-mtls-custom-rhel-fips/molecule.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_broker/tasks/rbac.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_controller/tasks/rbac.yml, roles/variables/defaults/main.yml
Pint merge wasnt able to propagate the changes downstream due to merge conflicts. Resolved those
=> Resolving Pint Merge conflicts when merging 7.7.x to 7.8.x

molecule/oauth-rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/oauth-rbac-mtls-provided-ubuntu/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu2004/molecule.yml, molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, molecule/rbac-mds-mtls-custom-rhel-fips/molecule.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_broker/tasks/rbac.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_controller/tasks/rbac.yml, roles/variables/defaults/main.yml
Pint merge wasnt able to propagate the changes downstream due to merge conflicts. Resolved those
=> Resolving Pint Merge conflicts when merging 76 to 77

molecule/oauth-rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/oauth-rbac-mtls-provided-ubuntu/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu/molecule.yml, molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, molecule/rbac-mds-mtls-custom-rhel-fips/molecule.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_broker/tasks/rbac.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_controller/tasks/rbac.yml, roles/variables/defaults/main.yml
Pint merge wasnt able to propagate the changes downstream due to merge conflicts. Resolved those
=> Resolving Pint Merge conflicts when merging 7.8.x to 7.9.x

molecule/oauth-rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/oauth-rbac-mtls-provided-ubuntu/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu/molecule.yml, molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, molecule/rbac-mds-mtls-custom-rhel-fips/molecule.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml
In 7.8 custom certs generation we changed the OU of principal. This change was made as this principal needs to go as argument in url for rbac and urls cant have spaces. Thus corresponding to that test side also we need to update the principals
[semaphore
](https://semaphore.ci.confluent.io/workflows/25e197c8-5beb-460d-8068-1fa791f414be?pipeline_id=71c5e599-72be-4a66-8a17-f3b44d152654)
=> [ANSIENG-3858] | Changing the cert principals in molecule tests

molecule/rbac-mtls-rhel-fips/molecule.yml, roles/kafka_broker/tasks/main.yml
resolving pint merge conflicts
=> Resolving pint Merge conflicts for 7.7.x to 7.8.x merge 

molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mtls-provided-ubuntu/molecule.yml
For zk to kraft migration kraft cert principal has _migration in subject name. Therefore it should be added in the super users.
[semaphore](https://semaphore.ci.confluent.io/workflows/4620f626-cf4a-40da-b627-4b45184c1ff2?pipeline_id=1ab829ed-3423-47fa-aa94-bd6880045a32)
=> Fix migration tests super users ansieng 3858

docs/sample_inventories/nonRBACtoRBACLdap.yml
=> Removing trailing space for sanity checks to pass

roles/kafka_broker/tasks/main.yml, roles/kafka_controller/tasks/main.yml
=> Changing fail+ignore errors back to debug to fix sanity checks

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.7 Patch Release Version Bump, docs update

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.6 Patch Release Version Bump, docs update

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.4 Patch Release Version Bump, docs update

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.2 Patch Release Version Bump, docs update

.bumpversion.cfg, CHANGELOG.rst, docs/VARIABLES.md, galaxy.yml, molecule/plaintext-rhel/verify.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 7.1 Patch Release Version Bump, docs update

roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml, roles/zookeeper/tasks/main.yml
[Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.](https://github.com/confluentinc/cp-ansible/pull/1917)
=> [ANSIENG-3434] | Fix Systemd override file permissions 7.1.x to 7.4.x

roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/schema_registry/tasks/main.yml, roles/zookeeper/tasks/main.yml
=> [ANSIENG-3434] | Service Override Directory file permission 640 -> 750

CHANGELOG.rst
=> 7.4 Changelog updated

CHANGELOG.rst, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md
=> 7.8 Changelog updated

roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> [ANSIENG-4623] | Update log4j2 file path

docs/VARIABLES.md, roles/variables/defaults/main.yml
=> Bump CLI version to 4.24.0 for 8.0.x

plugins/filter/filters.py, roles/variables/vars/main.yml
=> [ANSIENG-4731] | Update OAuthbearer login and server classes FQDN names

roles/variables/vars/main.yml
=> [ANSIENG-4745] | Remove 2 properties for monitoring interceptor

docs/VARIABLES.md, roles/variables/defaults/main.yml
Update CLI version to include `confluent local services` fixes.
=> Bump CLI version to 4.26.0 for 8.0.x

molecule/oauth-plain-archive/verify.yml, roles/control_center_next_gen/templates/prometheus_generated_overlay.yml.j2, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> [ANSIENG-4865][ANSIENG-4611] Use Correct Keystore for Kafka Controller

roles/variables/vars/main.yml
=> Add Trigger rules explicitly in control-center-next-gen

CHANGELOG.rst, docs/VARIABLES.md, roles/variables/defaults/main.yml
=> Bump CLI version to 3.65.0 for 7.4.x

CHANGELOG.rst, docs/VARIABLES.md, roles/variables/defaults/main.yml
=> Bump CLI version to 3.65.0 for 7.5.x

CHANGELOG.rst, docs/VARIABLES.md, roles/variables/defaults/main.yml
=> Bump CLI version to 3.65.0 for 7.6.x

roles/control_center/templates/jaas.conf.j2, roles/kafka_broker/templates/kafka_server_jaas.conf.j2, roles/kafka_rest/templates/jaas.conf.j2, roles/ksql/templates/jaas.conf.j2, roles/schema_registry/templates/jaas.conf.j2, roles/variables/vars/main.yml
Jetty 12 removed the artifact org.eclipse.jetty.jaas and now we are using org.eclipse.jetty.security. 
=> Jetty upgrade ansieng 4714

docs/hosts_example.yml, docs/sample_inventories/single_dev_node.yml, molecule/plaintext-rhel-customrepo/prepare.yml, roles/common/defaults/main.yml
JMX Exporter Version upgraded to 0.20.0.
More info - https://semaphore.ci.confluent.io/jobs/74f0f862-34aa-4989-a269-436e761627b0
=> [ANSIENG-4750] | JMX Exporter Version Upgrade to 0.20.0

molecule/mtls-customcerts-rhel/molecule.yml, molecule/oauth-archive-plain-ubuntu2004/molecule.yml
=> [ANSIENG-4618] | fix `mtls-customcerts-rhel` & `oauth-plain-archive-ubuntu2004`

roles/control_center_next_gen/templates/prometheus_generated_overlay.yml.j2
=> [ANSIENG-5127] | Remove server_name from prometheus_generated.yml

roles/control_center_next_gen/templates/prometheus_generated_overlay.yml.j2
=> [ANSIENG-5131]Add CA file

molecule/Dockerfile-debian-java8.j2, molecule/Dockerfile-debian10.j2, molecule/Dockerfile-ubuntu-java11.j2, molecule/Dockerfile-ubuntu-java8.j2, molecule/Dockerfile-ubuntu.j2, playbooks/all.yml
=> E2E Test Fixes

.bumpversion-ansible.cfg, .bumpversion.cfg, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, molecule/mtls-java21-rhel-fips/molecule.yml, molecule/mtls-ubuntu/molecule.yml, molecule/oauth-mtls-debian/molecule.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Bump version for 8.0.0 major release.
molecule doc update.
=> Major 7.9 release molecule doc update

.bumpversion-ansible.cfg, .bumpversion.cfg, docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
Bump version for 8.0.0 major release.
=> Major 7.9 release

docs/hosts_example.yml, docs/sample_inventories/ccloud.yml, docs/sample_inventories/ccloud_self_managed_schema_registry.yml, docs/sample_inventories/client_listener_for_ldap_users.yml, docs/sample_inventories/controller_broker_scram_kraft.yml, docs/sample_inventories/fips.yml, docs/sample_inventories/inter_broker_scram_kraft.yml, docs/sample_inventories/kerberos_kraft.yml, docs/sample_inventories/migration_sample.yml, docs/sample_inventories/migration_sample_scram.yml, docs/sample_inventories/mtls_kraft.yml, docs/sample_inventories/multi_connect_workers_on_single_node.yml, docs/sample_inventories/nonRBACtoRBACLdap.yml, docs/sample_inventories/nonRBACtoRBACOAuth.yml, docs/sample_inventories/oauth_brownfield.yml, docs/sample_inventories/oauth_greenfield.yml, docs/sample_inventories/oauth_greenfield_non_rbac.yml, docs/sample_inventories/rbac-over-mtls-centralized-mds.yml, docs/sample_inventories/rbac-over-mtls-file-based-user-store.yml, docs/sample_inventories/rbac-over-oauth-and-mtls.yml, docs/sample_inventories/rbac_centralized_mds_kerberos_custom_certs_example.yml, docs/sample_inventories/rbac_kerberos_custom_certs_example.yml, docs/sample_inventories/rbac_mutiple_ksql.yml, docs/sample_inventories/rbac_sso_c3.yml, docs/sample_inventories/sasl_ssl_kraft.yml, docs/sample_inventories/single_dev_node.yml
=> [ANSIENG-4612] Add Sample Inventory Files for C3NG

molecule/plaintext-rhel-customrepo/molecule.yml
=> [e2e-fix] | fix `plaintext-rhel-customrepo`

roles/control_center_next_gen/tasks/copy_dependency_configs.yml, roles/control_center_next_gen/tasks/prometheus_config_overlay.yml
=> Fix Sanity Warnings

docs/sample_inventories/control_center_next_gen_with_cp_790.yml
=> [ANSIENG-4612] | Add sample inventory for CP 790 against C3PP

molecule/archive-plain-debian/molecule.yml, molecule/kerberos-rhel/verify.yml, roles/kafka_connect/tasks/confluent_hub.yml, roles/kafka_connect/tasks/connect_plugins.yml
Replace confluent-hub with confluent CLI.
Tests Run - https://semaphore.ci.confluent.io/workflows/13da0815-9a18-4067-a81e-7acdb7a12d0f, https://semaphore.ci.confluent.io/workflows/df17ba7b-def5-4bdf-a23a-08d15e85e67c
=> [ANSIENG-4304] | Replace confluent-hub with confluent CLI

README.md
=> [ANSIENG-4868] | update README.md

docs/VARIABLES.md, molecule/archive-plain-debian/molecule.yml, roles/variables/defaults/main.yml
=> Bump CLI version to 4.27.0 for 8.0.x

docs/sample_inventories/rbac-over-mtls-file-based-user-store.yml, molecule/certs-create.sh, molecule/oauth-rbac-kafka-connect-replicator-kerberos-mtls-custom-rhel/molecule.yml, molecule/oauth-rbac-mtls-provided-ubuntu/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-debian10/molecule.yml, molecule/rbac-kafka-connect-replicator-kerberos-mtls-custom-ubuntu/molecule.yml, molecule/rbac-mds-mtls-custom-kerberos-rhel/molecule.yml, molecule/rbac-mds-mtls-custom-rhel-fips/molecule.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml, molecule/schema-validation/molecule.yml, roles/common/defaults/main.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/set_principal.yml, roles/kafka_connect/tasks/deploy_connectors.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/kafka_controller/tasks/set_principal.yml, roles/kafka_rest/tasks/main.yml, roles/ksql/tasks/main.yml, roles/ksql/tasks/set_principal.yml, roles/schema_registry/tasks/main.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> 79 hotfix cs dev add rp c3 listeners

docs/VARIABLES.md, molecule/archive-plain-debian/molecule.yml, molecule/archive-plain-rhel-fips/verify.yml, molecule/mtls-debian12/verify.yml, molecule/oauth-plain-rhel/verify.yml, molecule/oauth-rbac-plain-provided-debian12/verify.yml, roles/variables/defaults/main.yml
=> Master merge conflict resolve

roles/common/defaults/main.yml
=> Define Independent packaging URL default again

docs/VARIABLES.md, roles/variables/defaults/main.yml
https://confluent.slack.com/archives/C07648S1FMX/p1747810484922799
=> Update `confluent_control_center_next_gen_package_version` to 2.2.0

.gitignore, molecule/oauth-rbac-mtls-provided-ubuntu/verify.yml, molecule/rbac-mds-mtls-existing-keystore-truststore-ubuntu/verify.yml, molecule/schema-validation/molecule.yml, molecule/schema-validation/verify.yml, plugins/modules/kafka_connectors.py
=> [in-tests] | fixing test validations

molecule/archive-plain-rhel-fips/verify.yml, molecule/kerberos-rhel/verify.yml, molecule/oauth-plain-debian12/verify.yml, molecule/oauth-plain-rhel/verify.yml
=> [ANSIENG-4866] Fix Expect strings

docs/VARIABLES.md, docs/sample_inventories/rbac-ldap-to-mtls-brownfield/README.md, docs/sample_inventories/rbac-ldap-to-mtls-brownfield/step0_ldap_setup.yml, docs/sample_inventories/rbac-ldap-to-mtls-brownfield/step1_enable_mtls.yml, docs/sample_inventories/rbac-ldap-to-mtls-brownfield/step2_client_migration.yml, docs/sample_inventories/rbac-ldap-to-mtls-brownfield/step3_required.yml, docs/sample_inventories/rbac-ldap-to-mtls-brownfield/step4_ldap_to_sso.yml, docs/sample_inventories/rbac-over-mtls-centralized-mds, docs/sample_inventories/rbac-over-mtls-file-based-user-store.yml, docs/sample_inventories/rbac-over-oauth-and-mtls.yml, tests/sanity/ignore-2.11.txt, tests/sanity/ignore-2.12.txt, tests/sanity/ignore-2.13.txt, tests/sanity/ignore-2.14.txt, tests/sanity/ignore-2.15.txt, tests/sanity/ignore-2.16.txt, tests/sanity/ignore-2.9.txt
=> Updated the sample inventory files

meta/runtime.yml, molecule/Dockerfile-debian-archive.j2, molecule/Dockerfile-debian-java8.j2, molecule/Dockerfile-debian.j2, roles/common/meta/main.yml, roles/control_center/meta/main.yml, roles/kafka_broker/meta/main.yml, roles/kafka_connect/meta/main.yml, roles/kafka_connect_replicator/meta/main.yml, roles/kafka_controller/meta/main.yml, roles/kafka_rest/meta/main.yml, roles/kerberos/meta/main.yml, roles/ksql/meta/main.yml, roles/schema_registry/meta/main.yml, roles/ssl/meta/main.yml, roles/variables/meta/main.yml, roles/zookeeper/meta/main.yml, test_roles/confluent.test.kerberos/meta/main.yml, test_roles/confluent.test.kerberos/tasks/main.yml
Ansible 9 support enabled for q2 patch release
=> Ansible9 testing with 7.6

meta/runtime.yml, molecule/Dockerfile-debian-archive.j2, molecule/Dockerfile-debian-java11.j2, molecule/Dockerfile-debian-java8.j2, molecule/Dockerfile-debian.j2, roles/common/meta/main.yml, roles/common/tasks/debian.yml, roles/control_center/meta/main.yml, roles/kafka_broker/meta/main.yml, roles/kafka_connect/meta/main.yml, roles/kafka_connect_replicator/meta/main.yml, roles/kafka_controller/meta/main.yml, roles/kafka_rest/meta/main.yml, roles/kerberos/meta/main.yml, roles/ksql/meta/main.yml, roles/schema_registry/meta/main.yml, roles/ssl/meta/main.yml, roles/variables/meta/main.yml, roles/zookeeper/meta/main.yml, test_roles/confluent.test.kerberos/tasks/main.yml
ansible 9 support added to 7.4.x
=> Ansible9 testing with 7.4

docs/VARIABLES.md, molecule/archive-plain-rhel-fips/log4j2/kafka-log4j2.yaml, molecule/archive-plain-rhel-fips/verify.yml, molecule/oauth-plain-debian12/verify.yml, molecule/oauth-plain-rhel/verify.yml, molecule/rbac-kerberos-debian12/verify.yml, plugins/modules/update_log4j2.py, roles/control_center_next_gen/tasks/main.yml, roles/variables/defaults/main.yml
=> Update tests for log redactor

roles/control_center_next_gen/tasks/main.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> [ANSIENG-4742] | using token cert handler in c3 next gen

plugins/filter/filters.py, roles/common/tasks/get_authorization_token.yml, roles/kafka_connect/tasks/rbac_connectors.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/schema_registry/tasks/health_check.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> fixed missing send_client_cert var issue

roles/common/tasks/config_validations.yml
=> [ANSIENG-4744] Fix Control_Center_Next_gen Host validation

roles/common/tasks/config_validations.yml, roles/variables/vars/main.yml
C3++ oauth config fix for ksql client 
semaphore job run https://semaphore.ci.confluent.io/workflows/5d5d8da1-1543-4e33-915d-c4203f3c01a9?pipeline_id=d8558238-c6c9-4c41-8182-18f6d0de785b
=> C3++ oauth config fix for ksql client 

roles/common/tasks/config_validations.yml
=> Stop Playbook if old `control_center` is present in host

README.md
=> [ANSIENG-5269] | Fix Readme URLs to work with automation hub

roles/variables/vars/main.yml
Fixes # [(issue)](https://confluentinc.atlassian.net/browse/ANSIENG-4254)
[semaphore](https://semaphore.ci.confluent.io/workflows/f6f410e6-e475-40c6-ab77-fc4919ea6d32?pipeline_id=3ceb445e-cf0d-4d10-b63a-596f9adc3d47)
=> [ANSIENG-4254] | fix non rbac ksql mtls

CHANGELOG.rst, molecule/archive-community-plaintext-rhel/molecule.yml, molecule/archive-scram-rhel/molecule.yml, molecule/kerberos-rhel/molecule.yml, molecule/oauth-rbac-plain-rhel8/molecule.yml, molecule/plain-customcerts-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml
=> Ansieng 3419

docs/MOLECULE_SCENARIOS.md, docs/VARIABLES.md, docs/sample_inventories/rbac-ldap-to-mtls-brownfield/README.md, docs/sample_inventories/rbac-ldap-to-mtls-brownfield/step1_enable_mtls.yml, docs/sample_inventories/rbac-ldap-to-mtls-brownfield/step3_required.yml, docs/sample_inventories/rbac-oauth-to-mtls-brownfield/README.md, docs/sample_inventories/rbac-oauth-to-mtls-brownfield/step0_oauth_sso_setup.yml, docs/sample_inventories/rbac-oauth-to-mtls-brownfield/step1_enable_mtls.yml, docs/sample_inventories/rbac-oauth-to-mtls-brownfield/step2_client_migration.yml, docs/sample_inventories/rbac-oauth-to-mtls-brownfield/step3_required.yml, docs/sample_inventories/rbac-over-mtls-centralized-mds.yml, docs/sample_inventories/rbac-over-mtls-file-based-user-store.yml, docs/sample_inventories/rbac-over-oauth-and-mtls.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Fix Docs, Sample Inventory files 7.8.x

molecule/archive-community-plaintext-rhel/molecule.yml, molecule/archive-scram-rhel/molecule.yml, molecule/kerberos-rhel/molecule.yml, molecule/plain-customcerts-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml
oraclelinux-slim -> redhat/ubi-minimal
=> [ANSIENG-4663] | oraclelinux-slim -> redhat/ubi-minimal

molecule/archive-community-plaintext-rhel/molecule.yml, molecule/archive-scram-rhel/molecule.yml, molecule/kerberos-rhel/molecule.yml, molecule/oauth-rbac-plain-rhel8/molecule.yml, molecule/plain-customcerts-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel-fips/molecule.yml, molecule/rbac-mtls-rhel8/molecule.yml
=> [ANSIENG-4663] | oraclelinux -> ubi-minimal image

molecule/oauth-rbac-plain-rhel8/molecule.yml
=> [ANSIENG-4663] | oracleLinux-> ubi image

.ansible-lint
=> [ANSIENG-5272] | Fix ansible-lint warnings

CHANGELOG.rst
Changelog updated for patch release
=> [ANSIENG-4663] | changelog update

CHANGELOG.rst
Changelog updated for patch release
=> [ANSIENG-4663] | changelog updated

CHANGELOG.rst
Changelog updated for patch release
=> Changelog 7.7 ansieng 4663

CHANGELOG.rst
Changelog updated for patch release
=> Changelog 7.9 ansieng 4663

.bumpversion-ansible.cfg, .bumpversion.cfg, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch 7.8 release

roles/kafka_broker/tasks/main.yml
…ers when hostname_aliasing_enabled=true
=> Clone #1559 on 7.2.x

molecule/oauth-plain-rhel/molecule.yml
=> Merge conflict res

molecule/plain-rhel/test-jars/ibm-mq-connector.jar
=> Conflict resolve fix

molecule/oauth-plain-rhel/molecule.yml, molecule/oauth-plain-rhel/test-jars/ibm-mq-connector.jar, molecule/oauth-plain-rhel/verify.yml, roles/kafka_connect/tasks/main.yml
=> fixing kafka connect files issue

roles/common/tasks/config_validations.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
added schema registry properties to enable UsmSchemaRegistryExtension and setup Forwarder Configs
=> [ANSIENG-5658] | usm enablement for sr

galaxy.yml, roles/ssl/tasks/build_certificate_chain.yml, roles/ssl/tasks/custom_certs.yml, roles/ssl/tasks/self_signed_certs.yml
=> Resolve pint-merge Conficts

playbooks/all.yml, playbooks/tasks/certificate_authority.yml, roles/common/tasks/config_validations.yml, roles/common/tasks/validate_usm_agent_configs.yml, roles/usm_agent/defaults/main.yml, roles/usm_agent/tasks/health_check.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> [ANSIENG-5698] | USM Agent Enhancements: Bug Fixes, Config Validations, Listener Port Addition

.ansible-lint, playbooks/tasks/certificate_authority.yml, roles/common/handlers/main.yml, roles/common/tasks/config_validations.yml, roles/common/tasks/debian.yml, roles/common/tasks/fips-redhat.yml, roles/common/tasks/redhat.yml, roles/common/tasks/secrets_protection.yml, roles/common/tasks/ubuntu.yml, roles/kafka_broker/tasks/get_meta_properties.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_connect/tasks/confluent_hub.yml, roles/kafka_connect/tasks/connect_plugins.yml, roles/kafka_connect/tasks/main.yml, roles/kafka_connect_replicator/tasks/main.yml, roles/kafka_controller/tasks/get_meta_properties.yml, roles/kafka_controller/tasks/main.yml, roles/kafka_rest/tasks/main.yml, roles/kerberos/tasks/main.yml, roles/ksql/tasks/main.yml, roles/ksql/tasks/set_principal.yml, roles/schema_registry/tasks/main.yml, roles/ssl/tasks/create_keystores_from_certs.yml, roles/ssl/tasks/custom_certs.yml, roles/ssl/tasks/export_certs_from_keystore_and_truststore.yml, roles/ssl/tasks/import_ca_chain.yml, roles/ssl/tasks/self_signed_certs.yml
=> [ANSIENG-5630] | ansible-lint fixes (#2181)

roles/variables/defaults/main.yml
=> [ANSIENG-5691] | USM Agent variables fix

.bumpversion-ansible.cfg, .bumpversion.cfg, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Minor 8.0 release

molecule/Dockerfile-debian10-archive.j2
=> [ANSIENG-5719] | change debian10 repo link

roles/common/tasks/debian.yml, roles/common/tasks/ubuntu.yml, roles/usm_agent/defaults/main.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> [ANSIENG-5691] | Update USM Agent package handling for debain/ubuntu

README.md, roles/common/tasks/configure_logredactor.yml, roles/common/tasks/rbac_setup.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_controller/tasks/get_meta_properties.yml, roles/zookeeper/tasks/main.yml
=> Ansible Lint Fixes for RedHat Certification (#2229)

roles/common/tasks/configure_logredactor.yml, roles/common/tasks/rbac_setup.yml, roles/control_center/tasks/main.yml, roles/kafka_broker/tasks/main.yml, roles/zookeeper/tasks/main.yml
=> Ansible Lint Fixes For RedHat Certification

docs/TAGS.md, molecule/mtls-ubuntu/jolokia_access_test.xml, molecule/mtls-ubuntu/molecule.yml, molecule/mtls-ubuntu/verify.yml, roles/common/tasks/component_validations.yml, roles/kafka_broker/tasks/main.yml, roles/kafka_broker/templates/jolokia_access_control_default.xml, roles/kafka_broker/templates/kafka_jolokia.properties.j2, roles/kafka_connect/tasks/main.yml, roles/kafka_connect/templates/jolokia_access_control_default.xml, roles/kafka_connect/templates/kafka_connect_jolokia.properties.j2, roles/kafka_connect_replicator/tasks/main.yml, roles/kafka_connect_replicator/templates/jolokia_access_control_default.xml, roles/kafka_connect_replicator/templates/kafka-connect-replicator-jolokia.properties.j2, roles/kafka_controller/tasks/main.yml, roles/kafka_controller/templates/jolokia_access_control_default.xml, roles/kafka_controller/templates/kafka_jolokia.properties.j2, roles/kafka_rest/tasks/main.yml, roles/kafka_rest/templates/jolokia_access_control_default.xml, roles/kafka_rest/templates/kafka_rest_jolokia.properties.j2, roles/ksql/tasks/main.yml, roles/ksql/templates/jolokia_access_control_default.xml, roles/ksql/templates/ksql_jolokia.properties.j2, roles/schema_registry/tasks/main.yml, roles/schema_registry/templates/jolokia_access_control_default.xml, roles/schema_registry/templates/schema_registry_jolokia.properties.j2, roles/variables/defaults/main.yml
=> Jolokia for 8.0

.bumpversion-ansible.cfg, .bumpversion.cfg, CHANGELOG.rst, README.md, docs/VARIABLES.md, galaxy.yml, roles/variables/defaults/main.yml, roles/variables/vars/main.yml
=> Patch 8.0 release

docs/VARIABLES.md, molecule/archive-plain-debian/molecule.yml, roles/variables/defaults/main.yml
=> Bump CLI version to 4.39.0 for 8.1.x

molecule/mtls-ubuntu/molecule.yml, molecule/mtls-ubuntu/verify.yml, roles/variables/defaults/main.yml, roles/variables/tasks/main.yml, roles/variables/vars/main.yml
=> [ANSIENG-2858]-changes for brokers
